-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [signal_crypto]: function definitions
import Aeneas
import Libsignal.Crypto.Types
import Libsignal.Crypto.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace signal_crypto

/-- Trait implementation: [subtle::{subtle::ConstantTimeEq for u8}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/subtle-2.6.1/src/lib.rs', lines 346:8-346:36
    Name pattern: [subtle::ConstantTimeEq<u8>] -/
@[reducible, rust_trait_impl "subtle::ConstantTimeEq<u8>"]
def U8.Insts.SubtleConstantTimeEq : subtle.ConstantTimeEq Std.U8 := {
  ct_eq := U8.Insts.SubtleConstantTimeEq.ct_eq
}

/-- Trait implementation: [typenum::bit::{core::clone::Clone for typenum::bit::B0}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/bit.rs', lines 18:41-18:46
    Name pattern: [core::clone::Clone<typenum::bit::B0>] -/
@[reducible, rust_trait_impl "core::clone::Clone<typenum::bit::B0>"]
def typenum.bit.B0.Insts.CoreCloneClone : core.clone.Clone typenum.bit.B0 := {
  clone := typenum.bit.B0.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [typenum::bit::{core::marker::Copy for typenum::bit::B0}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/bit.rs', lines 18:48-18:52
    Name pattern: [core::marker::Copy<typenum::bit::B0>] -/
@[reducible, rust_trait_impl "core::marker::Copy<typenum::bit::B0>"]
def typenum.bit.B0.Insts.CoreMarkerCopy : core.marker.Copy typenum.bit.B0 := {
  cloneInst := typenum.bit.B0.Insts.CoreCloneClone
}

/-- Trait implementation: [typenum::bit::{core::default::Default for typenum::bit::B0}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/bit.rs', lines 18:67-18:74
    Name pattern: [core::default::Default<typenum::bit::B0>] -/
@[reducible, rust_trait_impl "core::default::Default<typenum::bit::B0>"]
def typenum.bit.B0.Insts.CoreDefaultDefault : core.default.Default
  typenum.bit.B0 := {
  default := typenum.bit.B0.Insts.CoreDefaultDefault.default
}

/-- Trait implementation: [typenum::bit::{core::clone::Clone for typenum::bit::B1}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/bit.rs', lines 31:41-31:46
    Name pattern: [core::clone::Clone<typenum::bit::B1>] -/
@[reducible, rust_trait_impl "core::clone::Clone<typenum::bit::B1>"]
def typenum.bit.B1.Insts.CoreCloneClone : core.clone.Clone typenum.bit.B1 := {
  clone := typenum.bit.B1.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [typenum::bit::{core::marker::Copy for typenum::bit::B1}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/bit.rs', lines 31:48-31:52
    Name pattern: [core::marker::Copy<typenum::bit::B1>] -/
@[reducible, rust_trait_impl "core::marker::Copy<typenum::bit::B1>"]
def typenum.bit.B1.Insts.CoreMarkerCopy : core.marker.Copy typenum.bit.B1 := {
  cloneInst := typenum.bit.B1.Insts.CoreCloneClone
}

/-- Trait implementation: [typenum::bit::{core::default::Default for typenum::bit::B1}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/bit.rs', lines 31:67-31:74
    Name pattern: [core::default::Default<typenum::bit::B1>] -/
@[reducible, rust_trait_impl "core::default::Default<typenum::bit::B1>"]
def typenum.bit.B1.Insts.CoreDefaultDefault : core.default.Default
  typenum.bit.B1 := {
  default := typenum.bit.B1.Insts.CoreDefaultDefault.default
}

/-- Trait implementation: [typenum::sealed::{typenum::sealed::Sealed for typenum::bit::B0}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/lib.rs', lines 156:4-156:22
    Name pattern: [typenum::sealed::Sealed<typenum::bit::B0>] -/
@[reducible, rust_trait_impl "typenum::sealed::Sealed<typenum::bit::B0>"]
def typenum.bit.B0.Insts.TypenumSealedSealed : typenum.sealed.Sealed
  typenum.bit.B0 := {
}

/-- Trait implementation: [typenum::bit::{typenum::marker_traits::Bit for typenum::bit::B0}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/bit.rs', lines 43:0-43:15
    Name pattern: [typenum::marker_traits::Bit<typenum::bit::B0>] -/
@[reducible, rust_trait_impl "typenum::marker_traits::Bit<typenum::bit::B0>"]
def typenum.bit.B0.Insts.TypenumMarker_traitsBit : typenum.marker_traits.Bit
  typenum.bit.B0 := {
  U8 := typenum.bit.B0.Insts.TypenumMarker_traitsBit.U8
  BOOL := typenum.bit.B0.Insts.TypenumMarker_traitsBit.BOOL
  sealedSealedInst := typenum.bit.B0.Insts.TypenumSealedSealed
  coremarkerCopyInst := typenum.bit.B0.Insts.CoreMarkerCopy
  coredefaultDefaultInst := typenum.bit.B0.Insts.CoreDefaultDefault
  new := typenum.bit.B0.Insts.TypenumMarker_traitsBit.new
  to_u8 := typenum.bit.B0.Insts.TypenumMarker_traitsBit.to_u8
  to_bool := typenum.bit.B0.Insts.TypenumMarker_traitsBit.to_bool
}

/-- Trait implementation: [typenum::sealed::{typenum::sealed::Sealed for typenum::bit::B1}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/lib.rs', lines 157:4-157:22
    Name pattern: [typenum::sealed::Sealed<typenum::bit::B1>] -/
@[reducible, rust_trait_impl "typenum::sealed::Sealed<typenum::bit::B1>"]
def typenum.bit.B1.Insts.TypenumSealedSealed : typenum.sealed.Sealed
  typenum.bit.B1 := {
}

/-- Trait implementation: [typenum::bit::{typenum::marker_traits::Bit for typenum::bit::B1}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/bit.rs', lines 61:0-61:15
    Name pattern: [typenum::marker_traits::Bit<typenum::bit::B1>] -/
@[reducible, rust_trait_impl "typenum::marker_traits::Bit<typenum::bit::B1>"]
def typenum.bit.B1.Insts.TypenumMarker_traitsBit : typenum.marker_traits.Bit
  typenum.bit.B1 := {
  U8 := typenum.bit.B1.Insts.TypenumMarker_traitsBit.U8
  BOOL := typenum.bit.B1.Insts.TypenumMarker_traitsBit.BOOL
  sealedSealedInst := typenum.bit.B1.Insts.TypenumSealedSealed
  coremarkerCopyInst := typenum.bit.B1.Insts.CoreMarkerCopy
  coredefaultDefaultInst := typenum.bit.B1.Insts.CoreDefaultDefault
  new := typenum.bit.B1.Insts.TypenumMarker_traitsBit.new
  to_u8 := typenum.bit.B1.Insts.TypenumMarker_traitsBit.to_u8
  to_bool := typenum.bit.B1.Insts.TypenumMarker_traitsBit.to_bool
}

/-- Trait implementation: [typenum::sealed::{typenum::sealed::Sealed for typenum::uint::UTerm}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/lib.rs', lines 159:4-159:25
    Name pattern: [typenum::sealed::Sealed<typenum::uint::UTerm>] -/
@[reducible, rust_trait_impl "typenum::sealed::Sealed<typenum::uint::UTerm>"]
def typenum.uint.UTerm.Insts.TypenumSealedSealed : typenum.sealed.Sealed
  typenum.uint.UTerm := {
}

/-- Trait implementation: [typenum::sealed::{typenum::sealed::Sealed for typenum::uint::UInt<U, B>}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/lib.rs', lines 160:4-160:51
    Name pattern: [typenum::sealed::Sealed<typenum::uint::UInt<@U, @B>>] -/
@[reducible, rust_trait_impl
  "typenum::sealed::Sealed<typenum::uint::UInt<@U, @B>>"]
def typenum.uint.UInt.Insts.TypenumSealedSealed {U : Type} {B : Type}
  (marker_traitsUnsignedInst : typenum.marker_traits.Unsigned U)
  (marker_traitsBitInst : typenum.marker_traits.Bit B) : typenum.sealed.Sealed
  (typenum.uint.UInt U B) := {
}

/-- Trait implementation: [typenum::uint::{core::clone::Clone for typenum::uint::UTerm}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/uint.rs', lines 48:41-48:46
    Name pattern: [core::clone::Clone<typenum::uint::UTerm>] -/
@[reducible, rust_trait_impl "core::clone::Clone<typenum::uint::UTerm>"]
def typenum.uint.UTerm.Insts.CoreCloneClone : core.clone.Clone
  typenum.uint.UTerm := {
  clone := typenum.uint.UTerm.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [typenum::uint::{core::marker::Copy for typenum::uint::UTerm}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/uint.rs', lines 48:48-48:52
    Name pattern: [core::marker::Copy<typenum::uint::UTerm>] -/
@[reducible, rust_trait_impl "core::marker::Copy<typenum::uint::UTerm>"]
def typenum.uint.UTerm.Insts.CoreMarkerCopy : core.marker.Copy
  typenum.uint.UTerm := {
  cloneInst := typenum.uint.UTerm.Insts.CoreCloneClone
}

/-- Trait implementation: [typenum::uint::{core::default::Default for typenum::uint::UTerm}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/uint.rs', lines 48:67-48:74
    Name pattern: [core::default::Default<typenum::uint::UTerm>] -/
@[reducible, rust_trait_impl "core::default::Default<typenum::uint::UTerm>"]
def typenum.uint.UTerm.Insts.CoreDefaultDefault : core.default.Default
  typenum.uint.UTerm := {
  default := typenum.uint.UTerm.Insts.CoreDefaultDefault.default
}

/-- Trait implementation: [typenum::uint::{typenum::marker_traits::Unsigned for typenum::uint::UTerm}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/uint.rs', lines 60:0-60:23
    Name pattern: [typenum::marker_traits::Unsigned<typenum::uint::UTerm>] -/
@[reducible, rust_trait_impl
  "typenum::marker_traits::Unsigned<typenum::uint::UTerm>"]
def typenum.uint.UTerm.Insts.TypenumMarker_traitsUnsigned :
  typenum.marker_traits.Unsigned typenum.uint.UTerm := {
  U8 := typenum.uint.UTerm.Insts.TypenumMarker_traitsUnsigned.U8
  U16 := typenum.uint.UTerm.Insts.TypenumMarker_traitsUnsigned.U16
  U32 := typenum.uint.UTerm.Insts.TypenumMarker_traitsUnsigned.U32
  U64 := typenum.uint.UTerm.Insts.TypenumMarker_traitsUnsigned.U64
  USIZE := typenum.uint.UTerm.Insts.TypenumMarker_traitsUnsigned.USIZE
  I8 := typenum.uint.UTerm.Insts.TypenumMarker_traitsUnsigned.I8
  I16 := typenum.uint.UTerm.Insts.TypenumMarker_traitsUnsigned.I16
  I32 := typenum.uint.UTerm.Insts.TypenumMarker_traitsUnsigned.I32
  I64 := typenum.uint.UTerm.Insts.TypenumMarker_traitsUnsigned.I64
  ISIZE := typenum.uint.UTerm.Insts.TypenumMarker_traitsUnsigned.ISIZE
  sealedSealedInst := typenum.uint.UTerm.Insts.TypenumSealedSealed
  coremarkerCopyInst := typenum.uint.UTerm.Insts.CoreMarkerCopy
  coredefaultDefaultInst := typenum.uint.UTerm.Insts.CoreDefaultDefault
  to_u8 := typenum.uint.UTerm.Insts.TypenumMarker_traitsUnsigned.to_u8
  to_u16 := typenum.uint.UTerm.Insts.TypenumMarker_traitsUnsigned.to_u16
  to_u32 := typenum.uint.UTerm.Insts.TypenumMarker_traitsUnsigned.to_u32
  to_u64 := typenum.uint.UTerm.Insts.TypenumMarker_traitsUnsigned.to_u64
  to_usize := typenum.uint.UTerm.Insts.TypenumMarker_traitsUnsigned.to_usize
  to_i8 := typenum.uint.UTerm.Insts.TypenumMarker_traitsUnsigned.to_i8
  to_i16 := typenum.uint.UTerm.Insts.TypenumMarker_traitsUnsigned.to_i16
  to_i32 := typenum.uint.UTerm.Insts.TypenumMarker_traitsUnsigned.to_i32
  to_i64 := typenum.uint.UTerm.Insts.TypenumMarker_traitsUnsigned.to_i64
  to_isize := typenum.uint.UTerm.Insts.TypenumMarker_traitsUnsigned.to_isize
}

/-- Trait implementation: [typenum::uint::{core::clone::Clone for typenum::uint::UInt<U, B>}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/uint.rs', lines 146:41-146:46
    Name pattern: [core::clone::Clone<typenum::uint::UInt<@U, @B>>] -/
@[reducible, rust_trait_impl "core::clone::Clone<typenum::uint::UInt<@U, @B>>"]
def typenum.uint.UInt.Insts.CoreCloneClone {U : Type} {B : Type}
  (corecloneCloneInst : core.clone.Clone U) (corecloneCloneInst1 :
  core.clone.Clone B) : core.clone.Clone (typenum.uint.UInt U B) := {
  clone := typenum.uint.UInt.Insts.CoreCloneClone.clone corecloneCloneInst
    corecloneCloneInst1
}

/-- Trait implementation: [typenum::uint::{core::marker::Copy for typenum::uint::UInt<U, B>}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/uint.rs', lines 146:48-146:52
    Name pattern: [core::marker::Copy<typenum::uint::UInt<@U, @B>>] -/
@[reducible, rust_trait_impl "core::marker::Copy<typenum::uint::UInt<@U, @B>>"]
def typenum.uint.UInt.Insts.CoreMarkerCopy {U : Type} {B : Type}
  (coremarkerCopyInst : core.marker.Copy U) (coremarkerCopyInst1 :
  core.marker.Copy B) : core.marker.Copy (typenum.uint.UInt U B) := {
  cloneInst := typenum.uint.UInt.Insts.CoreCloneClone
    coremarkerCopyInst.cloneInst coremarkerCopyInst1.cloneInst
}

/-- Trait implementation: [typenum::uint::{core::default::Default for typenum::uint::UInt<U, B>}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/uint.rs', lines 146:67-146:74
    Name pattern: [core::default::Default<typenum::uint::UInt<@U, @B>>] -/
@[reducible, rust_trait_impl
  "core::default::Default<typenum::uint::UInt<@U, @B>>"]
def typenum.uint.UInt.Insts.CoreDefaultDefault {U : Type} {B : Type}
  (coredefaultDefaultInst : core.default.Default U) (coredefaultDefaultInst1 :
  core.default.Default B) : core.default.Default (typenum.uint.UInt U B) := {
  default := typenum.uint.UInt.Insts.CoreDefaultDefault.default
    coredefaultDefaultInst coredefaultDefaultInst1
}

/-- Trait implementation: [typenum::uint::{typenum::marker_traits::Unsigned for typenum::uint::UInt<U, B>}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/uint.rs', lines 163:0-163:49
    Name pattern: [typenum::marker_traits::Unsigned<typenum::uint::UInt<@U, @B>>] -/
@[reducible, rust_trait_impl
  "typenum::marker_traits::Unsigned<typenum::uint::UInt<@U, @B>>"]
def typenum.uint.UInt.Insts.TypenumMarker_traitsUnsigned {U : Type} {B : Type}
  (marker_traitsUnsignedInst : typenum.marker_traits.Unsigned U)
  (marker_traitsBitInst : typenum.marker_traits.Bit B) :
  typenum.marker_traits.Unsigned (typenum.uint.UInt U B) := {
  U8 := typenum.uint.UInt.Insts.TypenumMarker_traitsUnsigned.U8
    marker_traitsUnsignedInst marker_traitsBitInst
  U16 := typenum.uint.UInt.Insts.TypenumMarker_traitsUnsigned.U16
    marker_traitsUnsignedInst marker_traitsBitInst
  U32 := typenum.uint.UInt.Insts.TypenumMarker_traitsUnsigned.U32
    marker_traitsUnsignedInst marker_traitsBitInst
  U64 := typenum.uint.UInt.Insts.TypenumMarker_traitsUnsigned.U64
    marker_traitsUnsignedInst marker_traitsBitInst
  USIZE := typenum.uint.UInt.Insts.TypenumMarker_traitsUnsigned.USIZE
    marker_traitsUnsignedInst marker_traitsBitInst
  I8 := typenum.uint.UInt.Insts.TypenumMarker_traitsUnsigned.I8
    marker_traitsUnsignedInst marker_traitsBitInst
  I16 := typenum.uint.UInt.Insts.TypenumMarker_traitsUnsigned.I16
    marker_traitsUnsignedInst marker_traitsBitInst
  I32 := typenum.uint.UInt.Insts.TypenumMarker_traitsUnsigned.I32
    marker_traitsUnsignedInst marker_traitsBitInst
  I64 := typenum.uint.UInt.Insts.TypenumMarker_traitsUnsigned.I64
    marker_traitsUnsignedInst marker_traitsBitInst
  ISIZE := typenum.uint.UInt.Insts.TypenumMarker_traitsUnsigned.ISIZE
    marker_traitsUnsignedInst marker_traitsBitInst
  sealedSealedInst := typenum.uint.UInt.Insts.TypenumSealedSealed
    marker_traitsUnsignedInst marker_traitsBitInst
  coremarkerCopyInst := typenum.uint.UInt.Insts.CoreMarkerCopy
    marker_traitsUnsignedInst.coremarkerCopyInst
    marker_traitsBitInst.coremarkerCopyInst
  coredefaultDefaultInst := typenum.uint.UInt.Insts.CoreDefaultDefault
    marker_traitsUnsignedInst.coredefaultDefaultInst
    marker_traitsBitInst.coredefaultDefaultInst
  to_u8 := typenum.uint.UInt.Insts.TypenumMarker_traitsUnsigned.to_u8
    marker_traitsUnsignedInst marker_traitsBitInst
  to_u16 := typenum.uint.UInt.Insts.TypenumMarker_traitsUnsigned.to_u16
    marker_traitsUnsignedInst marker_traitsBitInst
  to_u32 := typenum.uint.UInt.Insts.TypenumMarker_traitsUnsigned.to_u32
    marker_traitsUnsignedInst marker_traitsBitInst
  to_u64 := typenum.uint.UInt.Insts.TypenumMarker_traitsUnsigned.to_u64
    marker_traitsUnsignedInst marker_traitsBitInst
  to_usize := typenum.uint.UInt.Insts.TypenumMarker_traitsUnsigned.to_usize
    marker_traitsUnsignedInst marker_traitsBitInst
  to_i8 := typenum.uint.UInt.Insts.TypenumMarker_traitsUnsigned.to_i8
    marker_traitsUnsignedInst marker_traitsBitInst
  to_i16 := typenum.uint.UInt.Insts.TypenumMarker_traitsUnsigned.to_i16
    marker_traitsUnsignedInst marker_traitsBitInst
  to_i32 := typenum.uint.UInt.Insts.TypenumMarker_traitsUnsigned.to_i32
    marker_traitsUnsignedInst marker_traitsBitInst
  to_i64 := typenum.uint.UInt.Insts.TypenumMarker_traitsUnsigned.to_i64
    marker_traitsUnsignedInst marker_traitsBitInst
  to_isize := typenum.uint.UInt.Insts.TypenumMarker_traitsUnsigned.to_isize
    marker_traitsUnsignedInst marker_traitsBitInst
}

/-- [signal_crypto::aes_cbc::_::{signal_crypto::aes_cbc::_::DisplayToDisplayDoc for &0 (T)}::__displaydoc_display]:
    Source: 'rust/crypto/src/aes_cbc.rs', lines 12:16-12:35 -/
def
  Shared0T.Insts.Signal_cryptoAes_cbc_DisplayToDisplayDoc.__displaydoc_display
  {T : Type} (corefmtDisplayInst : core.fmt.Display T) (self : T) :
  Result T
  := do
  ok self

/-- Trait implementation: [signal_crypto::aes_cbc::_::{signal_crypto::aes_cbc::_::DisplayToDisplayDoc for &0 (T)}]
    Source: 'rust/crypto/src/aes_cbc.rs', lines 12:16-12:35 -/
@[reducible]
def Shared0T.Insts.Signal_cryptoAes_cbc_DisplayToDisplayDoc {T : Type}
  (corefmtDisplayInst : core.fmt.Display T) : aes_cbc._.DisplayToDisplayDoc T
  := {
  __displaydoc_display :=
    Shared0T.Insts.Signal_cryptoAes_cbc_DisplayToDisplayDoc.__displaydoc_display
    corefmtDisplayInst
}

/-- [signal_crypto::aes_cbc::_::{signal_crypto::aes_cbc::_::PathToDisplayDoc for std::path::Path}::__displaydoc_display]:
    Source: 'rust/crypto/src/aes_cbc.rs', lines 12:16-12:35 -/
def
  std.path.Path.Insts.Signal_cryptoAes_cbc_PathToDisplayDoc.__displaydoc_display
  (self : std.path.Path) : Result std.path.Display := do
  std.path.Path.display self

/-- Trait implementation: [signal_crypto::aes_cbc::_::{signal_crypto::aes_cbc::_::PathToDisplayDoc for std::path::Path}]
    Source: 'rust/crypto/src/aes_cbc.rs', lines 12:16-12:35 -/
@[reducible]
def std.path.Path.Insts.Signal_cryptoAes_cbc_PathToDisplayDoc :
  aes_cbc._.PathToDisplayDoc std.path.Path := {
  __displaydoc_display :=
    std.path.Path.Insts.Signal_cryptoAes_cbc_PathToDisplayDoc.__displaydoc_display
}

/-- [signal_crypto::aes_cbc::_::{signal_crypto::aes_cbc::_::PathToDisplayDoc for std::path::PathBuf}::__displaydoc_display]:
    Source: 'rust/crypto/src/aes_cbc.rs', lines 12:16-12:35 -/
def
  std.path.PathBuf.Insts.Signal_cryptoAes_cbc_PathToDisplayDoc.__displaydoc_display
  (self : std.path.PathBuf) : Result std.path.Display := do
  let p ← std.path.PathBuf.Insts.CoreOpsDerefDerefPath.deref self
  std.path.Path.display p

/-- Trait implementation: [signal_crypto::aes_cbc::_::{signal_crypto::aes_cbc::_::PathToDisplayDoc for std::path::PathBuf}]
    Source: 'rust/crypto/src/aes_cbc.rs', lines 12:16-12:35 -/
@[reducible]
def std.path.PathBuf.Insts.Signal_cryptoAes_cbc_PathToDisplayDoc :
  aes_cbc._.PathToDisplayDoc std.path.PathBuf := {
  __displaydoc_display :=
    std.path.PathBuf.Insts.Signal_cryptoAes_cbc_PathToDisplayDoc.__displaydoc_display
}

/-- [signal_crypto::aes_cbc::_]
    Source: 'rust/crypto/src/aes_cbc.rs', lines 12:16-12:35 -/
@[global_simps, irreducible] def aes_cbc._ : Unit := ()

/-- [signal_crypto::aes_cbc::_#1::{signal_crypto::aes_cbc::_#1::DisplayToDisplayDoc for &0 (T)}::__displaydoc_display]:
    Source: 'rust/crypto/src/aes_cbc.rs', lines 18:16-18:35 -/
def
  Shared0T.Insts.Signal_cryptoAes_cbc__1DisplayToDisplayDoc.__displaydoc_display
  {T : Type} (corefmtDisplayInst : core.fmt.Display T) (self : T) :
  Result T
  := do
  ok self

/-- Trait implementation: [signal_crypto::aes_cbc::_#1::{signal_crypto::aes_cbc::_#1::DisplayToDisplayDoc for &0 (T)}]
    Source: 'rust/crypto/src/aes_cbc.rs', lines 18:16-18:35 -/
@[reducible]
def Shared0T.Insts.Signal_cryptoAes_cbc__1DisplayToDisplayDoc {T : Type}
  (corefmtDisplayInst : core.fmt.Display T) : aes_cbc.__1.DisplayToDisplayDoc T
  := {
  __displaydoc_display :=
    Shared0T.Insts.Signal_cryptoAes_cbc__1DisplayToDisplayDoc.__displaydoc_display
    corefmtDisplayInst
}

/-- [signal_crypto::aes_cbc::_#1::{signal_crypto::aes_cbc::_#1::PathToDisplayDoc for std::path::Path}::__displaydoc_display]:
    Source: 'rust/crypto/src/aes_cbc.rs', lines 18:16-18:35 -/
def
  std.path.Path.Insts.Signal_cryptoAes_cbc__1PathToDisplayDoc.__displaydoc_display
  (self : std.path.Path) : Result std.path.Display := do
  std.path.Path.display self

/-- Trait implementation: [signal_crypto::aes_cbc::_#1::{signal_crypto::aes_cbc::_#1::PathToDisplayDoc for std::path::Path}]
    Source: 'rust/crypto/src/aes_cbc.rs', lines 18:16-18:35 -/
@[reducible]
def std.path.Path.Insts.Signal_cryptoAes_cbc__1PathToDisplayDoc :
  aes_cbc.__1.PathToDisplayDoc std.path.Path := {
  __displaydoc_display :=
    std.path.Path.Insts.Signal_cryptoAes_cbc__1PathToDisplayDoc.__displaydoc_display
}

/-- [signal_crypto::aes_cbc::_#1::{signal_crypto::aes_cbc::_#1::PathToDisplayDoc for std::path::PathBuf}::__displaydoc_display]:
    Source: 'rust/crypto/src/aes_cbc.rs', lines 18:16-18:35 -/
def
  std.path.PathBuf.Insts.Signal_cryptoAes_cbc__1PathToDisplayDoc.__displaydoc_display
  (self : std.path.PathBuf) : Result std.path.Display := do
  let p ← std.path.PathBuf.Insts.CoreOpsDerefDerefPath.deref self
  std.path.Path.display p

/-- Trait implementation: [signal_crypto::aes_cbc::_#1::{signal_crypto::aes_cbc::_#1::PathToDisplayDoc for std::path::PathBuf}]
    Source: 'rust/crypto/src/aes_cbc.rs', lines 18:16-18:35 -/
@[reducible]
def std.path.PathBuf.Insts.Signal_cryptoAes_cbc__1PathToDisplayDoc :
  aes_cbc.__1.PathToDisplayDoc std.path.PathBuf := {
  __displaydoc_display :=
    std.path.PathBuf.Insts.Signal_cryptoAes_cbc__1PathToDisplayDoc.__displaydoc_display
}

/-- [signal_crypto::aes_cbc::_#1]
    Source: 'rust/crypto/src/aes_cbc.rs', lines 18:16-18:35 -/
@[global_simps, irreducible] def aes_cbc.__1 : Unit := ()

/-- [signal_crypto::aes_ctr::{signal_crypto::aes_ctr::Aes256Ctr32}::NONCE_SIZE]
    Source: 'rust/crypto/src/aes_ctr.rs', lines 17:4-17:95
    Visibility: public -/
@[global_simps, irreducible]
def aes_ctr.Aes256Ctr32.NONCE_SIZE : Result Std.Usize := do
  let i ←
    typenum.uint.UInt.Insts.TypenumMarker_traitsUnsigned.USIZE
      (typenum.uint.UInt.Insts.TypenumMarker_traitsUnsigned
      (typenum.uint.UInt.Insts.TypenumMarker_traitsUnsigned
      (typenum.uint.UInt.Insts.TypenumMarker_traitsUnsigned
      (typenum.uint.UInt.Insts.TypenumMarker_traitsUnsigned
      typenum.uint.UTerm.Insts.TypenumMarker_traitsUnsigned
      typenum.bit.B1.Insts.TypenumMarker_traitsBit)
      typenum.bit.B0.Insts.TypenumMarker_traitsBit)
      typenum.bit.B0.Insts.TypenumMarker_traitsBit)
      typenum.bit.B0.Insts.TypenumMarker_traitsBit)
      typenum.bit.B0.Insts.TypenumMarker_traitsBit
  i - 4#usize

/-- [signal_crypto::aes_gcm::TAG_SIZE]
    Source: 'rust/crypto/src/aes_gcm.rs', lines 15:0-15:31
    Visibility: public -/
@[global_simps, irreducible] def aes_gcm.TAG_SIZE : Std.Usize := 16#usize

/-- [signal_crypto::aes_gcm::NONCE_SIZE]
    Source: 'rust/crypto/src/aes_gcm.rs', lines 16:0-16:33
    Visibility: public -/
@[global_simps, irreducible] def aes_gcm.NONCE_SIZE : Std.Usize := 12#usize

/-- [signal_crypto::aes_gcm::{signal_crypto::aes_gcm::Aes256GcmEncryption}::TAG_SIZE]
    Source: 'rust/crypto/src/aes_gcm.rs', lines 144:4-144:41
    Visibility: public -/
@[global_simps, irreducible]
def aes_gcm.Aes256GcmEncryption.TAG_SIZE : Std.Usize := aes_gcm.TAG_SIZE

/-- [signal_crypto::aes_gcm::{signal_crypto::aes_gcm::Aes256GcmEncryption}::NONCE_SIZE]
    Source: 'rust/crypto/src/aes_gcm.rs', lines 145:4-145:45
    Visibility: public -/
@[global_simps, irreducible]
def aes_gcm.Aes256GcmEncryption.NONCE_SIZE : Std.Usize := aes_gcm.NONCE_SIZE

/-- [signal_crypto::aes_gcm::{signal_crypto::aes_gcm::Aes256GcmEncryption}::new]:
    Source: 'rust/crypto/src/aes_gcm.rs', lines 147:4-150:5
    Visibility: public -/
def aes_gcm.Aes256GcmEncryption.new
  (key : Slice Std.U8) (nonce : Slice Std.U8) (associated_data : Slice Std.U8)
  :
  Result (core.result.Result aes_gcm.Aes256GcmEncryption error.Error)
  := do
  let r ← aes_gcm.setup_gcm key nonce associated_data
  let cf ←
    core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let (ctr, ghash) := val
    ok (core.result.Result.Ok { ctr, ghash })
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
      aes_gcm.Aes256GcmEncryption (core.convert.FromSame error.Error) residual

/-- [signal_crypto::aes_gcm::{signal_crypto::aes_gcm::Aes256GcmEncryption}::encrypt]:
    Source: 'rust/crypto/src/aes_gcm.rs', lines 152:4-155:5
    Visibility: public -/
def aes_gcm.Aes256GcmEncryption.encrypt
  (self : aes_gcm.Aes256GcmEncryption) (buf : Slice Std.U8) :
  Result (aes_gcm.Aes256GcmEncryption × (Slice Std.U8))
  := do
  let (ac, buf1) ← aes_ctr.Aes256Ctr32.process self.ctr buf
  let gg ← aes_gcm.GcmGhash.update self.ghash buf1
  ok ({ ctr := ac, ghash := gg }, buf1)

/-- [signal_crypto::aes_gcm::{signal_crypto::aes_gcm::Aes256GcmEncryption}::compute_tag]:
    Source: 'rust/crypto/src/aes_gcm.rs', lines 157:4-159:5
    Visibility: public -/
def aes_gcm.Aes256GcmEncryption.compute_tag
  (self : aes_gcm.Aes256GcmEncryption) : Result (Array Std.U8 16#usize) := do
  aes_gcm.GcmGhash.finalize self.ghash

/-- [signal_crypto::aes_gcm::{signal_crypto::aes_gcm::Aes256GcmDecryption}::TAG_SIZE]
    Source: 'rust/crypto/src/aes_gcm.rs', lines 168:4-168:41
    Visibility: public -/
@[global_simps, irreducible]
def aes_gcm.Aes256GcmDecryption.TAG_SIZE : Std.Usize := aes_gcm.TAG_SIZE

/-- [signal_crypto::aes_gcm::{signal_crypto::aes_gcm::Aes256GcmDecryption}::NONCE_SIZE]
    Source: 'rust/crypto/src/aes_gcm.rs', lines 169:4-169:45
    Visibility: public -/
@[global_simps, irreducible]
def aes_gcm.Aes256GcmDecryption.NONCE_SIZE : Std.Usize := aes_gcm.NONCE_SIZE

/-- [signal_crypto::aes_gcm::{signal_crypto::aes_gcm::Aes256GcmDecryption}::new]:
    Source: 'rust/crypto/src/aes_gcm.rs', lines 171:4-174:5
    Visibility: public -/
def aes_gcm.Aes256GcmDecryption.new
  (key : Slice Std.U8) (nonce : Slice Std.U8) (associated_data : Slice Std.U8)
  :
  Result (core.result.Result aes_gcm.Aes256GcmDecryption error.Error)
  := do
  let r ← aes_gcm.setup_gcm key nonce associated_data
  let cf ←
    core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let (ctr, ghash) := val
    ok (core.result.Result.Ok { ctr, ghash })
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
      aes_gcm.Aes256GcmDecryption (core.convert.FromSame error.Error) residual

/-- [signal_crypto::aes_gcm::{signal_crypto::aes_gcm::Aes256GcmDecryption}::decrypt]:
    Source: 'rust/crypto/src/aes_gcm.rs', lines 176:4-179:5
    Visibility: public -/
def aes_gcm.Aes256GcmDecryption.decrypt
  (self : aes_gcm.Aes256GcmDecryption) (buf : Slice Std.U8) :
  Result (aes_gcm.Aes256GcmDecryption × (Slice Std.U8))
  := do
  let gg ← aes_gcm.GcmGhash.update self.ghash buf
  let (ac, buf1) ← aes_ctr.Aes256Ctr32.process self.ctr buf
  ok ({ ctr := ac, ghash := gg }, buf1)

/-- [signal_crypto::aes_gcm::{signal_crypto::aes_gcm::Aes256GcmDecryption}::verify_tag]:
    Source: 'rust/crypto/src/aes_gcm.rs', lines 181:4-195:5
    Visibility: public -/
def aes_gcm.Aes256GcmDecryption.verify_tag
  (self : aes_gcm.Aes256GcmDecryption) (tag : Slice Std.U8) :
  Result (core.result.Result Unit error.Error)
  := do
  let i := Slice.len tag
  if i != aes_gcm.TAG_SIZE
  then ok (core.result.Result.Err error.Error.InvalidTag)
  else
    let computed_tag ← aes_gcm.GcmGhash.finalize self.ghash
    let s ← lift (Array.to_slice computed_tag)
    let tag_ok ←
      Slice.Insts.SubtleConstantTimeEq.ct_eq U8.Insts.SubtleConstantTimeEq tag
        s
    let b ← Bool.Insts.CoreConvertFromChoice.from tag_ok
    if b
    then ok (core.result.Result.Ok ())
    else ok (core.result.Result.Err error.Error.InvalidTag)

/-- [signal_crypto::error::_::{signal_crypto::error::_::DisplayToDisplayDoc for &0 (T)}::__displaydoc_display]:
    Source: 'rust/crypto/src/error.rs', lines 6:9-6:28 -/
def Shared0T.Insts.Signal_cryptoError_DisplayToDisplayDoc.__displaydoc_display
  {T : Type} (corefmtDisplayInst : core.fmt.Display T) (self : T) :
  Result T
  := do
  ok self

/-- Trait implementation: [signal_crypto::error::_::{signal_crypto::error::_::DisplayToDisplayDoc for &0 (T)}]
    Source: 'rust/crypto/src/error.rs', lines 6:9-6:28 -/
@[reducible]
def Shared0T.Insts.Signal_cryptoError_DisplayToDisplayDoc {T : Type}
  (corefmtDisplayInst : core.fmt.Display T) : error._.DisplayToDisplayDoc T
  := {
  __displaydoc_display :=
    Shared0T.Insts.Signal_cryptoError_DisplayToDisplayDoc.__displaydoc_display
    corefmtDisplayInst
}

/-- [signal_crypto::error::_::{signal_crypto::error::_::PathToDisplayDoc for std::path::Path}::__displaydoc_display]:
    Source: 'rust/crypto/src/error.rs', lines 6:9-6:28 -/
def
  std.path.Path.Insts.Signal_cryptoError_PathToDisplayDoc.__displaydoc_display
  (self : std.path.Path) : Result std.path.Display := do
  std.path.Path.display self

/-- Trait implementation: [signal_crypto::error::_::{signal_crypto::error::_::PathToDisplayDoc for std::path::Path}]
    Source: 'rust/crypto/src/error.rs', lines 6:9-6:28 -/
@[reducible]
def std.path.Path.Insts.Signal_cryptoError_PathToDisplayDoc :
  error._.PathToDisplayDoc std.path.Path := {
  __displaydoc_display :=
    std.path.Path.Insts.Signal_cryptoError_PathToDisplayDoc.__displaydoc_display
}

/-- [signal_crypto::error::_::{signal_crypto::error::_::PathToDisplayDoc for std::path::PathBuf}::__displaydoc_display]:
    Source: 'rust/crypto/src/error.rs', lines 6:9-6:28 -/
def
  std.path.PathBuf.Insts.Signal_cryptoError_PathToDisplayDoc.__displaydoc_display
  (self : std.path.PathBuf) : Result std.path.Display := do
  let p ← std.path.PathBuf.Insts.CoreOpsDerefDerefPath.deref self
  std.path.Path.display p

/-- Trait implementation: [signal_crypto::error::_::{signal_crypto::error::_::PathToDisplayDoc for std::path::PathBuf}]
    Source: 'rust/crypto/src/error.rs', lines 6:9-6:28 -/
@[reducible]
def std.path.PathBuf.Insts.Signal_cryptoError_PathToDisplayDoc :
  error._.PathToDisplayDoc std.path.PathBuf := {
  __displaydoc_display :=
    std.path.PathBuf.Insts.Signal_cryptoError_PathToDisplayDoc.__displaydoc_display
}

/-- [signal_crypto::error::_]
    Source: 'rust/crypto/src/error.rs', lines 6:9-6:28 -/
@[global_simps, irreducible] def error._ : Unit := ()

/-- [signal_crypto::hash::{signal_crypto::hash::CryptographicMac}::update_and_get]:
    Source: 'rust/crypto/src/hash.rs', lines 41:4-44:5
    Visibility: public -/
def hash.CryptographicMac.update_and_get
  (self : hash.CryptographicMac) (input : Slice Std.U8) :
  Result (hash.CryptographicMac × (hash.CryptographicMac →
    hash.CryptographicMac))
  := do
  let self1 ← hash.CryptographicMac.update self input
  ok (self1, fun self2 => self2)

end signal_crypto
