include = ["Cargo.toml", "rust/**/*.toml"]

[formatting]
align_comments = false
indent_string = '    '
reorder_keys = false

[[rule]]
include = ["**/Cargo.toml"]
keys = ["dependencies", "workspace.dependencies", "dev-dependencies", "build-dependencies"]

[rule.formatting]
inline_table_expand = false
reorder_keys = true
