//
// Copyright 2026 Signal Messenger, LLC.
// SPDX-License-Identifier: AGPL-3.0-only
//

import Foundation

public enum AuthCheckResult {
    /// The credentials could be used to make a call to SVR service by the user
    /// associated with the phone number.
    case match
    /// The credentials were generated by a different user.
    case noMatch
    /// This status indicates that the corresponding credentials token should no longer be used.
    /// This may be because it has expired or invalid, but it can also mean that there is a more
    /// recent token in the request which should be used instead.
    case invalid
}

public protocol UnauthCredentialsService: Sendable {
    /// Given a list of secure value recovery (SVR) service credentials and a phone
    /// number, checks and returns which of the provided credentials were generated
    /// by the user with the given phone number and have not yet expired.
    ///
    /// - Parameters:
    ///   - number: A phone number in the E164 format to check the passwords against. Only
    ///     passwords generated for the user associated with the given number will be marked as
    ///     AuthCheckResult::Match.
    ///   - credentials: A list of credentials (`username:password`) from previously made calls to
    ///     ExternalServiceCredentials.GetExternalServiceCredentials() for
    ///     EXTERNAL_SERVICE_TYPE_SVR. This list may contain credentials generated by different
    ///     users. Up to 10 credentials can be checked.
    ///
    /// - Returns: A map from the inputted credential to its corresponding result
    ///
    /// - Throws:
    ///   - the standard Signal network errors
    func checkSvrCredentials(
        number: String,
        credentials: [String],
    ) async throws -> [String: AuthCheckResult]
}

extension UnauthenticatedChatConnection: UnauthCredentialsService {

    public func checkSvrCredentials(number: String, credentials: [String]) async throws -> [String: AuthCheckResult] {
        return Dictionary(
            uniqueKeysWithValues: try await NativeNice.UnauthenticatedChatConnection_check_svr_credentials(
                asyncContext: self.tokioAsyncContext,
                chat: self,
                number: number,
                credentials: credentials,
            )
        )
    }

}

extension UnauthServiceSelector where Self == UnauthServiceSelectorHelper<any UnauthCredentialsService> {
    public static var credentials: Self { .init() }
}
