// Copyright (C) 2026 Signal Messenger, LLC.
// SPDX-License-Identifier: AGPL-3.0-only
// AUTOGENERATED! Do not modify!
#pragma once
#include "signal_ffi.h"
typedef const SignalType_ConstPointer_void* SignalType_ConstPointer_SignalType_ConstPointer_void;
static_assert_64bit(sizeof(SignalType_ConstPointer_SignalType_ConstPointer_void) == 8);
static_assert_64bit(alignof(SignalType_ConstPointer_SignalType_ConstPointer_void) == 8);
typedef const SignalCStringPtr* SignalType_ConstPointer_SignalCStringPtr;
static_assert_64bit(sizeof(SignalType_ConstPointer_SignalCStringPtr) == 8);
static_assert_64bit(alignof(SignalType_ConstPointer_SignalCStringPtr) == 8);
typedef const int32_t* SignalType_ConstPointer_int32_t;
static_assert_64bit(sizeof(SignalType_ConstPointer_int32_t) == 8);
static_assert_64bit(alignof(SignalType_ConstPointer_int32_t) == 8);
typedef struct SignalTestStream SignalTestStream;
typedef const SignalTestStream* SignalType_ConstPointer_SignalTestStream;
static_assert_64bit(sizeof(SignalType_ConstPointer_SignalTestStream) == 8);
static_assert_64bit(alignof(SignalType_ConstPointer_SignalTestStream) == 8);
typedef struct {
  SignalCStringPtr* base;
  size_t length;
  size_t size_bytes;
} SignalOwnedBufferOfMaxAlignedCStringPtr;
static_assert_64bit(offsetof(SignalOwnedBufferOfMaxAlignedCStringPtr, base) == 0);
static_assert_64bit(offsetof(SignalOwnedBufferOfMaxAlignedCStringPtr, length) == 8);
static_assert_64bit(offsetof(SignalOwnedBufferOfMaxAlignedCStringPtr, size_bytes) == 16);
static_assert_64bit(sizeof(SignalOwnedBufferOfMaxAlignedCStringPtr) == 24);
static_assert_64bit(alignof(SignalOwnedBufferOfMaxAlignedCStringPtr) == 8);
typedef struct {
  SignalOwnedBufferOfMaxAlignedCStringPtr chunk;
  SignalFfiBulkPolledStreamTerminationReason termination;
} SignalTestStreamChunkFfiResult;
static_assert_64bit(offsetof(SignalTestStreamChunkFfiResult, chunk) == 0);
static_assert_64bit(offsetof(SignalTestStreamChunkFfiResult, termination) == 24);
static_assert_64bit(sizeof(SignalTestStreamChunkFfiResult) == 32);
static_assert_64bit(alignof(SignalTestStreamChunkFfiResult) == 8);
typedef const SignalTestStreamChunkFfiResult* SignalType_ConstPointer_SignalTestStreamChunkFfiResult;
static_assert_64bit(sizeof(SignalType_ConstPointer_SignalTestStreamChunkFfiResult) == 8);
static_assert_64bit(alignof(SignalType_ConstPointer_SignalTestStreamChunkFfiResult) == 8);
typedef struct SignalNonSuspendingBackgroundThreadRuntime SignalNonSuspendingBackgroundThreadRuntime;
typedef const SignalNonSuspendingBackgroundThreadRuntime* SignalType_ConstPointer_SignalNonSuspendingBackgroundThreadRuntime;
static_assert_64bit(sizeof(SignalType_ConstPointer_SignalNonSuspendingBackgroundThreadRuntime) == 8);
static_assert_64bit(alignof(SignalType_ConstPointer_SignalNonSuspendingBackgroundThreadRuntime) == 8);
typedef struct SignalOtherTestingHandleType SignalOtherTestingHandleType;
typedef const SignalOtherTestingHandleType* SignalType_ConstPointer_SignalOtherTestingHandleType;
static_assert_64bit(sizeof(SignalType_ConstPointer_SignalOtherTestingHandleType) == 8);
static_assert_64bit(alignof(SignalType_ConstPointer_SignalOtherTestingHandleType) == 8);
typedef struct SignalTestingHandleType SignalTestingHandleType;
typedef const SignalTestingHandleType* SignalType_ConstPointer_SignalTestingHandleType;
static_assert_64bit(sizeof(SignalType_ConstPointer_SignalTestingHandleType) == 8);
static_assert_64bit(alignof(SignalType_ConstPointer_SignalTestingHandleType) == 8);
typedef struct SignalComparableBackup SignalComparableBackup;
typedef const SignalComparableBackup* SignalType_ConstPointer_SignalComparableBackup;
static_assert_64bit(sizeof(SignalType_ConstPointer_SignalComparableBackup) == 8);
static_assert_64bit(alignof(SignalType_ConstPointer_SignalComparableBackup) == 8);
typedef struct SignalFakeChatConnection SignalFakeChatConnection;
typedef const SignalFakeChatConnection* SignalType_ConstPointer_SignalFakeChatConnection;
static_assert_64bit(sizeof(SignalType_ConstPointer_SignalFakeChatConnection) == 8);
static_assert_64bit(alignof(SignalType_ConstPointer_SignalFakeChatConnection) == 8);
typedef struct SignalFakeChatRemoteEnd SignalFakeChatRemoteEnd;
typedef const SignalFakeChatRemoteEnd* SignalType_ConstPointer_SignalFakeChatRemoteEnd;
static_assert_64bit(sizeof(SignalType_ConstPointer_SignalFakeChatRemoteEnd) == 8);
static_assert_64bit(alignof(SignalType_ConstPointer_SignalFakeChatRemoteEnd) == 8);
typedef struct SignalFakeChatResponse SignalFakeChatResponse;
typedef const SignalFakeChatResponse* SignalType_ConstPointer_SignalFakeChatResponse;
static_assert_64bit(sizeof(SignalType_ConstPointer_SignalFakeChatResponse) == 8);
static_assert_64bit(alignof(SignalType_ConstPointer_SignalFakeChatResponse) == 8);
typedef struct SignalFakeChatServer SignalFakeChatServer;
typedef const SignalFakeChatServer* SignalType_ConstPointer_SignalFakeChatServer;
static_assert_64bit(sizeof(SignalType_ConstPointer_SignalFakeChatServer) == 8);
static_assert_64bit(alignof(SignalType_ConstPointer_SignalFakeChatServer) == 8);
typedef struct SignalGrpcTestCaseBridgedResponse SignalGrpcTestCaseBridgedResponse;
typedef const SignalGrpcTestCaseBridgedResponse* SignalType_ConstPointer_SignalGrpcTestCaseBridgedResponse;
static_assert_64bit(sizeof(SignalType_ConstPointer_SignalGrpcTestCaseBridgedResponse) == 8);
static_assert_64bit(alignof(SignalType_ConstPointer_SignalGrpcTestCaseBridgedResponse) == 8);
typedef enum {
  SignalMySimpleTestEnumFfiArgA,
  SignalMySimpleTestEnumFfiArgB,
} SignalMySimpleTestEnumFfiArg;
static_assert_64bit(sizeof(SignalMySimpleTestEnumFfiArg) == 4);
static_assert_64bit(alignof(SignalMySimpleTestEnumFfiArg) == 4);
typedef const SignalMySimpleTestEnumFfiArg* SignalType_ConstPointer_SignalMySimpleTestEnumFfiArg;
static_assert_64bit(sizeof(SignalType_ConstPointer_SignalMySimpleTestEnumFfiArg) == 8);
static_assert_64bit(alignof(SignalType_ConstPointer_SignalMySimpleTestEnumFfiArg) == 8);
typedef struct SignalTestingFutureCancellationCounter SignalTestingFutureCancellationCounter;
typedef const SignalTestingFutureCancellationCounter* SignalType_ConstPointer_SignalTestingFutureCancellationCounter;
static_assert_64bit(sizeof(SignalType_ConstPointer_SignalTestingFutureCancellationCounter) == 8);
static_assert_64bit(alignof(SignalType_ConstPointer_SignalTestingFutureCancellationCounter) == 8);
typedef struct SignalTestingIntBox SignalTestingIntBox;
typedef const SignalTestingIntBox* SignalType_ConstPointer_SignalTestingIntBox;
static_assert_64bit(sizeof(SignalType_ConstPointer_SignalTestingIntBox) == 8);
static_assert_64bit(alignof(SignalType_ConstPointer_SignalTestingIntBox) == 8);
typedef struct SignalTestingSemaphore SignalTestingSemaphore;
typedef const SignalTestingSemaphore* SignalType_ConstPointer_SignalTestingSemaphore;
static_assert_64bit(sizeof(SignalType_ConstPointer_SignalTestingSemaphore) == 8);
static_assert_64bit(alignof(SignalType_ConstPointer_SignalTestingSemaphore) == 8);
typedef struct SignalTestingValueHolder SignalTestingValueHolder;
typedef const SignalTestingValueHolder* SignalType_ConstPointer_SignalTestingValueHolder;
static_assert_64bit(sizeof(SignalType_ConstPointer_SignalTestingValueHolder) == 8);
static_assert_64bit(alignof(SignalType_ConstPointer_SignalTestingValueHolder) == 8);
typedef SignalOtherTestingHandleType* SignalType_MutPointer_SignalOtherTestingHandleType;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalOtherTestingHandleType) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalOtherTestingHandleType) == 8);
typedef struct {
  SignalOtherTestingHandleType* raw;
} SignalMutPointerOtherTestingHandleType;
static_assert_64bit(offsetof(SignalMutPointerOtherTestingHandleType, raw) == 0);
static_assert_64bit(sizeof(SignalMutPointerOtherTestingHandleType) == 8);
static_assert_64bit(alignof(SignalMutPointerOtherTestingHandleType) == 8);
typedef const SignalMutPointerOtherTestingHandleType* SignalType_ConstPointer_SignalMutPointerOtherTestingHandleType;
static_assert_64bit(sizeof(SignalType_ConstPointer_SignalMutPointerOtherTestingHandleType) == 8);
static_assert_64bit(alignof(SignalType_ConstPointer_SignalMutPointerOtherTestingHandleType) == 8);
typedef SignalTestingHandleType* SignalType_MutPointer_SignalTestingHandleType;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalTestingHandleType) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalTestingHandleType) == 8);
typedef struct {
  SignalTestingHandleType* raw;
} SignalMutPointerTestingHandleType;
static_assert_64bit(offsetof(SignalMutPointerTestingHandleType, raw) == 0);
static_assert_64bit(sizeof(SignalMutPointerTestingHandleType) == 8);
static_assert_64bit(alignof(SignalMutPointerTestingHandleType) == 8);
typedef const SignalMutPointerTestingHandleType* SignalType_ConstPointer_SignalMutPointerTestingHandleType;
static_assert_64bit(sizeof(SignalType_ConstPointer_SignalMutPointerTestingHandleType) == 8);
static_assert_64bit(alignof(SignalType_ConstPointer_SignalMutPointerTestingHandleType) == 8);
typedef SignalFakeChatRemoteEnd* SignalType_MutPointer_SignalFakeChatRemoteEnd;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalFakeChatRemoteEnd) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalFakeChatRemoteEnd) == 8);
typedef struct {
  SignalFakeChatRemoteEnd* raw;
} SignalMutPointerFakeChatRemoteEnd;
static_assert_64bit(offsetof(SignalMutPointerFakeChatRemoteEnd, raw) == 0);
static_assert_64bit(sizeof(SignalMutPointerFakeChatRemoteEnd) == 8);
static_assert_64bit(alignof(SignalMutPointerFakeChatRemoteEnd) == 8);
typedef const SignalMutPointerFakeChatRemoteEnd* SignalType_ConstPointer_SignalMutPointerFakeChatRemoteEnd;
static_assert_64bit(sizeof(SignalType_ConstPointer_SignalMutPointerFakeChatRemoteEnd) == 8);
static_assert_64bit(alignof(SignalType_ConstPointer_SignalMutPointerFakeChatRemoteEnd) == 8);
typedef struct {
  bool present;
  SignalMutPointerHttpRequest first;
  uint64_t second;
} SignalOptionalPairOfMutPointerHttpRequestu64;
static_assert_64bit(offsetof(SignalOptionalPairOfMutPointerHttpRequestu64, present) == 0);
static_assert_64bit(offsetof(SignalOptionalPairOfMutPointerHttpRequestu64, first) == 8);
static_assert_64bit(offsetof(SignalOptionalPairOfMutPointerHttpRequestu64, second) == 16);
static_assert_64bit(sizeof(SignalOptionalPairOfMutPointerHttpRequestu64) == 24);
static_assert_64bit(alignof(SignalOptionalPairOfMutPointerHttpRequestu64) == 8);
typedef const SignalOptionalPairOfMutPointerHttpRequestu64* SignalType_ConstPointer_SignalOptionalPairOfMutPointerHttpRequestu64;
static_assert_64bit(sizeof(SignalType_ConstPointer_SignalOptionalPairOfMutPointerHttpRequestu64) == 8);
static_assert_64bit(alignof(SignalType_ConstPointer_SignalOptionalPairOfMutPointerHttpRequestu64) == 8);
typedef SignalType_ConstPointer_void* SignalType_MutPointer_SignalType_ConstPointer_void;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalType_ConstPointer_void) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalType_ConstPointer_void) == 8);
typedef SignalType_MutPointer_SignalFfiError* SignalType_MutPointer_SignalType_MutPointer_SignalFfiError;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalType_MutPointer_SignalFfiError) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalType_MutPointer_SignalFfiError) == 8);
typedef SignalTestStream* SignalType_MutPointer_SignalTestStream;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalTestStream) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalTestStream) == 8);
typedef SignalTestStreamChunkFfiResult* SignalType_MutPointer_SignalTestStreamChunkFfiResult;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalTestStreamChunkFfiResult) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalTestStreamChunkFfiResult) == 8);
typedef SignalNonSuspendingBackgroundThreadRuntime* SignalType_MutPointer_SignalNonSuspendingBackgroundThreadRuntime;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalNonSuspendingBackgroundThreadRuntime) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalNonSuspendingBackgroundThreadRuntime) == 8);
typedef SignalComparableBackup* SignalType_MutPointer_SignalComparableBackup;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalComparableBackup) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalComparableBackup) == 8);
typedef SignalFakeChatConnection* SignalType_MutPointer_SignalFakeChatConnection;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalFakeChatConnection) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalFakeChatConnection) == 8);
typedef SignalFakeChatResponse* SignalType_MutPointer_SignalFakeChatResponse;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalFakeChatResponse) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalFakeChatResponse) == 8);
typedef SignalFakeChatServer* SignalType_MutPointer_SignalFakeChatServer;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalFakeChatServer) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalFakeChatServer) == 8);
typedef SignalGrpcTestCaseBridgedResponse* SignalType_MutPointer_SignalGrpcTestCaseBridgedResponse;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalGrpcTestCaseBridgedResponse) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalGrpcTestCaseBridgedResponse) == 8);
typedef void (*SignalType_UnsafeFunctionPointer_void_SignalType_MutPointer_void)(SignalType_MutPointer_void);
static_assert_64bit(sizeof(SignalType_UnsafeFunctionPointer_void_SignalType_MutPointer_void) == 8);
static_assert_64bit(alignof(SignalType_UnsafeFunctionPointer_void_SignalType_MutPointer_void) == 8);
typedef struct {
  SignalType_UnsafeFunctionPointer_void_SignalType_MutPointer_void destroy;
  void* contents;
} SignalFfiErasedForTesting;
static_assert_64bit(offsetof(SignalFfiErasedForTesting, destroy) == 0);
static_assert_64bit(offsetof(SignalFfiErasedForTesting, contents) == 8);
static_assert_64bit(sizeof(SignalFfiErasedForTesting) == 16);
static_assert_64bit(alignof(SignalFfiErasedForTesting) == 8);
typedef struct {
  SignalGrpcTestCaseBridgedResponse* raw;
} SignalMutPointerGrpcTestCaseBridgedResponse;
static_assert_64bit(offsetof(SignalMutPointerGrpcTestCaseBridgedResponse, raw) == 0);
static_assert_64bit(sizeof(SignalMutPointerGrpcTestCaseBridgedResponse) == 8);
static_assert_64bit(alignof(SignalMutPointerGrpcTestCaseBridgedResponse) == 8);
typedef struct {
  const int8_t* name;
  const int8_t* method;
  SignalFfiErasedForTesting request;
  SignalOwnedBuffer request_grpc;
  SignalMutPointerGrpcTestCaseBridgedResponse response_grpc;
  SignalFfiErasedForTesting response;
} SignalGrpcTestCaseBridgedFfi;
static_assert_64bit(offsetof(SignalGrpcTestCaseBridgedFfi, name) == 0);
static_assert_64bit(offsetof(SignalGrpcTestCaseBridgedFfi, method) == 8);
static_assert_64bit(offsetof(SignalGrpcTestCaseBridgedFfi, request) == 16);
static_assert_64bit(offsetof(SignalGrpcTestCaseBridgedFfi, request_grpc) == 32);
static_assert_64bit(offsetof(SignalGrpcTestCaseBridgedFfi, response_grpc) == 48);
static_assert_64bit(offsetof(SignalGrpcTestCaseBridgedFfi, response) == 56);
static_assert_64bit(sizeof(SignalGrpcTestCaseBridgedFfi) == 72);
static_assert_64bit(alignof(SignalGrpcTestCaseBridgedFfi) == 8);
typedef SignalGrpcTestCaseBridgedFfi* SignalType_MutPointer_SignalGrpcTestCaseBridgedFfi;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalGrpcTestCaseBridgedFfi) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalGrpcTestCaseBridgedFfi) == 8);
typedef enum {
  SignalCopyBackupMediaOutFfiResultItem,
  SignalCopyBackupMediaOutFfiResultInvalidDataInStream,
  SignalCopyBackupMediaOutFfiResultCredentialRejected,
  SignalCopyBackupMediaOutFfiResultCredentialRejectedWithoutAppropriateServerInfo,
} SignalCopyBackupMediaOutFfiResult_Tag;
typedef struct {
  SignalBridgeCopyBackupMediaOutcomeFfiResult _0;
} SignalCopyBackupMediaOutFfiResultSignalItem_Body;
typedef struct {
  SignalCopyBackupMediaOutFfiResult_Tag tag;
  union {
    SignalCopyBackupMediaOutFfiResultSignalItem_Body item;
  };
} SignalCopyBackupMediaOutFfiResult;
static_assert_64bit(sizeof(SignalCopyBackupMediaOutFfiResult) == 28);
static_assert_64bit(alignof(SignalCopyBackupMediaOutFfiResult) == 4);
typedef SignalCopyBackupMediaOutFfiResult* SignalType_MutPointer_SignalCopyBackupMediaOutFfiResult;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalCopyBackupMediaOutFfiResult) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalCopyBackupMediaOutFfiResult) == 8);
typedef enum {
  SignalMySimpleTestEnumFfiResultA,
  SignalMySimpleTestEnumFfiResultB,
} SignalMySimpleTestEnumFfiResult;
static_assert_64bit(sizeof(SignalMySimpleTestEnumFfiResult) == 4);
static_assert_64bit(alignof(SignalMySimpleTestEnumFfiResult) == 4);
typedef SignalMySimpleTestEnumFfiResult* SignalType_MutPointer_SignalMySimpleTestEnumFfiResult;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalMySimpleTestEnumFfiResult) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalMySimpleTestEnumFfiResult) == 8);
typedef struct {
  int32_t _0;
  int32_t _1;
} SignalMyTestPointFfiResult;
static_assert_64bit(offsetof(SignalMyTestPointFfiResult, _0) == 0);
static_assert_64bit(offsetof(SignalMyTestPointFfiResult, _1) == 4);
static_assert_64bit(sizeof(SignalMyTestPointFfiResult) == 8);
static_assert_64bit(alignof(SignalMyTestPointFfiResult) == 4);
typedef struct {
  int32_t my_numeric_field;
  const int8_t* my_string_field;
} SignalMyTestStructFfiResult;
static_assert_64bit(offsetof(SignalMyTestStructFfiResult, my_numeric_field) == 0);
static_assert_64bit(offsetof(SignalMyTestStructFfiResult, my_string_field) == 8);
static_assert_64bit(sizeof(SignalMyTestStructFfiResult) == 16);
static_assert_64bit(alignof(SignalMyTestStructFfiResult) == 8);
typedef enum {
  SignalMyTestEnumFfiResultUnit,
  SignalMyTestEnumFfiResultSingle,
  SignalMyTestEnumFfiResultSingleNamed,
  SignalMyTestEnumFfiResultDouble,
  SignalMyTestEnumFfiResultRecord,
} SignalMyTestEnumFfiResult_Tag;
typedef struct {
  int32_t _0;
} SignalMyTestEnumFfiResultSignalSingle_Body;
typedef struct {
  int32_t x;
} SignalMyTestEnumFfiResultSignalSingleNamed_Body;
typedef struct {
  int32_t _0;
  int32_t _1;
} SignalMyTestEnumFfiResultSignalDouble_Body;
typedef struct {
  const int8_t* person_name;
  int32_t person_age;
  SignalMyTestPointFfiResult position;
  SignalMyTestStructFfiResult fun_struct;
} SignalMyTestEnumFfiResultSignalRecord_Body;
typedef struct {
  SignalMyTestEnumFfiResult_Tag tag;
  union {
    SignalMyTestEnumFfiResultSignalSingle_Body single;
    SignalMyTestEnumFfiResultSignalSingleNamed_Body single_named;
    SignalMyTestEnumFfiResultSignalDouble_Body double_;
    SignalMyTestEnumFfiResultSignalRecord_Body record;
  };
} SignalMyTestEnumFfiResult;
static_assert_64bit(sizeof(SignalMyTestEnumFfiResult) == 48);
static_assert_64bit(alignof(SignalMyTestEnumFfiResult) == 8);
typedef SignalMyTestEnumFfiResult* SignalType_MutPointer_SignalMyTestEnumFfiResult;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalMyTestEnumFfiResult) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalMyTestEnumFfiResult) == 8);
typedef SignalMyTestPointFfiResult* SignalType_MutPointer_SignalMyTestPointFfiResult;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalMyTestPointFfiResult) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalMyTestPointFfiResult) == 8);
typedef SignalMyTestStructFfiResult* SignalType_MutPointer_SignalMyTestStructFfiResult;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalMyTestStructFfiResult) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalMyTestStructFfiResult) == 8);
typedef SignalTestingFutureCancellationCounter* SignalType_MutPointer_SignalTestingFutureCancellationCounter;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalTestingFutureCancellationCounter) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalTestingFutureCancellationCounter) == 8);
typedef SignalTestingIntBox* SignalType_MutPointer_SignalTestingIntBox;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalTestingIntBox) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalTestingIntBox) == 8);
typedef SignalTestingSemaphore* SignalType_MutPointer_SignalTestingSemaphore;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalTestingSemaphore) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalTestingSemaphore) == 8);
typedef SignalTestingValueHolder* SignalType_MutPointer_SignalTestingValueHolder;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalTestingValueHolder) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalTestingValueHolder) == 8);
typedef enum {
  SignalMyRemoteDeriveEnumFfiResultUnit,
  SignalMyRemoteDeriveEnumFfiResultTuple,
  SignalMyRemoteDeriveEnumFfiResultRecord,
} SignalMyRemoteDeriveEnumFfiResult_Tag;
typedef struct {
  int32_t _0;
  int32_t _1;
} SignalMyRemoteDeriveEnumFfiResultSignalTuple_Body;
typedef struct {
  const int8_t* x;
  int32_t y;
} SignalMyRemoteDeriveEnumFfiResultSignalRecord_Body;
typedef struct {
  SignalMyRemoteDeriveEnumFfiResult_Tag tag;
  union {
    SignalMyRemoteDeriveEnumFfiResultSignalTuple_Body tuple;
    SignalMyRemoteDeriveEnumFfiResultSignalRecord_Body record;
  };
} SignalMyRemoteDeriveEnumFfiResult;
static_assert_64bit(sizeof(SignalMyRemoteDeriveEnumFfiResult) == 24);
static_assert_64bit(alignof(SignalMyRemoteDeriveEnumFfiResult) == 8);
typedef SignalMyRemoteDeriveEnumFfiResult* SignalType_MutPointer_SignalMyRemoteDeriveEnumFfiResult;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalMyRemoteDeriveEnumFfiResult) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalMyRemoteDeriveEnumFfiResult) == 8);
typedef struct {
  int32_t x;
  int32_t y;
} SignalMyRemoteDeriveStructFfiResult;
static_assert_64bit(offsetof(SignalMyRemoteDeriveStructFfiResult, x) == 0);
static_assert_64bit(offsetof(SignalMyRemoteDeriveStructFfiResult, y) == 4);
static_assert_64bit(sizeof(SignalMyRemoteDeriveStructFfiResult) == 8);
static_assert_64bit(alignof(SignalMyRemoteDeriveStructFfiResult) == 4);
typedef SignalMyRemoteDeriveStructFfiResult* SignalType_MutPointer_SignalMyRemoteDeriveStructFfiResult;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalMyRemoteDeriveStructFfiResult) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalMyRemoteDeriveStructFfiResult) == 8);
typedef SignalFfiChatResponse* SignalType_MutPointer_SignalFfiChatResponse;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalFfiChatResponse) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalFfiChatResponse) == 8);
typedef SignalFfiCheckSvr2CredentialsResponse* SignalType_MutPointer_SignalFfiCheckSvr2CredentialsResponse;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalFfiCheckSvr2CredentialsResponse) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalFfiCheckSvr2CredentialsResponse) == 8);
typedef struct {
  SignalTestStream* raw;
} SignalMutPointerTestStream;
static_assert_64bit(offsetof(SignalMutPointerTestStream, raw) == 0);
static_assert_64bit(sizeof(SignalMutPointerTestStream) == 8);
static_assert_64bit(alignof(SignalMutPointerTestStream) == 8);
typedef SignalMutPointerTestStream* SignalType_MutPointer_SignalMutPointerTestStream;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalMutPointerTestStream) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalMutPointerTestStream) == 8);
typedef SignalMutPointerOtherTestingHandleType* SignalType_MutPointer_SignalMutPointerOtherTestingHandleType;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalMutPointerOtherTestingHandleType) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalMutPointerOtherTestingHandleType) == 8);
typedef SignalMutPointerTestingHandleType* SignalType_MutPointer_SignalMutPointerTestingHandleType;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalMutPointerTestingHandleType) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalMutPointerTestingHandleType) == 8);
typedef struct {
  SignalComparableBackup* raw;
} SignalMutPointerComparableBackup;
static_assert_64bit(offsetof(SignalMutPointerComparableBackup, raw) == 0);
static_assert_64bit(sizeof(SignalMutPointerComparableBackup) == 8);
static_assert_64bit(alignof(SignalMutPointerComparableBackup) == 8);
typedef SignalMutPointerComparableBackup* SignalType_MutPointer_SignalMutPointerComparableBackup;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalMutPointerComparableBackup) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalMutPointerComparableBackup) == 8);
typedef struct {
  SignalFakeChatConnection* raw;
} SignalMutPointerFakeChatConnection;
static_assert_64bit(offsetof(SignalMutPointerFakeChatConnection, raw) == 0);
static_assert_64bit(sizeof(SignalMutPointerFakeChatConnection) == 8);
static_assert_64bit(alignof(SignalMutPointerFakeChatConnection) == 8);
typedef SignalMutPointerFakeChatConnection* SignalType_MutPointer_SignalMutPointerFakeChatConnection;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalMutPointerFakeChatConnection) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalMutPointerFakeChatConnection) == 8);
typedef SignalMutPointerFakeChatRemoteEnd* SignalType_MutPointer_SignalMutPointerFakeChatRemoteEnd;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalMutPointerFakeChatRemoteEnd) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalMutPointerFakeChatRemoteEnd) == 8);
typedef struct {
  SignalFakeChatResponse* raw;
} SignalMutPointerFakeChatResponse;
static_assert_64bit(offsetof(SignalMutPointerFakeChatResponse, raw) == 0);
static_assert_64bit(sizeof(SignalMutPointerFakeChatResponse) == 8);
static_assert_64bit(alignof(SignalMutPointerFakeChatResponse) == 8);
typedef SignalMutPointerFakeChatResponse* SignalType_MutPointer_SignalMutPointerFakeChatResponse;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalMutPointerFakeChatResponse) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalMutPointerFakeChatResponse) == 8);
typedef struct {
  SignalFakeChatServer* raw;
} SignalMutPointerFakeChatServer;
static_assert_64bit(offsetof(SignalMutPointerFakeChatServer, raw) == 0);
static_assert_64bit(sizeof(SignalMutPointerFakeChatServer) == 8);
static_assert_64bit(alignof(SignalMutPointerFakeChatServer) == 8);
typedef SignalMutPointerFakeChatServer* SignalType_MutPointer_SignalMutPointerFakeChatServer;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalMutPointerFakeChatServer) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalMutPointerFakeChatServer) == 8);
typedef struct {
  SignalTestingFutureCancellationCounter* raw;
} SignalMutPointerTestingFutureCancellationCounter;
static_assert_64bit(offsetof(SignalMutPointerTestingFutureCancellationCounter, raw) == 0);
static_assert_64bit(sizeof(SignalMutPointerTestingFutureCancellationCounter) == 8);
static_assert_64bit(alignof(SignalMutPointerTestingFutureCancellationCounter) == 8);
typedef SignalMutPointerTestingFutureCancellationCounter* SignalType_MutPointer_SignalMutPointerTestingFutureCancellationCounter;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalMutPointerTestingFutureCancellationCounter) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalMutPointerTestingFutureCancellationCounter) == 8);
typedef struct {
  SignalTestingIntBox* raw;
} SignalMutPointerTestingIntBox;
static_assert_64bit(offsetof(SignalMutPointerTestingIntBox, raw) == 0);
static_assert_64bit(sizeof(SignalMutPointerTestingIntBox) == 8);
static_assert_64bit(alignof(SignalMutPointerTestingIntBox) == 8);
typedef SignalMutPointerTestingIntBox* SignalType_MutPointer_SignalMutPointerTestingIntBox;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalMutPointerTestingIntBox) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalMutPointerTestingIntBox) == 8);
typedef struct {
  SignalTestingSemaphore* raw;
} SignalMutPointerTestingSemaphore;
static_assert_64bit(offsetof(SignalMutPointerTestingSemaphore, raw) == 0);
static_assert_64bit(sizeof(SignalMutPointerTestingSemaphore) == 8);
static_assert_64bit(alignof(SignalMutPointerTestingSemaphore) == 8);
typedef SignalMutPointerTestingSemaphore* SignalType_MutPointer_SignalMutPointerTestingSemaphore;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalMutPointerTestingSemaphore) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalMutPointerTestingSemaphore) == 8);
typedef struct {
  SignalTestingValueHolder* raw;
} SignalMutPointerTestingValueHolder;
static_assert_64bit(offsetof(SignalMutPointerTestingValueHolder, raw) == 0);
static_assert_64bit(sizeof(SignalMutPointerTestingValueHolder) == 8);
static_assert_64bit(alignof(SignalMutPointerTestingValueHolder) == 8);
typedef SignalMutPointerTestingValueHolder* SignalType_MutPointer_SignalMutPointerTestingValueHolder;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalMutPointerTestingValueHolder) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalMutPointerTestingValueHolder) == 8);
typedef SignalMutPointerAuthenticatedChatConnection* SignalType_MutPointer_SignalMutPointerAuthenticatedChatConnection;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalMutPointerAuthenticatedChatConnection) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalMutPointerAuthenticatedChatConnection) == 8);
typedef SignalMutPointerProvisioningChatConnection* SignalType_MutPointer_SignalMutPointerProvisioningChatConnection;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalMutPointerProvisioningChatConnection) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalMutPointerProvisioningChatConnection) == 8);
typedef SignalMutPointerUnauthenticatedChatConnection* SignalType_MutPointer_SignalMutPointerUnauthenticatedChatConnection;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalMutPointerUnauthenticatedChatConnection) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalMutPointerUnauthenticatedChatConnection) == 8);
typedef SignalMutPointerRegisterAccountResponse* SignalType_MutPointer_SignalMutPointerRegisterAccountResponse;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalMutPointerRegisterAccountResponse) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalMutPointerRegisterAccountResponse) == 8);
typedef struct {
  SignalGrpcTestCaseBridgedFfi* base;
  size_t length;
} SignalOwnedBufferOfGrpcTestCaseBridgedFfi;
static_assert_64bit(offsetof(SignalOwnedBufferOfGrpcTestCaseBridgedFfi, base) == 0);
static_assert_64bit(offsetof(SignalOwnedBufferOfGrpcTestCaseBridgedFfi, length) == 8);
static_assert_64bit(sizeof(SignalOwnedBufferOfGrpcTestCaseBridgedFfi) == 16);
static_assert_64bit(alignof(SignalOwnedBufferOfGrpcTestCaseBridgedFfi) == 8);
typedef SignalOwnedBufferOfGrpcTestCaseBridgedFfi* SignalType_MutPointer_SignalOwnedBufferOfGrpcTestCaseBridgedFfi;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalOwnedBufferOfGrpcTestCaseBridgedFfi) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalOwnedBufferOfGrpcTestCaseBridgedFfi) == 8);
typedef SignalOwnedBufferOfMaxAlignedCStringPtr* SignalType_MutPointer_SignalOwnedBufferOfMaxAlignedCStringPtr;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalOwnedBufferOfMaxAlignedCStringPtr) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalOwnedBufferOfMaxAlignedCStringPtr) == 8);
typedef struct {
  SignalType_FixedArray32_uint8_t* base;
  size_t length;
  size_t size_bytes;
} SignalOwnedBufferOfMaxAlignedc_uchar32;
static_assert_64bit(offsetof(SignalOwnedBufferOfMaxAlignedc_uchar32, base) == 0);
static_assert_64bit(offsetof(SignalOwnedBufferOfMaxAlignedc_uchar32, length) == 8);
static_assert_64bit(offsetof(SignalOwnedBufferOfMaxAlignedc_uchar32, size_bytes) == 16);
static_assert_64bit(sizeof(SignalOwnedBufferOfMaxAlignedc_uchar32) == 24);
static_assert_64bit(alignof(SignalOwnedBufferOfMaxAlignedc_uchar32) == 8);
typedef SignalOwnedBufferOfMaxAlignedc_uchar32* SignalType_MutPointer_SignalOwnedBufferOfMaxAlignedc_uchar32;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalOwnedBufferOfMaxAlignedc_uchar32) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalOwnedBufferOfMaxAlignedc_uchar32) == 8);
typedef struct {
  SignalCopyBackupMediaOutFfiResult* base;
  size_t length;
  size_t size_bytes;
} SignalOwnedBufferOfMaxAlignedCopyBackupMediaOutFfiResult;
static_assert_64bit(offsetof(SignalOwnedBufferOfMaxAlignedCopyBackupMediaOutFfiResult, base) == 0);
static_assert_64bit(offsetof(SignalOwnedBufferOfMaxAlignedCopyBackupMediaOutFfiResult, length) == 8);
static_assert_64bit(offsetof(SignalOwnedBufferOfMaxAlignedCopyBackupMediaOutFfiResult, size_bytes) == 16);
static_assert_64bit(sizeof(SignalOwnedBufferOfMaxAlignedCopyBackupMediaOutFfiResult) == 24);
static_assert_64bit(alignof(SignalOwnedBufferOfMaxAlignedCopyBackupMediaOutFfiResult) == 8);
typedef SignalOwnedBufferOfMaxAlignedCopyBackupMediaOutFfiResult* SignalType_MutPointer_SignalOwnedBufferOfMaxAlignedCopyBackupMediaOutFfiResult;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalOwnedBufferOfMaxAlignedCopyBackupMediaOutFfiResult) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalOwnedBufferOfMaxAlignedCopyBackupMediaOutFfiResult) == 8);
typedef struct {
  SignalMySimpleTestEnumFfiResult* base;
  size_t length;
  size_t size_bytes;
} SignalOwnedBufferOfMaxAlignedMySimpleTestEnumFfiResult;
static_assert_64bit(offsetof(SignalOwnedBufferOfMaxAlignedMySimpleTestEnumFfiResult, base) == 0);
static_assert_64bit(offsetof(SignalOwnedBufferOfMaxAlignedMySimpleTestEnumFfiResult, length) == 8);
static_assert_64bit(offsetof(SignalOwnedBufferOfMaxAlignedMySimpleTestEnumFfiResult, size_bytes) == 16);
static_assert_64bit(sizeof(SignalOwnedBufferOfMaxAlignedMySimpleTestEnumFfiResult) == 24);
static_assert_64bit(alignof(SignalOwnedBufferOfMaxAlignedMySimpleTestEnumFfiResult) == 8);
typedef SignalOwnedBufferOfMaxAlignedMySimpleTestEnumFfiResult* SignalType_MutPointer_SignalOwnedBufferOfMaxAlignedMySimpleTestEnumFfiResult;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalOwnedBufferOfMaxAlignedMySimpleTestEnumFfiResult) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalOwnedBufferOfMaxAlignedMySimpleTestEnumFfiResult) == 8);
typedef struct {
  int32_t first;
  const int8_t* second;
} SignalPairOfi32CStringPtr;
static_assert_64bit(offsetof(SignalPairOfi32CStringPtr, first) == 0);
static_assert_64bit(offsetof(SignalPairOfi32CStringPtr, second) == 8);
static_assert_64bit(sizeof(SignalPairOfi32CStringPtr) == 16);
static_assert_64bit(alignof(SignalPairOfi32CStringPtr) == 8);
typedef SignalPairOfi32CStringPtr* SignalType_MutPointer_SignalPairOfi32CStringPtr;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalPairOfi32CStringPtr) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalPairOfi32CStringPtr) == 8);
typedef struct {
  uint32_t first;
  uint32_t second;
} SignalPairOfu32u32;
static_assert_64bit(offsetof(SignalPairOfu32u32, first) == 0);
static_assert_64bit(offsetof(SignalPairOfu32u32, second) == 4);
static_assert_64bit(sizeof(SignalPairOfu32u32) == 8);
static_assert_64bit(alignof(SignalPairOfu32u32) == 4);
typedef SignalPairOfu32u32* SignalType_MutPointer_SignalPairOfu32u32;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalPairOfu32u32) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalPairOfu32u32) == 8);
typedef void (*SignalType_FunctionPointer_void_SignalType_MutPointer_SignalFfiError_SignalType_ConstPointer_SignalType_ConstPointer_void_SignalType_ConstPointer_void)(SignalType_MutPointer_SignalFfiError, SignalType_ConstPointer_SignalType_ConstPointer_void, SignalType_ConstPointer_void);
static_assert_64bit(sizeof(SignalType_FunctionPointer_void_SignalType_MutPointer_SignalFfiError_SignalType_ConstPointer_SignalType_ConstPointer_void_SignalType_ConstPointer_void) == 8);
static_assert_64bit(alignof(SignalType_FunctionPointer_void_SignalType_MutPointer_SignalFfiError_SignalType_ConstPointer_SignalType_ConstPointer_void_SignalType_ConstPointer_void) == 8);
typedef struct {
  SignalType_FunctionPointer_void_SignalType_MutPointer_SignalFfiError_SignalType_ConstPointer_SignalType_ConstPointer_void_SignalType_ConstPointer_void complete;
  const void* context;
  uint64_t cancellation_id;
} SignalCPromiseRawPointer;
static_assert_64bit(offsetof(SignalCPromiseRawPointer, complete) == 0);
static_assert_64bit(offsetof(SignalCPromiseRawPointer, context) == 8);
static_assert_64bit(offsetof(SignalCPromiseRawPointer, cancellation_id) == 16);
static_assert_64bit(sizeof(SignalCPromiseRawPointer) == 24);
static_assert_64bit(alignof(SignalCPromiseRawPointer) == 8);
typedef SignalCPromiseRawPointer* SignalType_MutPointer_SignalCPromiseRawPointer;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalCPromiseRawPointer) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalCPromiseRawPointer) == 8);
typedef void (*SignalType_FunctionPointer_void_SignalType_MutPointer_SignalFfiError_SignalType_ConstPointer_int32_t_SignalType_ConstPointer_void)(SignalType_MutPointer_SignalFfiError, SignalType_ConstPointer_int32_t, SignalType_ConstPointer_void);
static_assert_64bit(sizeof(SignalType_FunctionPointer_void_SignalType_MutPointer_SignalFfiError_SignalType_ConstPointer_int32_t_SignalType_ConstPointer_void) == 8);
static_assert_64bit(alignof(SignalType_FunctionPointer_void_SignalType_MutPointer_SignalFfiError_SignalType_ConstPointer_int32_t_SignalType_ConstPointer_void) == 8);
typedef struct {
  SignalType_FunctionPointer_void_SignalType_MutPointer_SignalFfiError_SignalType_ConstPointer_int32_t_SignalType_ConstPointer_void complete;
  const void* context;
  uint64_t cancellation_id;
} SignalCPromisei32;
static_assert_64bit(offsetof(SignalCPromisei32, complete) == 0);
static_assert_64bit(offsetof(SignalCPromisei32, context) == 8);
static_assert_64bit(offsetof(SignalCPromisei32, cancellation_id) == 16);
static_assert_64bit(sizeof(SignalCPromisei32) == 24);
static_assert_64bit(alignof(SignalCPromisei32) == 8);
typedef SignalCPromisei32* SignalType_MutPointer_SignalCPromisei32;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalCPromisei32) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalCPromisei32) == 8);
typedef void (*SignalType_FunctionPointer_void_SignalType_MutPointer_SignalFfiError_SignalType_ConstPointer_SignalTestStreamChunkFfiResult_SignalType_ConstPointer_void)(SignalType_MutPointer_SignalFfiError, SignalType_ConstPointer_SignalTestStreamChunkFfiResult, SignalType_ConstPointer_void);
static_assert_64bit(sizeof(SignalType_FunctionPointer_void_SignalType_MutPointer_SignalFfiError_SignalType_ConstPointer_SignalTestStreamChunkFfiResult_SignalType_ConstPointer_void) == 8);
static_assert_64bit(alignof(SignalType_FunctionPointer_void_SignalType_MutPointer_SignalFfiError_SignalType_ConstPointer_SignalTestStreamChunkFfiResult_SignalType_ConstPointer_void) == 8);
typedef struct {
  SignalType_FunctionPointer_void_SignalType_MutPointer_SignalFfiError_SignalType_ConstPointer_SignalTestStreamChunkFfiResult_SignalType_ConstPointer_void complete;
  const void* context;
  uint64_t cancellation_id;
} SignalCPromiseTestStreamChunkFfiResult;
static_assert_64bit(offsetof(SignalCPromiseTestStreamChunkFfiResult, complete) == 0);
static_assert_64bit(offsetof(SignalCPromiseTestStreamChunkFfiResult, context) == 8);
static_assert_64bit(offsetof(SignalCPromiseTestStreamChunkFfiResult, cancellation_id) == 16);
static_assert_64bit(sizeof(SignalCPromiseTestStreamChunkFfiResult) == 24);
static_assert_64bit(alignof(SignalCPromiseTestStreamChunkFfiResult) == 8);
typedef SignalCPromiseTestStreamChunkFfiResult* SignalType_MutPointer_SignalCPromiseTestStreamChunkFfiResult;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalCPromiseTestStreamChunkFfiResult) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalCPromiseTestStreamChunkFfiResult) == 8);
typedef void (*SignalType_FunctionPointer_void_SignalType_MutPointer_SignalFfiError_SignalType_ConstPointer_SignalMutPointerOtherTestingHandleType_SignalType_ConstPointer_void)(SignalType_MutPointer_SignalFfiError, SignalType_ConstPointer_SignalMutPointerOtherTestingHandleType, SignalType_ConstPointer_void);
static_assert_64bit(sizeof(SignalType_FunctionPointer_void_SignalType_MutPointer_SignalFfiError_SignalType_ConstPointer_SignalMutPointerOtherTestingHandleType_SignalType_ConstPointer_void) == 8);
static_assert_64bit(alignof(SignalType_FunctionPointer_void_SignalType_MutPointer_SignalFfiError_SignalType_ConstPointer_SignalMutPointerOtherTestingHandleType_SignalType_ConstPointer_void) == 8);
typedef struct {
  SignalType_FunctionPointer_void_SignalType_MutPointer_SignalFfiError_SignalType_ConstPointer_SignalMutPointerOtherTestingHandleType_SignalType_ConstPointer_void complete;
  const void* context;
  uint64_t cancellation_id;
} SignalCPromiseMutPointerOtherTestingHandleType;
static_assert_64bit(offsetof(SignalCPromiseMutPointerOtherTestingHandleType, complete) == 0);
static_assert_64bit(offsetof(SignalCPromiseMutPointerOtherTestingHandleType, context) == 8);
static_assert_64bit(offsetof(SignalCPromiseMutPointerOtherTestingHandleType, cancellation_id) == 16);
static_assert_64bit(sizeof(SignalCPromiseMutPointerOtherTestingHandleType) == 24);
static_assert_64bit(alignof(SignalCPromiseMutPointerOtherTestingHandleType) == 8);
typedef SignalCPromiseMutPointerOtherTestingHandleType* SignalType_MutPointer_SignalCPromiseMutPointerOtherTestingHandleType;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalCPromiseMutPointerOtherTestingHandleType) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalCPromiseMutPointerOtherTestingHandleType) == 8);
typedef void (*SignalType_FunctionPointer_void_SignalType_MutPointer_SignalFfiError_SignalType_ConstPointer_SignalMutPointerTestingHandleType_SignalType_ConstPointer_void)(SignalType_MutPointer_SignalFfiError, SignalType_ConstPointer_SignalMutPointerTestingHandleType, SignalType_ConstPointer_void);
static_assert_64bit(sizeof(SignalType_FunctionPointer_void_SignalType_MutPointer_SignalFfiError_SignalType_ConstPointer_SignalMutPointerTestingHandleType_SignalType_ConstPointer_void) == 8);
static_assert_64bit(alignof(SignalType_FunctionPointer_void_SignalType_MutPointer_SignalFfiError_SignalType_ConstPointer_SignalMutPointerTestingHandleType_SignalType_ConstPointer_void) == 8);
typedef struct {
  SignalType_FunctionPointer_void_SignalType_MutPointer_SignalFfiError_SignalType_ConstPointer_SignalMutPointerTestingHandleType_SignalType_ConstPointer_void complete;
  const void* context;
  uint64_t cancellation_id;
} SignalCPromiseMutPointerTestingHandleType;
static_assert_64bit(offsetof(SignalCPromiseMutPointerTestingHandleType, complete) == 0);
static_assert_64bit(offsetof(SignalCPromiseMutPointerTestingHandleType, context) == 8);
static_assert_64bit(offsetof(SignalCPromiseMutPointerTestingHandleType, cancellation_id) == 16);
static_assert_64bit(sizeof(SignalCPromiseMutPointerTestingHandleType) == 24);
static_assert_64bit(alignof(SignalCPromiseMutPointerTestingHandleType) == 8);
typedef SignalCPromiseMutPointerTestingHandleType* SignalType_MutPointer_SignalCPromiseMutPointerTestingHandleType;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalCPromiseMutPointerTestingHandleType) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalCPromiseMutPointerTestingHandleType) == 8);
typedef void (*SignalType_FunctionPointer_void_SignalType_MutPointer_SignalFfiError_SignalType_ConstPointer_SignalMutPointerFakeChatRemoteEnd_SignalType_ConstPointer_void)(SignalType_MutPointer_SignalFfiError, SignalType_ConstPointer_SignalMutPointerFakeChatRemoteEnd, SignalType_ConstPointer_void);
static_assert_64bit(sizeof(SignalType_FunctionPointer_void_SignalType_MutPointer_SignalFfiError_SignalType_ConstPointer_SignalMutPointerFakeChatRemoteEnd_SignalType_ConstPointer_void) == 8);
static_assert_64bit(alignof(SignalType_FunctionPointer_void_SignalType_MutPointer_SignalFfiError_SignalType_ConstPointer_SignalMutPointerFakeChatRemoteEnd_SignalType_ConstPointer_void) == 8);
typedef struct {
  SignalType_FunctionPointer_void_SignalType_MutPointer_SignalFfiError_SignalType_ConstPointer_SignalMutPointerFakeChatRemoteEnd_SignalType_ConstPointer_void complete;
  const void* context;
  uint64_t cancellation_id;
} SignalCPromiseMutPointerFakeChatRemoteEnd;
static_assert_64bit(offsetof(SignalCPromiseMutPointerFakeChatRemoteEnd, complete) == 0);
static_assert_64bit(offsetof(SignalCPromiseMutPointerFakeChatRemoteEnd, context) == 8);
static_assert_64bit(offsetof(SignalCPromiseMutPointerFakeChatRemoteEnd, cancellation_id) == 16);
static_assert_64bit(sizeof(SignalCPromiseMutPointerFakeChatRemoteEnd) == 24);
static_assert_64bit(alignof(SignalCPromiseMutPointerFakeChatRemoteEnd) == 8);
typedef SignalCPromiseMutPointerFakeChatRemoteEnd* SignalType_MutPointer_SignalCPromiseMutPointerFakeChatRemoteEnd;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalCPromiseMutPointerFakeChatRemoteEnd) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalCPromiseMutPointerFakeChatRemoteEnd) == 8);
typedef void (*SignalType_FunctionPointer_void_SignalType_MutPointer_SignalFfiError_SignalType_ConstPointer_SignalOptionalPairOfMutPointerHttpRequestu64_SignalType_ConstPointer_void)(SignalType_MutPointer_SignalFfiError, SignalType_ConstPointer_SignalOptionalPairOfMutPointerHttpRequestu64, SignalType_ConstPointer_void);
static_assert_64bit(sizeof(SignalType_FunctionPointer_void_SignalType_MutPointer_SignalFfiError_SignalType_ConstPointer_SignalOptionalPairOfMutPointerHttpRequestu64_SignalType_ConstPointer_void) == 8);
static_assert_64bit(alignof(SignalType_FunctionPointer_void_SignalType_MutPointer_SignalFfiError_SignalType_ConstPointer_SignalOptionalPairOfMutPointerHttpRequestu64_SignalType_ConstPointer_void) == 8);
typedef struct {
  SignalType_FunctionPointer_void_SignalType_MutPointer_SignalFfiError_SignalType_ConstPointer_SignalOptionalPairOfMutPointerHttpRequestu64_SignalType_ConstPointer_void complete;
  const void* context;
  uint64_t cancellation_id;
} SignalCPromiseOptionalPairOfMutPointerHttpRequestu64;
static_assert_64bit(offsetof(SignalCPromiseOptionalPairOfMutPointerHttpRequestu64, complete) == 0);
static_assert_64bit(offsetof(SignalCPromiseOptionalPairOfMutPointerHttpRequestu64, context) == 8);
static_assert_64bit(offsetof(SignalCPromiseOptionalPairOfMutPointerHttpRequestu64, cancellation_id) == 16);
static_assert_64bit(sizeof(SignalCPromiseOptionalPairOfMutPointerHttpRequestu64) == 24);
static_assert_64bit(alignof(SignalCPromiseOptionalPairOfMutPointerHttpRequestu64) == 8);
typedef SignalCPromiseOptionalPairOfMutPointerHttpRequestu64* SignalType_MutPointer_SignalCPromiseOptionalPairOfMutPointerHttpRequestu64;
static_assert_64bit(sizeof(SignalType_MutPointer_SignalCPromiseOptionalPairOfMutPointerHttpRequestu64) == 8);
static_assert_64bit(alignof(SignalType_MutPointer_SignalCPromiseOptionalPairOfMutPointerHttpRequestu64) == 8);
typedef struct {
  SignalOwnedBufferOfMaxAlignedLinkedDeviceInternalFfiResult devices;
} SignalGetDevicesOutFfiResult;
static_assert_64bit(offsetof(SignalGetDevicesOutFfiResult, devices) == 0);
static_assert_64bit(sizeof(SignalGetDevicesOutFfiResult) == 24);
static_assert_64bit(alignof(SignalGetDevicesOutFfiResult) == 8);
typedef struct {
  uint8_t id;
} SignalRemoveDeviceArgsFfiResult;
static_assert_64bit(offsetof(SignalRemoveDeviceArgsFfiResult, id) == 0);
static_assert_64bit(sizeof(SignalRemoveDeviceArgsFfiResult) == 1);
static_assert_64bit(alignof(SignalRemoveDeviceArgsFfiResult) == 1);
typedef enum {
  SignalRemoveDeviceOutFfiResultSuccess,
} SignalRemoveDeviceOutFfiResult;
static_assert_64bit(sizeof(SignalRemoveDeviceOutFfiResult) == 4);
static_assert_64bit(alignof(SignalRemoveDeviceOutFfiResult) == 4);
typedef struct {
  SignalOwnedBufferOfMaxAlignedc_uchar32 usernames;
} SignalReserveUsernameHashArgsFfiResult;
static_assert_64bit(offsetof(SignalReserveUsernameHashArgsFfiResult, usernames) == 0);
static_assert_64bit(sizeof(SignalReserveUsernameHashArgsFfiResult) == 24);
static_assert_64bit(alignof(SignalReserveUsernameHashArgsFfiResult) == 8);
typedef enum {
  SignalReserveUsernameHashOutFfiResultSuccess,
  SignalReserveUsernameHashOutFfiResultUsernameNotAvailable,
} SignalReserveUsernameHashOutFfiResult_Tag;
typedef struct {
  SignalType_FixedArray32_uint8_t _0;
} SignalReserveUsernameHashOutFfiResultSignalSuccess_Body;
typedef struct {
  SignalReserveUsernameHashOutFfiResult_Tag tag;
  union {
    SignalReserveUsernameHashOutFfiResultSignalSuccess_Body success;
  };
} SignalReserveUsernameHashOutFfiResult;
static_assert_64bit(sizeof(SignalReserveUsernameHashOutFfiResult) == 36);
static_assert_64bit(alignof(SignalReserveUsernameHashOutFfiResult) == 4);
typedef struct {
  uint8_t id;
  SignalOwnedBuffer encrypted_name;
} SignalSetDeviceNameArgsFfiResult;
static_assert_64bit(offsetof(SignalSetDeviceNameArgsFfiResult, id) == 0);
static_assert_64bit(offsetof(SignalSetDeviceNameArgsFfiResult, encrypted_name) == 8);
static_assert_64bit(sizeof(SignalSetDeviceNameArgsFfiResult) == 24);
static_assert_64bit(alignof(SignalSetDeviceNameArgsFfiResult) == 8);
typedef enum {
  SignalSetDeviceNameOutFfiResultSuccess,
  SignalSetDeviceNameOutFfiResultDeviceNotFound,
} SignalSetDeviceNameOutFfiResult;
static_assert_64bit(sizeof(SignalSetDeviceNameOutFfiResult) == 4);
static_assert_64bit(alignof(SignalSetDeviceNameOutFfiResult) == 4);
typedef struct {
  SignalOwnedBuffer username_ciphertext;
  bool keep_link_handle;
} SignalSetUsernameLinkArgsFfiResult;
static_assert_64bit(offsetof(SignalSetUsernameLinkArgsFfiResult, username_ciphertext) == 0);
static_assert_64bit(offsetof(SignalSetUsernameLinkArgsFfiResult, keep_link_handle) == 16);
static_assert_64bit(sizeof(SignalSetUsernameLinkArgsFfiResult) == 24);
static_assert_64bit(alignof(SignalSetUsernameLinkArgsFfiResult) == 8);
typedef enum {
  SignalSetUsernameLinkOutFfiResultSuccess,
  SignalSetUsernameLinkOutFfiResultUsernameNotSet,
} SignalSetUsernameLinkOutFfiResult_Tag;
typedef struct {
  SignalUuid _0;
} SignalSetUsernameLinkOutFfiResultSignalSuccess_Body;
typedef struct {
  SignalSetUsernameLinkOutFfiResult_Tag tag;
  union {
    SignalSetUsernameLinkOutFfiResultSignalSuccess_Body success;
  };
} SignalSetUsernameLinkOutFfiResult;
static_assert_64bit(sizeof(SignalSetUsernameLinkOutFfiResult) == 20);
static_assert_64bit(alignof(SignalSetUsernameLinkOutFfiResult) == 4);
typedef struct {
  int32_t _0;
  int32_t _1;
} SignalMyTestPointFfiArg;
static_assert_64bit(offsetof(SignalMyTestPointFfiArg, _0) == 0);
static_assert_64bit(offsetof(SignalMyTestPointFfiArg, _1) == 4);
static_assert_64bit(sizeof(SignalMyTestPointFfiArg) == 8);
static_assert_64bit(alignof(SignalMyTestPointFfiArg) == 4);
typedef struct {
  int32_t my_numeric_field;
  const int8_t* my_string_field;
} SignalMyTestStructFfiArg;
static_assert_64bit(offsetof(SignalMyTestStructFfiArg, my_numeric_field) == 0);
static_assert_64bit(offsetof(SignalMyTestStructFfiArg, my_string_field) == 8);
static_assert_64bit(sizeof(SignalMyTestStructFfiArg) == 16);
static_assert_64bit(alignof(SignalMyTestStructFfiArg) == 8);
typedef enum {
  SignalMyTestEnumFfiArgUnit,
  SignalMyTestEnumFfiArgSingle,
  SignalMyTestEnumFfiArgSingleNamed,
  SignalMyTestEnumFfiArgDouble,
  SignalMyTestEnumFfiArgRecord,
} SignalMyTestEnumFfiArg_Tag;
typedef struct {
  int32_t _0;
} SignalMyTestEnumFfiArgSignalSingle_Body;
typedef struct {
  int32_t x;
} SignalMyTestEnumFfiArgSignalSingleNamed_Body;
typedef struct {
  int32_t _0;
  int32_t _1;
} SignalMyTestEnumFfiArgSignalDouble_Body;
typedef struct {
  const int8_t* person_name;
  int32_t person_age;
  SignalMyTestPointFfiArg position;
  SignalMyTestStructFfiArg fun_struct;
} SignalMyTestEnumFfiArgSignalRecord_Body;
typedef struct {
  SignalMyTestEnumFfiArg_Tag tag;
  union {
    SignalMyTestEnumFfiArgSignalSingle_Body single;
    SignalMyTestEnumFfiArgSignalSingleNamed_Body single_named;
    SignalMyTestEnumFfiArgSignalDouble_Body double_;
    SignalMyTestEnumFfiArgSignalRecord_Body record;
  };
} SignalMyTestEnumFfiArg;
static_assert_64bit(sizeof(SignalMyTestEnumFfiArg) == 48);
static_assert_64bit(alignof(SignalMyTestEnumFfiArg) == 8);
typedef enum {
  SignalMyRemoteDeriveEnumFfiArgUnit,
  SignalMyRemoteDeriveEnumFfiArgTuple,
  SignalMyRemoteDeriveEnumFfiArgRecord,
} SignalMyRemoteDeriveEnumFfiArg_Tag;
typedef struct {
  int32_t _0;
  int32_t _1;
} SignalMyRemoteDeriveEnumFfiArgSignalTuple_Body;
typedef struct {
  const int8_t* x;
  int32_t y;
} SignalMyRemoteDeriveEnumFfiArgSignalRecord_Body;
typedef struct {
  SignalMyRemoteDeriveEnumFfiArg_Tag tag;
  union {
    SignalMyRemoteDeriveEnumFfiArgSignalTuple_Body tuple;
    SignalMyRemoteDeriveEnumFfiArgSignalRecord_Body record;
  };
} SignalMyRemoteDeriveEnumFfiArg;
static_assert_64bit(sizeof(SignalMyRemoteDeriveEnumFfiArg) == 24);
static_assert_64bit(alignof(SignalMyRemoteDeriveEnumFfiArg) == 8);
typedef struct {
  int32_t x;
  int32_t y;
} SignalMyRemoteDeriveStructFfiArg;
static_assert_64bit(offsetof(SignalMyRemoteDeriveStructFfiArg, x) == 0);
static_assert_64bit(offsetof(SignalMyRemoteDeriveStructFfiArg, y) == 4);
static_assert_64bit(sizeof(SignalMyRemoteDeriveStructFfiArg) == 8);
static_assert_64bit(alignof(SignalMyRemoteDeriveStructFfiArg) == 4);
typedef struct {
  const SignalCStringPtr* base;
  size_t length;
} SignalBorrowedSliceOfCStringPtr;
static_assert_64bit(offsetof(SignalBorrowedSliceOfCStringPtr, base) == 0);
static_assert_64bit(offsetof(SignalBorrowedSliceOfCStringPtr, length) == 8);
static_assert_64bit(sizeof(SignalBorrowedSliceOfCStringPtr) == 16);
static_assert_64bit(alignof(SignalBorrowedSliceOfCStringPtr) == 8);
typedef struct {
  const SignalMySimpleTestEnumFfiArg* base;
  size_t length;
} SignalBorrowedSliceOfMySimpleTestEnumFfiArg;
static_assert_64bit(offsetof(SignalBorrowedSliceOfMySimpleTestEnumFfiArg, base) == 0);
static_assert_64bit(offsetof(SignalBorrowedSliceOfMySimpleTestEnumFfiArg, length) == 8);
static_assert_64bit(sizeof(SignalBorrowedSliceOfMySimpleTestEnumFfiArg) == 16);
static_assert_64bit(alignof(SignalBorrowedSliceOfMySimpleTestEnumFfiArg) == 8);
typedef struct {
  const SignalTestStream* raw;
} SignalConstPointerTestStream;
static_assert_64bit(offsetof(SignalConstPointerTestStream, raw) == 0);
static_assert_64bit(sizeof(SignalConstPointerTestStream) == 8);
static_assert_64bit(alignof(SignalConstPointerTestStream) == 8);
typedef struct {
  const SignalNonSuspendingBackgroundThreadRuntime* raw;
} SignalConstPointerNonSuspendingBackgroundThreadRuntime;
static_assert_64bit(offsetof(SignalConstPointerNonSuspendingBackgroundThreadRuntime, raw) == 0);
static_assert_64bit(sizeof(SignalConstPointerNonSuspendingBackgroundThreadRuntime) == 8);
static_assert_64bit(alignof(SignalConstPointerNonSuspendingBackgroundThreadRuntime) == 8);
typedef struct {
  const SignalOtherTestingHandleType* raw;
} SignalConstPointerOtherTestingHandleType;
static_assert_64bit(offsetof(SignalConstPointerOtherTestingHandleType, raw) == 0);
static_assert_64bit(sizeof(SignalConstPointerOtherTestingHandleType) == 8);
static_assert_64bit(alignof(SignalConstPointerOtherTestingHandleType) == 8);
typedef struct {
  const SignalTestingHandleType* raw;
} SignalConstPointerTestingHandleType;
static_assert_64bit(offsetof(SignalConstPointerTestingHandleType, raw) == 0);
static_assert_64bit(sizeof(SignalConstPointerTestingHandleType) == 8);
static_assert_64bit(alignof(SignalConstPointerTestingHandleType) == 8);
typedef struct {
  const SignalComparableBackup* raw;
} SignalConstPointerComparableBackup;
static_assert_64bit(offsetof(SignalConstPointerComparableBackup, raw) == 0);
static_assert_64bit(sizeof(SignalConstPointerComparableBackup) == 8);
static_assert_64bit(alignof(SignalConstPointerComparableBackup) == 8);
typedef struct {
  const SignalFakeChatConnection* raw;
} SignalConstPointerFakeChatConnection;
static_assert_64bit(offsetof(SignalConstPointerFakeChatConnection, raw) == 0);
static_assert_64bit(sizeof(SignalConstPointerFakeChatConnection) == 8);
static_assert_64bit(alignof(SignalConstPointerFakeChatConnection) == 8);
typedef struct {
  const SignalFakeChatRemoteEnd* raw;
} SignalConstPointerFakeChatRemoteEnd;
static_assert_64bit(offsetof(SignalConstPointerFakeChatRemoteEnd, raw) == 0);
static_assert_64bit(sizeof(SignalConstPointerFakeChatRemoteEnd) == 8);
static_assert_64bit(alignof(SignalConstPointerFakeChatRemoteEnd) == 8);
typedef struct {
  const SignalFakeChatResponse* raw;
} SignalConstPointerFakeChatResponse;
static_assert_64bit(offsetof(SignalConstPointerFakeChatResponse, raw) == 0);
static_assert_64bit(sizeof(SignalConstPointerFakeChatResponse) == 8);
static_assert_64bit(alignof(SignalConstPointerFakeChatResponse) == 8);
typedef struct {
  const SignalFakeChatServer* raw;
} SignalConstPointerFakeChatServer;
static_assert_64bit(offsetof(SignalConstPointerFakeChatServer, raw) == 0);
static_assert_64bit(sizeof(SignalConstPointerFakeChatServer) == 8);
static_assert_64bit(alignof(SignalConstPointerFakeChatServer) == 8);
typedef struct {
  const SignalGrpcTestCaseBridgedResponse* raw;
} SignalConstPointerGrpcTestCaseBridgedResponse;
static_assert_64bit(offsetof(SignalConstPointerGrpcTestCaseBridgedResponse, raw) == 0);
static_assert_64bit(sizeof(SignalConstPointerGrpcTestCaseBridgedResponse) == 8);
static_assert_64bit(alignof(SignalConstPointerGrpcTestCaseBridgedResponse) == 8);
typedef struct {
  const SignalTestingFutureCancellationCounter* raw;
} SignalConstPointerTestingFutureCancellationCounter;
static_assert_64bit(offsetof(SignalConstPointerTestingFutureCancellationCounter, raw) == 0);
static_assert_64bit(sizeof(SignalConstPointerTestingFutureCancellationCounter) == 8);
static_assert_64bit(alignof(SignalConstPointerTestingFutureCancellationCounter) == 8);
typedef struct {
  const SignalTestingIntBox* raw;
} SignalConstPointerTestingIntBox;
static_assert_64bit(offsetof(SignalConstPointerTestingIntBox, raw) == 0);
static_assert_64bit(sizeof(SignalConstPointerTestingIntBox) == 8);
static_assert_64bit(alignof(SignalConstPointerTestingIntBox) == 8);
typedef struct {
  const SignalTestingSemaphore* raw;
} SignalConstPointerTestingSemaphore;
static_assert_64bit(offsetof(SignalConstPointerTestingSemaphore, raw) == 0);
static_assert_64bit(sizeof(SignalConstPointerTestingSemaphore) == 8);
static_assert_64bit(alignof(SignalConstPointerTestingSemaphore) == 8);
typedef struct {
  const SignalTestingValueHolder* raw;
} SignalConstPointerTestingValueHolder;
static_assert_64bit(offsetof(SignalConstPointerTestingValueHolder, raw) == 0);
static_assert_64bit(sizeof(SignalConstPointerTestingValueHolder) == 8);
static_assert_64bit(alignof(SignalConstPointerTestingValueHolder) == 8);
typedef struct {
  SignalNonSuspendingBackgroundThreadRuntime* raw;
} SignalMutPointerNonSuspendingBackgroundThreadRuntime;
static_assert_64bit(offsetof(SignalMutPointerNonSuspendingBackgroundThreadRuntime, raw) == 0);
static_assert_64bit(sizeof(SignalMutPointerNonSuspendingBackgroundThreadRuntime) == 8);
static_assert_64bit(alignof(SignalMutPointerNonSuspendingBackgroundThreadRuntime) == 8);
SignalFfiError* signal_comparable_backup_destroy(
  SignalMutPointerComparableBackup p
);
SignalFfiError* signal_comparable_backup_get_comparable_string(
  SignalCStringPtr* out,
  SignalConstPointerComparableBackup backup
);
SignalFfiError* signal_comparable_backup_get_unknown_fields(
  SignalBytestringArray* out,
  SignalConstPointerComparableBackup backup
);
SignalFfiError* signal_comparable_backup_read_unencrypted(
  SignalMutPointerComparableBackup* out,
  SignalConstPointerFfiSyncInputStreamStruct stream,
  uint64_t len,
  uint8_t purpose
);
SignalFfiError* signal_fake_chat_connection_destroy(
  SignalMutPointerFakeChatConnection p
);
SignalFfiError* signal_fake_chat_remote_end_destroy(
  SignalMutPointerFakeChatRemoteEnd p
);
SignalFfiError* signal_fake_chat_response_destroy(
  SignalMutPointerFakeChatResponse p
);
SignalFfiError* signal_fake_chat_server_destroy(
  SignalMutPointerFakeChatServer p
);
void signal_free_testing_grpc_test_cases_bridged_vec(
  SignalOwnedBufferOfGrpcTestCaseBridgedFfi buffer
);
SignalFfiError* signal_grpc_test_case_bridged_response_destroy(
  SignalMutPointerGrpcTestCaseBridgedResponse p
);
SignalFfiError* signal_other_testing_handle_type_clone(
  SignalMutPointerOtherTestingHandleType* new_obj,
  SignalConstPointerOtherTestingHandleType obj
);
SignalFfiError* signal_other_testing_handle_type_destroy(
  SignalMutPointerOtherTestingHandleType p
);
SignalFfiError* signal_test_only_fn_returns_123(
  uint32_t* out
);
SignalFfiError* signal_test_stream_destroy(
  SignalMutPointerTestStream p
);
SignalFfiError* signal_testing_NonSuspendingBackgroundThreadRuntime_destroy(
  SignalMutPointerNonSuspendingBackgroundThreadRuntime p
);
SignalFfiError* signal_testing_bridged_string_map_dump_to_json(
  SignalCStringPtr* out,
  SignalConstPointerBridgedStringMap map
);
SignalFfiError* signal_testing_bulk_pull_from_stream_cancel(
  SignalConstPointerTestStream stream
);
SignalFfiError* signal_testing_bulk_pull_from_stream_new(
  SignalMutPointerTestStream* out,
  SignalBorrowedBytestringArray contents,
  bool end_with_error
);
SignalFfiError* signal_testing_bulk_pull_from_stream_next_chunk(
  SignalCPromiseTestStreamChunkFfiResult* promise,
  SignalConstPointerTokioAsyncContext async_runtime,
  SignalConstPointerTestStream stream
);
SignalFfiError* signal_testing_cdsi_lookup_error_convert(
  const int8_t* error_description
);
SignalFfiError* signal_testing_cdsi_lookup_response_convert(
  SignalCPromiseFfiCdsiLookupResponse* promise,
  SignalConstPointerTokioAsyncContext async_runtime
);
SignalFfiError* signal_testing_chat_connect_error_convert(
  const int8_t* error_description
);
SignalFfiError* signal_testing_chat_request_get_body(
  SignalOwnedBuffer* out,
  SignalConstPointerHttpRequest request
);
SignalFfiError* signal_testing_chat_request_get_header_names(
  SignalBytestringArray* out,
  SignalConstPointerHttpRequest request
);
SignalFfiError* signal_testing_chat_request_get_header_value(
  SignalCStringPtr* out,
  SignalConstPointerHttpRequest request,
  const int8_t* header_name
);
SignalFfiError* signal_testing_chat_request_get_method(
  SignalCStringPtr* out,
  SignalConstPointerHttpRequest request
);
SignalFfiError* signal_testing_chat_request_get_path(
  SignalCStringPtr* out,
  SignalConstPointerHttpRequest request
);
SignalFfiError* signal_testing_chat_response_convert(
  SignalFfiChatResponse* out,
  bool body_present
);
SignalFfiError* signal_testing_chat_send_error_convert(
  const int8_t* error_description
);
SignalFfiError* signal_testing_clear_push_token_tests(
  SignalOwnedBufferOfGrpcTestCaseBridgedFfi* out
);
SignalFfiError* signal_testing_connection_manager_is_using_proxy(
  int32_t* out,
  SignalConstPointerConnectionManager manager
);
SignalFfiError* signal_testing_conversion_bool_identity(
  bool* out,
  bool x
);
SignalFfiError* signal_testing_conversion_bool_to_string(
  SignalCStringPtr* out,
  bool x
);
SignalFfiError* signal_testing_conversion_bridge_vec_data32_identity(
  SignalOwnedBufferOfMaxAlignedc_uchar32* out,
  SignalBorrowedSliceOfc_uchar32 x
);
SignalFfiError* signal_testing_conversion_bridge_vec_data32_to_string(
  SignalCStringPtr* out,
  SignalBorrowedSliceOfc_uchar32 x
);
SignalFfiError* signal_testing_conversion_bridge_vec_string_identity(
  SignalOwnedBufferOfMaxAlignedCStringPtr* out,
  SignalBorrowedSliceOfCStringPtr x
);
SignalFfiError* signal_testing_conversion_bridge_vec_string_to_string(
  SignalCStringPtr* out,
  SignalBorrowedSliceOfCStringPtr x
);
SignalFfiError* signal_testing_conversion_data32_identity(
  SignalType_FixedArray32_uint8_t* out,
  const SignalType_FixedArray32_uint8_t* x
);
SignalFfiError* signal_testing_conversion_data32_to_string(
  SignalCStringPtr* out,
  const SignalType_FixedArray32_uint8_t* x
);
SignalFfiError* signal_testing_conversion_data_identity(
  SignalOwnedBuffer* out,
  SignalBorrowedBuffer x
);
SignalFfiError* signal_testing_conversion_data_to_string(
  SignalCStringPtr* out,
  SignalBorrowedBuffer x
);
SignalFfiError* signal_testing_conversion_data_vec_u8_identity(
  SignalOwnedBuffer* out,
  SignalBorrowedBuffer x
);
SignalFfiError* signal_testing_conversion_data_vec_u8_to_string(
  SignalCStringPtr* out,
  SignalBorrowedBuffer x
);
SignalFfiError* signal_testing_conversion_device_id_identity(
  uint8_t* out,
  uint8_t x
);
SignalFfiError* signal_testing_conversion_device_id_to_string(
  SignalCStringPtr* out,
  uint8_t x
);
SignalFfiError* signal_testing_conversion_i32_identity(
  int32_t* out,
  int32_t x
);
SignalFfiError* signal_testing_conversion_i32_to_string(
  SignalCStringPtr* out,
  int32_t x
);
SignalFfiError* signal_testing_conversion_service_id_identity(
  SignalType_FixedArray17_uint8_t* out,
  const SignalType_FixedArray17_uint8_t* x
);
SignalFfiError* signal_testing_conversion_service_id_to_string(
  SignalCStringPtr* out,
  const SignalType_FixedArray17_uint8_t* x
);
SignalFfiError* signal_testing_conversion_string_identity(
  SignalCStringPtr* out,
  const int8_t* x
);
SignalFfiError* signal_testing_conversion_timestamp_identity(
  uint64_t* out,
  uint64_t x
);
SignalFfiError* signal_testing_conversion_timestamp_to_string(
  SignalCStringPtr* out,
  uint64_t x
);
SignalFfiError* signal_testing_conversion_u16_identity(
  uint16_t* out,
  uint16_t x
);
SignalFfiError* signal_testing_conversion_u16_to_string(
  SignalCStringPtr* out,
  uint16_t x
);
SignalFfiError* signal_testing_conversion_u8_identity(
  uint8_t* out,
  uint8_t x
);
SignalFfiError* signal_testing_conversion_u8_to_string(
  SignalCStringPtr* out,
  uint8_t x
);
SignalFfiError* signal_testing_conversion_uuid_identity(
  SignalUuid* out,
  SignalUuid x
);
SignalFfiError* signal_testing_conversion_uuid_to_string(
  SignalCStringPtr* out,
  SignalUuid x
);
SignalFfiError* signal_testing_convert_optional_uuid(
  SignalOptionalUuid* out,
  bool present
);
SignalFfiError* signal_testing_copy_backup_media_tests(
  SignalOwnedBufferOfGrpcTestCaseBridgedFfi* out
);
SignalFfiError* signal_testing_create_otp(
  SignalCStringPtr* out,
  const int8_t* username,
  SignalBorrowedBuffer secret
);
SignalFfiError* signal_testing_create_otp_from_base64(
  SignalCStringPtr* out,
  const int8_t* username,
  const int8_t* secret
);
SignalFfiError* signal_testing_delete_username_hash_tests(
  SignalOwnedBufferOfGrpcTestCaseBridgedFfi* out
);
SignalFfiError* signal_testing_delete_username_link_tests(
  SignalOwnedBufferOfGrpcTestCaseBridgedFfi* out
);
SignalFfiError* signal_testing_enable_deterministic_rng_for_testing(void);
SignalFfiError* signal_testing_error_on_borrow_async(
  const void* _input
);
SignalFfiError* signal_testing_error_on_borrow_io(
  SignalCPromisebool* promise,
  SignalConstPointerNonSuspendingBackgroundThreadRuntime async_runtime,
  const void* _input
);
SignalFfiError* signal_testing_error_on_borrow_sync(
  const void* _input
);
SignalFfiError* signal_testing_error_on_return_async(
  SignalType_ConstPointer_void* out,
  const void* _needs_cleanup
);
SignalFfiError* signal_testing_error_on_return_io(
  SignalCPromiseRawPointer* promise,
  SignalConstPointerNonSuspendingBackgroundThreadRuntime async_runtime,
  const void* _needs_cleanup
);
SignalFfiError* signal_testing_error_on_return_sync(
  SignalType_ConstPointer_void* out,
  const void* _needs_cleanup
);
SignalFfiError* signal_testing_fake_chat_connection_create(
  SignalMutPointerFakeChatConnection* out,
  SignalConstPointerTokioAsyncContext tokio,
  SignalConstPointerFfiChatListenerStruct listener,
  const int8_t* grpc_overrides_joined_by_newlines,
  const int8_t* alerts_joined_by_newlines
);
SignalFfiError* signal_testing_fake_chat_connection_create_provisioning(
  SignalMutPointerFakeChatConnection* out,
  SignalConstPointerTokioAsyncContext tokio,
  SignalConstPointerFfiProvisioningListenerStruct listener
);
SignalFfiError* signal_testing_fake_chat_connection_take_authenticated_chat(
  SignalMutPointerAuthenticatedChatConnection* out,
  SignalConstPointerFakeChatConnection chat
);
SignalFfiError* signal_testing_fake_chat_connection_take_provisioning_chat(
  SignalMutPointerProvisioningChatConnection* out,
  SignalConstPointerFakeChatConnection chat
);
SignalFfiError* signal_testing_fake_chat_connection_take_remote(
  SignalMutPointerFakeChatRemoteEnd* out,
  SignalConstPointerFakeChatConnection chat
);
SignalFfiError* signal_testing_fake_chat_connection_take_unauthenticated_chat(
  SignalMutPointerUnauthenticatedChatConnection* out,
  SignalConstPointerFakeChatConnection chat
);
SignalFfiError* signal_testing_fake_chat_remote_end_binproto_to_json(
  SignalCStringPtr* out,
  const int8_t* name,
  SignalBorrowedBuffer input
);
SignalFfiError* signal_testing_fake_chat_remote_end_grpc_frame_for_message_length(
  SignalOwnedBuffer* out,
  uint32_t len
);
SignalFfiError* signal_testing_fake_chat_remote_end_inject_connection_interrupted(
  SignalConstPointerFakeChatRemoteEnd chat
);
SignalFfiError* signal_testing_fake_chat_remote_end_json_to_binproto(
  SignalOwnedBuffer* out,
  const int8_t* name,
  const int8_t* input
);
SignalFfiError* signal_testing_fake_chat_remote_end_next_grpc_message(
  SignalPairOfu32u32* out,
  SignalBorrowedBuffer input,
  uint32_t offset
);
SignalFfiError* signal_testing_fake_chat_remote_end_receive_incoming_grpc_request(
  SignalCPromiseOptionalPairOfMutPointerHttpRequestu64* promise,
  SignalConstPointerTokioAsyncContext async_runtime,
  SignalConstPointerFakeChatRemoteEnd chat
);
SignalFfiError* signal_testing_fake_chat_remote_end_receive_incoming_request(
  SignalCPromiseOptionalPairOfMutPointerHttpRequestu64* promise,
  SignalConstPointerTokioAsyncContext async_runtime,
  SignalConstPointerFakeChatRemoteEnd chat
);
SignalFfiError* signal_testing_fake_chat_remote_end_send_raw_server_request(
  SignalConstPointerFakeChatRemoteEnd chat,
  SignalBorrowedBuffer bytes
);
SignalFfiError* signal_testing_fake_chat_remote_end_send_raw_server_response(
  SignalConstPointerFakeChatRemoteEnd chat,
  SignalBorrowedBuffer bytes
);
SignalFfiError* signal_testing_fake_chat_remote_end_send_server_grpc_response(
  SignalCPromisebool* promise,
  SignalConstPointerTokioAsyncContext async_runtime,
  SignalConstPointerFakeChatRemoteEnd chat,
  SignalConstPointerFakeChatResponse response
);
SignalFfiError* signal_testing_fake_chat_remote_end_send_server_grpc_test_case_response(
  SignalCPromisebool* promise,
  SignalConstPointerTokioAsyncContext async_runtime,
  SignalConstPointerFakeChatRemoteEnd chat,
  uint64_t id,
  SignalConstPointerGrpcTestCaseBridgedResponse response
);
SignalFfiError* signal_testing_fake_chat_remote_end_send_server_response(
  SignalConstPointerFakeChatRemoteEnd chat,
  SignalConstPointerFakeChatResponse response
);
SignalFfiError* signal_testing_fake_chat_response_create(
  SignalMutPointerFakeChatResponse* out,
  uint64_t id,
  uint16_t status,
  const int8_t* message,
  SignalBorrowedBytestringArray headers,
  SignalOptionalBorrowedSliceOfc_uchar body
);
SignalFfiError* signal_testing_fake_chat_server_create(
  SignalMutPointerFakeChatServer* out
);
SignalFfiError* signal_testing_fake_chat_server_get_next_remote(
  SignalCPromiseMutPointerFakeChatRemoteEnd* promise,
  SignalConstPointerTokioAsyncContext async_runtime,
  SignalConstPointerFakeChatServer server
);
SignalFfiError* signal_testing_fake_registration_session_create_session(
  SignalCPromiseMutPointerRegistrationService* promise,
  SignalConstPointerTokioAsyncContext async_runtime,
  SignalFfiRegistrationCreateSessionRequest create_session,
  SignalConstPointerFakeChatServer chat
);
SignalFfiError* signal_testing_fingerprint_version_mismatch_error(
  uint32_t theirs,
  uint32_t ours
);
SignalFfiError* signal_testing_force_emit_vec_of_bridge_copy_backup_media_out(
  SignalOwnedBufferOfMaxAlignedCopyBackupMediaOutFfiResult* out
);
SignalFfiError* signal_testing_future_cancellation_counter_create(
  SignalMutPointerTestingFutureCancellationCounter* out,
  uint8_t initial_value
);
SignalFfiError* signal_testing_future_cancellation_counter_destroy(
  SignalMutPointerTestingFutureCancellationCounter p
);
SignalFfiError* signal_testing_future_cancellation_counter_wait_for_count(
  SignalCPromisebool* promise,
  SignalConstPointerTokioAsyncContext async_runtime,
  SignalConstPointerTestingFutureCancellationCounter count,
  uint8_t target
);
SignalFfiError* signal_testing_future_failure(
  SignalCPromisei32* promise,
  SignalConstPointerNonSuspendingBackgroundThreadRuntime async_runtime,
  uint8_t _input
);
SignalFfiError* signal_testing_future_increment_on_cancel(
  SignalCPromisebool* promise,
  SignalConstPointerTokioAsyncContext async_runtime,
  SignalConstPointerTestingFutureCancellationCounter _guard
);
SignalFfiError* signal_testing_future_produces_other_pointer_type(
  SignalCPromiseMutPointerOtherTestingHandleType* promise,
  SignalConstPointerNonSuspendingBackgroundThreadRuntime async_runtime,
  const int8_t* input
);
SignalFfiError* signal_testing_future_produces_pointer_type(
  SignalCPromiseMutPointerTestingHandleType* promise,
  SignalConstPointerNonSuspendingBackgroundThreadRuntime async_runtime,
  uint8_t input
);
SignalFfiError* signal_testing_future_success(
  SignalCPromisei32* promise,
  SignalConstPointerNonSuspendingBackgroundThreadRuntime async_runtime,
  uint8_t input
);
SignalFfiError* signal_testing_get_devices_tests(
  SignalOwnedBufferOfGrpcTestCaseBridgedFfi* out
);
SignalFfiError* signal_testing_handle_type_clone(
  SignalMutPointerTestingHandleType* new_obj,
  SignalConstPointerTestingHandleType obj
);
SignalFfiError* signal_testing_handle_type_destroy(
  SignalMutPointerTestingHandleType p
);
SignalFfiError* signal_testing_input_stream_read_into_zero_length_slice(
  SignalOwnedBuffer* out,
  SignalConstPointerFfiSyncInputStreamStruct caps_alphabet_input
);
SignalFfiError* signal_testing_int_box_destroy(
  SignalMutPointerTestingIntBox p
);
SignalFfiError* signal_testing_key_trans_chat_send_error(void);
SignalFfiError* signal_testing_key_trans_fatal_verification_failure(void);
SignalFfiError* signal_testing_key_trans_non_fatal_verification_failure(void);
SignalFfiError* signal_testing_key_trans_stored_account_data(
  SignalOwnedBuffer* out
);
SignalFfiError* signal_testing_my_remote_derive_enum_identity(
  SignalMyRemoteDeriveEnumFfiResult* out,
  SignalMyRemoteDeriveEnumFfiArg x
);
SignalFfiError* signal_testing_my_remote_derive_struct_identity(
  SignalMyRemoteDeriveStructFfiResult* out,
  SignalMyRemoteDeriveStructFfiArg x
);
SignalFfiError* signal_testing_my_simple_test_enum_bridge_vec_identity(
  SignalOwnedBufferOfMaxAlignedMySimpleTestEnumFfiResult* out,
  SignalBorrowedSliceOfMySimpleTestEnumFfiArg x
);
SignalFfiError* signal_testing_my_simple_test_enum_bridge_vec_to_string(
  SignalCStringPtr* out,
  SignalBorrowedSliceOfMySimpleTestEnumFfiArg x
);
SignalFfiError* signal_testing_my_simple_test_enum_identity(
  SignalMySimpleTestEnumFfiResult* out,
  SignalMySimpleTestEnumFfiArg x
);
SignalFfiError* signal_testing_my_simple_test_enum_to_string(
  SignalCStringPtr* out,
  SignalMySimpleTestEnumFfiArg x
);
SignalFfiError* signal_testing_my_test_enum_identity(
  SignalMyTestEnumFfiResult* out,
  SignalMyTestEnumFfiArg x
);
SignalFfiError* signal_testing_my_test_enum_to_string(
  SignalCStringPtr* out,
  SignalMyTestEnumFfiArg x
);
SignalFfiError* signal_testing_my_test_point_identity(
  SignalMyTestPointFfiResult* out,
  SignalMyTestPointFfiArg x
);
SignalFfiError* signal_testing_my_test_point_to_string(
  SignalCStringPtr* out,
  SignalMyTestPointFfiArg x
);
SignalFfiError* signal_testing_my_test_struct_identity(
  SignalMyTestStructFfiResult* out,
  SignalMyTestStructFfiArg x
);
SignalFfiError* signal_testing_my_test_struct_to_string(
  SignalCStringPtr* out,
  SignalMyTestStructFfiArg x
);
SignalFfiError* signal_testing_other_testing_handle_type_get_value(
  SignalCStringPtr* out,
  SignalConstPointerOtherTestingHandleType handle
);
SignalFfiError* signal_testing_panic_in_body_async(
  const void* _input
);
SignalFfiError* signal_testing_panic_in_body_io(
  SignalCPromisebool* promise,
  SignalConstPointerNonSuspendingBackgroundThreadRuntime async_runtime,
  const void* _input
);
SignalFfiError* signal_testing_panic_in_body_sync(
  const void* _input
);
SignalFfiError* signal_testing_panic_on_borrow_async(
  const void* _input
);
SignalFfiError* signal_testing_panic_on_borrow_io(
  SignalCPromisebool* promise,
  SignalConstPointerNonSuspendingBackgroundThreadRuntime async_runtime,
  const void* _input
);
SignalFfiError* signal_testing_panic_on_borrow_sync(
  const void* _input
);
SignalFfiError* signal_testing_panic_on_load_async(
  const void* _needs_cleanup,
  const void* _input
);
SignalFfiError* signal_testing_panic_on_load_io(
  SignalCPromisebool* promise,
  SignalConstPointerNonSuspendingBackgroundThreadRuntime async_runtime,
  const void* _needs_cleanup,
  const void* _input
);
SignalFfiError* signal_testing_panic_on_load_sync(
  const void* _needs_cleanup,
  const void* _input
);
SignalFfiError* signal_testing_panic_on_return_async(
  SignalType_ConstPointer_void* out,
  const void* _needs_cleanup
);
SignalFfiError* signal_testing_panic_on_return_io(
  SignalCPromiseRawPointer* promise,
  SignalConstPointerNonSuspendingBackgroundThreadRuntime async_runtime,
  const void* _needs_cleanup
);
SignalFfiError* signal_testing_panic_on_return_sync(
  SignalType_ConstPointer_void* out,
  const void* _needs_cleanup
);
SignalFfiError* signal_testing_process_bytestring_array(
  SignalBytestringArray* out,
  SignalBorrowedSliceOfBuffers input
);
SignalFfiError* signal_testing_register_account_response_create_test_value(
  SignalMutPointerRegisterAccountResponse* out
);
SignalFfiError* signal_testing_registration_service_check_svr2_credentials_error_convert(
  const int8_t* error_description
);
SignalFfiError* signal_testing_registration_service_check_svr2_credentials_response_convert(
  SignalFfiCheckSvr2CredentialsResponse* out
);
SignalFfiError* signal_testing_registration_service_create_session_error_convert(
  const int8_t* error_description
);
SignalFfiError* signal_testing_registration_service_register_account_error_convert(
  const int8_t* error_description
);
SignalFfiError* signal_testing_registration_service_request_verification_code_error_convert(
  const int8_t* error_description
);
SignalFfiError* signal_testing_registration_service_resume_session_error_convert(
  const int8_t* error_description
);
SignalFfiError* signal_testing_registration_service_submit_verification_error_convert(
  const int8_t* error_description
);
SignalFfiError* signal_testing_registration_service_update_session_error_convert(
  const int8_t* error_description
);
SignalFfiError* signal_testing_registration_session_info_convert(
  SignalMutPointerRegistrationSession* out
);
SignalFfiError* signal_testing_remove_device_tests(
  SignalOwnedBufferOfGrpcTestCaseBridgedFfi* out
);
SignalFfiError* signal_testing_reserve_username_hash_tests(
  SignalOwnedBufferOfGrpcTestCaseBridgedFfi* out
);
SignalFfiError* signal_testing_return_io_error(
  SignalType_MutPointer_SignalFfiError* out
);
SignalFfiError* signal_testing_return_pair(
  SignalPairOfi32CStringPtr* out
);
SignalFfiError* signal_testing_return_some_io_error(
  SignalType_MutPointer_SignalFfiError* out,
  bool present
);
SignalFfiError* signal_testing_return_string_array(
  SignalBytestringArray* out
);
SignalFfiError* signal_testing_semaphore_add_permits(
  SignalConstPointerTestingSemaphore semaphore,
  uint32_t permits
);
SignalFfiError* signal_testing_semaphore_destroy(
  SignalMutPointerTestingSemaphore p
);
SignalFfiError* signal_testing_semaphore_new(
  SignalMutPointerTestingSemaphore* out,
  uint32_t initial
);
SignalFfiError* signal_testing_set_device_name_tests(
  SignalOwnedBufferOfGrpcTestCaseBridgedFfi* out
);
SignalFfiError* signal_testing_set_push_token_apns_tests(
  SignalOwnedBufferOfGrpcTestCaseBridgedFfi* out
);
SignalFfiError* signal_testing_set_username_link_tests(
  SignalOwnedBufferOfGrpcTestCaseBridgedFfi* out
);
SignalFfiError* signal_testing_signed_public_pre_key_check_bridges_correctly(
  SignalConstPointerPublicKey source_public_key,
  SignalFfiSignedPublicPreKey signed_pre_key
);
SignalFfiError* signal_testing_test_stream_chunk_return(
  SignalTestStreamChunkFfiResult* out
);
SignalFfiError* signal_testing_testing_handle_type_get_value(
  uint8_t* out,
  SignalConstPointerTestingHandleType handle
);
SignalFfiError* signal_testing_testing_int_box_get(
  int32_t* out,
  SignalConstPointerTestingIntBox my_int_box
);
SignalFfiError* signal_testing_testing_int_box_new(
  SignalMutPointerTestingIntBox* out,
  int32_t value
);
SignalFfiError* signal_testing_tokio_async_context_future_success_bytes(
  SignalCPromiseOwnedBuffer* promise,
  SignalConstPointerTokioAsyncContext async_runtime,
  int32_t count
);
SignalFfiError* signal_testing_tokio_async_context_new_single_threaded(
  SignalMutPointerTokioAsyncContext* out
);
SignalFfiError* signal_testing_tokio_async_future(
  SignalCPromisei32* promise,
  SignalConstPointerTokioAsyncContext async_runtime,
  uint8_t input
);
SignalFfiError* signal_testing_value_holder_destroy(
  SignalMutPointerTestingValueHolder p
);
SignalFfiError* signal_testing_value_holder_get(
  int32_t* out,
  SignalConstPointerTestingValueHolder holder
);
SignalFfiError* signal_testing_value_holder_new(
  SignalMutPointerTestingValueHolder* out,
  int32_t value
);