disabled_rules:
- cyclomatic_complexity
- empty_enum_arguments
- force_try
- function_body_length
- function_parameter_count
- identifier_name
- line_length
- redundant_optional_initialization
- trailing_comma
- type_body_length
opt_in_rules:
- attributes
- file_header
file_header:
  required_pattern: |
    //
    // Copyright \d{4}(-\d{4})? Signal Messenger, LLC.
    // SPDX-License-Identifier: AGPL-3.0-only
    //
inclusive_language:
  override_allowed_terms:
  - master
