//
// Copyright (C) 2020 Signal Messenger, LLC.
// All rights reserved.
//
// SPDX-License-Identifier: GPL-3.0-only
//
// Generated by zkgroup/codegen/codegen.py - do not edit

import Foundation
import SignalFfi

public class AuthCredential : ByteArray {

  public static let SIZE: Int = 181

  public init(contents: [UInt8]) throws  {
    try super.init(newContents: contents, expectedLength: AuthCredential.SIZE)

    
    let ffi_return = FFI_AuthCredential_checkValidContents(self.contents, UInt32(self.contents.count))

    if (ffi_return == Native.FFI_RETURN_INPUT_ERROR) {
      throw ZkGroupException.InvalidInput
    }

    if (ffi_return != Native.FFI_RETURN_OK) {
      throw ZkGroupException.ZkGroupError
    }
  }

  public func serialize() -> [UInt8] {
    return contents
  }

}
