//
// Copyright (C) 2020 Signal Messenger, LLC.
// All rights reserved.
//
// SPDX-License-Identifier: GPL-3.0-only
//
// Generated by zkgroup/codegen/codegen.py - do not edit

import Foundation
import SignalFfi

public class ProfileKey : ByteArray {

  public static let SIZE: Int = 32

  public required init(contents: [UInt8]) throws  {
    try super.init(newContents: contents, expectedLength: ProfileKey.SIZE)
  }

  public func getCommitment(uuid: ZKGUuid) throws  -> ProfileKeyCommitment {
    return try withUnsafePointerToSerialized { contents in
      try uuid.withUnsafePointerToSerialized { uuid in
        try invokeFnReturningSerialized {
          signal_profile_key_get_commitment($0, contents, uuid)
        }
      }
    }
  }

  public func getProfileKeyVersion(uuid: ZKGUuid) throws  -> ProfileKeyVersion {
    return try withUnsafePointerToSerialized { contents in
      try uuid.withUnsafePointerToSerialized { uuid in
        try invokeFnReturningSerialized {
          signal_profile_key_get_profile_key_version($0, contents, uuid)
        }
      }
    }
  }

}
