//
// Copyright (C) 2020 Signal Messenger, LLC.
// All rights reserved.
//
// SPDX-License-Identifier: GPL-3.0-only
//
// Generated by zkgroup/codegen/codegen.py - do not edit

import Foundation
import SignalFfi

public class ReceiptCredentialRequestContext : ByteArray {

  public static let SIZE: Int = 177

  public required init(contents: [UInt8]) throws  {
    try super.init(newContents: contents, expectedLength: ReceiptCredentialRequestContext.SIZE)

    try withUnsafePointerToSerialized { contents in
      try checkError(signal_receipt_credential_request_context_check_valid_contents(contents))
    }
  }

  public func getRequest() throws  -> ReceiptCredentialRequest {
    return try withUnsafePointerToSerialized { contents in
      try invokeFnReturningSerialized {
        signal_receipt_credential_request_context_get_request($0, contents)
      }
    }
  }

}
