//
// Copyright 2026 Signal Messenger, LLC.
// SPDX-License-Identifier: AGPL-3.0-only
//

package org.signal.libsignal.net

import org.signal.libsignal.internal.CompletableFuture
import org.signal.libsignal.internal.NativeNice
import org.signal.libsignal.internal.mapWithCancellation

public sealed class AuthCheckResult {
  /**
   * The credentials could be used to make a call to SVR service by the user
   * associated with the `CheckSvrCredentialsRequest.number` phone number.
   */
  public data object Match : AuthCheckResult()

  /**
   * The credentials were generated by a different user.
   */
  public data object NoMatch : AuthCheckResult()

  /**
   * This status indicates that the corresponding credentials token should no longer be used.
   * This may be because it has expired or invalid, but it can also mean that there is a more
   * recent token in the request which should be used instead.
   */
  public data object Invalid : AuthCheckResult()
}

public class UnauthCredentialsService(
  private val connection: UnauthenticatedChatConnection,
) {
  /**
   * Given a list of secure value recovery (SVR) service credentials and a phone
   * number, checks and returns which of the provided credentials were generated
   * by the user with the given phone number and have not yet expired.
   *
   * All exceptions are mapped into [RequestResult]; unexpected ones will be treated as
   * [RequestResult.ApplicationError].
   *
   * @param number A phone number in the E164 format to check the passwords against. Only
   * passwords generated for the user associated with the given number will be marked as
   * `Match`.
   *
   * @param credentials A list of credentials (`username:password`) from previously made calls to
   * `ExternalServiceCredentials.GetExternalServiceCredentials()` for
   * `EXTERNAL_SERVICE_TYPE_SVR`. This list may contain credentials generated by different
   * users. Up to 10 credentials can be checked.
   *
   * @returns A map from the inputted credential to its corresponding result
   */
  public fun checkSvrCredentials(
    number: String,
    credentials: List<String>,
  ): CompletableFuture<RequestResult<Map<String, AuthCheckResult>, Nothing>> =
    try {
      NativeNice
        .UnauthenticatedChatConnection_check_svr_credentials(
          asyncCtx = connection.tokioAsyncContext,
          chat = connection,
          number = number,
          credentials = credentials,
        ).mapWithCancellation(
          onSuccess = { RequestResult.Success(it.toMap()) },
          onError = { err -> err.toRequestResult() },
        )
    } catch (e: Throwable) {
      CompletableFuture.completedFuture(RequestResult.ApplicationError(e))
    }
}
