//
// Copyright (C) 2020 Signal Messenger, LLC.
// All rights reserved.
//
// SPDX-License-Identifier: GPL-3.0-only
//

// Generated by zkgroup/codegen/codegen.py - do not edit

package org.signal.zkgroup;

import org.signal.zkgroup.internal.ByteArray;
import org.signal.zkgroup.internal.Native;

public final class ServerPublicParams extends ByteArray {

  public static final int SIZE = 225;

  public ServerPublicParams(byte[] contents)  {
    super(contents, SIZE, true);
    
    int ffi_return = Native.serverPublicParamsCheckValidContentsJNI(contents);

    if (ffi_return == Native.FFI_RETURN_INPUT_ERROR) {
      throw new IllegalArgumentException(new InvalidInputException("FFI_RETURN_INPUT_ERROR"));
    }

    if (ffi_return != Native.FFI_RETURN_OK) {
      throw new ZkGroupError("FFI_RETURN!=OK");
    }
  }

  public void verifySignature(byte[] message, NotarySignature notarySignature) throws VerificationFailedException {
    int ffi_return = Native.serverPublicParamsVerifySignatureJNI(contents, message, notarySignature.getInternalContentsForJNI());
    if (ffi_return == Native.FFI_RETURN_INPUT_ERROR) {
      throw new VerificationFailedException();
    }

    if (ffi_return != Native.FFI_RETURN_OK) {
      throw new ZkGroupError("FFI_RETURN!=OK");
    }
  }

  public byte[] serialize() {
    return contents.clone();
  }

}
