-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [signal_crypto]: function definitions
import Aeneas
import Libsignal.Code.Types
import Libsignal.Code.FunsPre
import Libsignal.Code.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.longLine false
set_option linter.style.setOption false
set_option linter.style.whitespace false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace signal_crypto


/-- [libsignal_core::address::{core::cmp::PartialEq<libsignal_core::address::ServiceIdKind> for libsignal_core::address::ServiceIdKind}::eq]:
    Source: 'rust/core/src/address.rs', lines 16:28-16:37
    Name pattern: [libsignal_core::address::{core::cmp::PartialEq<libsignal_core::address::ServiceIdKind, libsignal_core::address::ServiceIdKind>}::eq]
    Visibility: public -/
@[rust_fun
  "libsignal_core::address::{core::cmp::PartialEq<libsignal_core::address::ServiceIdKind, libsignal_core::address::ServiceIdKind>}::eq"]
def libsignal_core.address.ServiceIdKind.Insts.CoreCmpPartialEqServiceIdKind.eq
  (self : libsignal_core.address.ServiceIdKind)
  (other : libsignal_core.address.ServiceIdKind) :
  Result Bool
  := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- [libsignal_core::address::{core::convert::TryFrom<u8, derive_more::convert::try_from::TryFromReprError<u8>> for libsignal_core::address::ServiceIdKind}::try_from]:
    Source: 'rust/core/src/address.rs', lines 16:43-16:63
    Name pattern: [libsignal_core::address::{core::convert::TryFrom<libsignal_core::address::ServiceIdKind, u8, derive_more::convert::try_from::TryFromReprError<u8>>}::try_from]
    Visibility: public -/
@[rust_fun
  "libsignal_core::address::{core::convert::TryFrom<libsignal_core::address::ServiceIdKind, u8, derive_more::convert::try_from::TryFromReprError<u8>>}::try_from"]
def
  libsignal_core.address.ServiceIdKind.Insts.CoreConvertTryFromU8TryFromReprErrorU8.try_from
  (val : Std.U8) :
  Result (core.result.Result libsignal_core.address.ServiceIdKind
    (derive_more.convert.try_from.TryFromReprError Std.U8))
  := do
  match val with
  | 0#uscalar =>
    ok (core.result.Result.Ok libsignal_core.address.ServiceIdKind.Aci)
  | 1#uscalar =>
    ok (core.result.Result.Ok libsignal_core.address.ServiceIdKind.Pni)
  | _ =>
    let tfre ← derive_more.convert.try_from.TryFromReprError.new val
    ok (core.result.Result.Err tfre)

/-- [libsignal_core::address::{core::convert::From<libsignal_core::address::ServiceIdKind> for u8}::from]:
    Source: 'rust/core/src/address.rs', lines 27:4-27:41
    Name pattern: [libsignal_core::address::{core::convert::From<u8, libsignal_core::address::ServiceIdKind>}::from]
    Visibility: public -/
@[rust_fun
  "libsignal_core::address::{core::convert::From<u8, libsignal_core::address::ServiceIdKind>}::from"]
def U8.Insts.CoreConvertFromServiceIdKind.from
  (value : libsignal_core.address.ServiceIdKind) : Result Std.U8 := do
  let value1 := read_discriminant value
  ok (UScalar.cast .U8 value1)

/-- Trait implementation: [libsignal_core::address::{core::convert::From<libsignal_core::address::ServiceIdKind> for u8}]
    Source: 'rust/core/src/address.rs', lines 26:0-26:31
    Name pattern: [core::convert::From<u8, libsignal_core::address::ServiceIdKind>] -/
@[reducible, rust_trait_impl
  "core::convert::From<u8, libsignal_core::address::ServiceIdKind>"]
def U8.Insts.CoreConvertFromServiceIdKind : core.convert.From Std.U8
  libsignal_core.address.ServiceIdKind := {
  from_ := U8.Insts.CoreConvertFromServiceIdKind.from
}

/-- [libsignal_core::address::{libsignal_core::address::SpecificServiceId<KIND>}::from_uuid]:
    Source: 'rust/core/src/address.rs', lines 75:4-75:42
    Name pattern: [libsignal_core::address::{libsignal_core::address::SpecificServiceId<@KIND>}::from_uuid] -/
@[rust_fun
  "libsignal_core::address::{libsignal_core::address::SpecificServiceId<@KIND>}::from_uuid"]
def libsignal_core.address.SpecificServiceId.from_uuid
  (KIND : Std.U8) (uuid : uuid.Uuid) :
  Result (libsignal_core.address.SpecificServiceId KIND)
  := do
  ok { uuid }

/-- [libsignal_core::address::{core::convert::From<libsignal_core::address::SpecificServiceId<KIND>> for uuid::Uuid}::from]:
    Source: 'rust/core/src/address.rs', lines 149:4-149:51
    Name pattern: [libsignal_core::address::{core::convert::From<uuid::Uuid, libsignal_core::address::SpecificServiceId<@KIND>>}::from]
    Visibility: public -/
@[rust_fun
  "libsignal_core::address::{core::convert::From<uuid::Uuid, libsignal_core::address::SpecificServiceId<@KIND>>}::from"]
def uuid.Uuid.Insts.CoreConvertFromSpecificServiceId.from
  {KIND : Std.U8} (value : libsignal_core.address.SpecificServiceId KIND) :
  Result uuid.Uuid
  := do
  ok value.uuid

/-- Trait implementation: [libsignal_core::address::{core::convert::From<libsignal_core::address::SpecificServiceId<KIND>> for uuid::Uuid}]
    Source: 'rust/core/src/address.rs', lines 147:0-147:59
    Name pattern: [core::convert::From<uuid::Uuid, libsignal_core::address::SpecificServiceId<@KIND>>] -/
@[reducible, rust_trait_impl
  "core::convert::From<uuid::Uuid, libsignal_core::address::SpecificServiceId<@KIND>>"]
def uuid.Uuid.Insts.CoreConvertFromSpecificServiceId (KIND : Std.U8) :
  core.convert.From uuid.Uuid (libsignal_core.address.SpecificServiceId KIND)
  := {
  from_ := uuid.Uuid.Insts.CoreConvertFromSpecificServiceId.from
}

/-- [libsignal_core::address::{libsignal_core::address::ServiceId}::raw_uuid]:
    Source: 'rust/core/src/address.rs', lines 286:4-286:33
    Name pattern: [libsignal_core::address::{libsignal_core::address::ServiceId}::raw_uuid]
    Visibility: public -/
@[rust_fun
  "libsignal_core::address::{libsignal_core::address::ServiceId}::raw_uuid"]
def libsignal_core.address.ServiceId.raw_uuid
  (self : libsignal_core.address.ServiceId) : Result uuid.Uuid := do
  match self with
  | libsignal_core.address.ServiceId.Aci aci =>
    core.convert.IntoFrom.into
      (uuid.Uuid.Insts.CoreConvertFromSpecificServiceId 0#u8) aci
  | libsignal_core.address.ServiceId.Pni pni =>
    core.convert.IntoFrom.into
      (uuid.Uuid.Insts.CoreConvertFromSpecificServiceId 1#u8) pni

/-- [libsignal_core::address::{libsignal_core::address::ServiceId}::kind]:
    Source: 'rust/core/src/address.rs', lines 193:4-193:39
    Name pattern: [libsignal_core::address::{libsignal_core::address::ServiceId}::kind]
    Visibility: public -/
@[rust_fun
  "libsignal_core::address::{libsignal_core::address::ServiceId}::kind"]
def libsignal_core.address.ServiceId.kind
  (self : libsignal_core.address.ServiceId) :
  Result libsignal_core.address.ServiceIdKind
  := do
  match self with
  | libsignal_core.address.ServiceId.Aci _ =>
    ok libsignal_core.address.ServiceIdKind.Aci
  | libsignal_core.address.ServiceId.Pni _ =>
    ok libsignal_core.address.ServiceIdKind.Pni

/-- [libsignal_core::address::{libsignal_core::address::ServiceId}::service_id_fixed_width_binary]:
    Source: 'rust/core/src/address.rs', lines 214:4-214:81
    Name pattern: [libsignal_core::address::{libsignal_core::address::ServiceId}::service_id_fixed_width_binary]
    Visibility: public -/
@[rust_fun
  "libsignal_core::address::{libsignal_core::address::ServiceId}::service_id_fixed_width_binary"]
def libsignal_core.address.ServiceId.service_id_fixed_width_binary
  (self : libsignal_core.address.ServiceId) :
  Result (Array Std.U8 17#usize)
  := do
  let result := Array.repeat 17#usize 0#u8
  let sik ← libsignal_core.address.ServiceId.kind self
  let i ←
    core.convert.IntoFrom.into U8.Insts.CoreConvertFromServiceIdKind sik
  let result1 ← Array.update result 0#usize i
  let (s, index_mut_back) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeFromUsizeSlice Std.U8)) result1
      { start := 1#usize }
  let u ← libsignal_core.address.ServiceId.raw_uuid self
  let a ← uuid.Uuid.as_bytes u
  let s1 ← lift (Array.to_slice a)
  let s2 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s s1
  ok (index_mut_back s2)

/-- [libsignal_core::address::{libsignal_core::address::ServiceId}::service_id_binary]:
    Source: 'rust/core/src/address.rs', lines 204:4-204:46
    Name pattern: [libsignal_core::address::{libsignal_core::address::ServiceId}::service_id_binary]
    Visibility: public -/
@[rust_fun
  "libsignal_core::address::{libsignal_core::address::ServiceId}::service_id_binary"]
def libsignal_core.address.ServiceId.service_id_binary
  (self : libsignal_core.address.ServiceId) :
  Result (alloc.vec.Vec Std.U8)
  := do
  match self with
  | libsignal_core.address.ServiceId.Aci aci =>
    let a ← uuid.Uuid.as_bytes aci.uuid
    let s ← lift (Array.to_slice a)
    alloc.slice.Slice.to_vec core.clone.CloneU8 s
  | libsignal_core.address.ServiceId.Pni _ =>
    let a ←
      libsignal_core.address.ServiceId.service_id_fixed_width_binary self
    let s ← lift (Array.to_slice a)
    alloc.slice.Slice.to_vec core.clone.CloneU8 s

/-- [libsignal_core::address::{core::convert::From<uuid::Uuid> for libsignal_core::address::SpecificServiceId<KIND>}::from]:
    Source: 'rust/core/src/address.rs', lines 142:4-142:32
    Name pattern: [libsignal_core::address::{core::convert::From<libsignal_core::address::SpecificServiceId<@KIND>, uuid::Uuid>}::from]
    Visibility: public -/
@[rust_fun
  "libsignal_core::address::{core::convert::From<libsignal_core::address::SpecificServiceId<@KIND>, uuid::Uuid>}::from"]
def libsignal_core.address.SpecificServiceId.Insts.CoreConvertFromUuid.from
  (KIND : Std.U8) (value : uuid.Uuid) :
  Result (libsignal_core.address.SpecificServiceId KIND)
  := do
  libsignal_core.address.SpecificServiceId.from_uuid KIND value

/-- Trait implementation: [libsignal_core::address::{core::convert::From<uuid::Uuid> for libsignal_core::address::SpecificServiceId<KIND>}]
    Source: 'rust/core/src/address.rs', lines 140:0-140:59
    Name pattern: [core::convert::From<libsignal_core::address::SpecificServiceId<@KIND>, uuid::Uuid>] -/
@[reducible, rust_trait_impl
  "core::convert::From<libsignal_core::address::SpecificServiceId<@KIND>, uuid::Uuid>"]
def libsignal_core.address.SpecificServiceId.Insts.CoreConvertFromUuid (KIND :
  Std.U8) : core.convert.From (libsignal_core.address.SpecificServiceId KIND)
  uuid.Uuid := {
  from_ :=
    libsignal_core.address.SpecificServiceId.Insts.CoreConvertFromUuid.from
    KIND
}

/-- [libsignal_core::address::{libsignal_core::address::ServiceId}::parse_from_service_id_fixed_width_binary]:
    Source: 'rust/core/src/address.rs', lines 252:4-254:21
    Name pattern: [libsignal_core::address::{libsignal_core::address::ServiceId}::parse_from_service_id_fixed_width_binary]
    Visibility: public -/
@[rust_fun
  "libsignal_core::address::{libsignal_core::address::ServiceId}::parse_from_service_id_fixed_width_binary"]
def libsignal_core.address.ServiceId.parse_from_service_id_fixed_width_binary
  (bytes : Array Std.U8 17#usize) :
  Result (Option libsignal_core.address.ServiceId)
  := do
  let s ←
    core.array.Array.index (core.ops.index.IndexSlice
      (core.slice.index.SliceIndexRangeFromUsizeSlice Std.U8)) bytes
      { start := 1#usize }
  let r ← uuid.builder.Uuid.from_slice s
  let o ← core.result.Result.ok r
  let cf ←
    core.option.Option.Insts.CoreOpsTry_traitTryTOptionInfallible.branch o
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let i ← Array.index_usize bytes 0#usize
    let r1 ←
      libsignal_core.address.ServiceIdKind.Insts.CoreConvertTryFromU8TryFromReprErrorU8.try_from
        i
    let o1 ← core.result.Result.ok r1
    let cf1 ←
      core.option.Option.Insts.CoreOpsTry_traitTryTOptionInfallible.branch o1
    match cf1 with
    | core.ops.control_flow.ControlFlow.Continue val1 =>
      match val1 with
      | libsignal_core.address.ServiceIdKind.Aci =>
        let ssi ←
          core.convert.IntoFrom.into
            (libsignal_core.address.SpecificServiceId.Insts.CoreConvertFromUuid
            0#u8) val
        ok (some (libsignal_core.address.ServiceId.Aci ssi))
      | libsignal_core.address.ServiceIdKind.Pni =>
        let ssi ←
          core.convert.IntoFrom.into
            (libsignal_core.address.SpecificServiceId.Insts.CoreConvertFromUuid
            1#u8) val
        ok (some (libsignal_core.address.ServiceId.Pni ssi))
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
        libsignal_core.address.ServiceId residual
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
      libsignal_core.address.ServiceId residual

/-- [libsignal_core::address::{libsignal_core::address::ServiceId}::parse_from_service_id_binary]:
    Source: 'rust/core/src/address.rs', lines 232:4-232:69
    Name pattern: [libsignal_core::address::{libsignal_core::address::ServiceId}::parse_from_service_id_binary]
    Visibility: public -/
@[rust_fun
  "libsignal_core::address::{libsignal_core::address::ServiceId}::parse_from_service_id_binary"]
def libsignal_core.address.ServiceId.parse_from_service_id_binary
  (bytes : Slice Std.U8) :
  Result (Option libsignal_core.address.ServiceId)
  := do
  let i := Slice.len bytes
  match i.val with
  | 16 =>
    let r ← uuid.builder.Uuid.from_slice bytes
    let o ← core.result.Result.ok r
    let cf ←
      core.option.Option.Insts.CoreOpsTry_traitTryTOptionInfallible.branch o
    match cf with
    | core.ops.control_flow.ControlFlow.Continue val =>
      let ssi ←
        core.convert.IntoFrom.into
          (libsignal_core.address.SpecificServiceId.Insts.CoreConvertFromUuid
          0#u8) val
      ok (some (libsignal_core.address.ServiceId.Aci ssi))
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
        libsignal_core.address.ServiceId residual
  | 17 =>
    let r ← core.array.TryFromSharedArraySlice.try_from 17#usize bytes
    let a ←
      core.result.Result.expect core.fmt.DebugTryFromSliceError r (toStr
        "already measured")
    let o ←
      libsignal_core.address.ServiceId.parse_from_service_id_fixed_width_binary
        a
    let cf ←
      core.option.Option.Insts.CoreOpsTry_traitTryTOptionInfallible.branch o
    match cf with
    | core.ops.control_flow.ControlFlow.Continue val =>
      let sik ← libsignal_core.address.ServiceId.kind val
      let b ←
        libsignal_core.address.ServiceIdKind.Insts.CoreCmpPartialEqServiceIdKind.eq
          sik libsignal_core.address.ServiceIdKind.Aci
      if b
      then ok none
      else ok (some val)
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
        libsignal_core.address.ServiceId residual
  | _ => ok none

/-- [libsignal_core::address::MAX_VALID_DEVICE_ID]
    Source: 'rust/core/src/address.rs', lines 715:0-715:29
    Name pattern: [libsignal_core::address::MAX_VALID_DEVICE_ID] -/
@[global_simps, irreducible, rust_const
  "libsignal_core::address::MAX_VALID_DEVICE_ID"]
def libsignal_core.address.MAX_VALID_DEVICE_ID : Std.U8 := 127#u8

/-- [libsignal_core::address::{libsignal_core::address::DeviceId}::new_nonzero]:
    Source: 'rust/core/src/address.rs', lines 706:4-706:76
    Name pattern: [libsignal_core::address::{libsignal_core::address::DeviceId}::new_nonzero]
    Visibility: public -/
@[rust_fun
  "libsignal_core::address::{libsignal_core::address::DeviceId}::new_nonzero"]
def libsignal_core.address.DeviceId.new_nonzero
  (id : core.num.nonzero.NonZero
  U8.Insts.CoreNumNonzeroZeroablePrimitiveNonZeroU8Inner) :
  Result (core.result.Result libsignal_core.address.DeviceId
    libsignal_core.address.InvalidDeviceId)
  := do
  let i ←
    core.num.nonzero.NonZero.get
      U8.Insts.CoreNumNonzeroZeroablePrimitiveNonZeroU8Inner id
  if i <= libsignal_core.address.MAX_VALID_DEVICE_ID
  then ok (core.result.Result.Ok { id })
  else ok (core.result.Result.Err ())

/-- [libsignal_core::curve::{libsignal_core::curve::KeyType}::value]:
    Source: 'rust/core/src/curve.rs', lines 26:4-26:25
    Name pattern: [libsignal_core::curve::{libsignal_core::curve::KeyType}::value] -/
@[rust_fun "libsignal_core::curve::{libsignal_core::curve::KeyType}::value"]
def libsignal_core.curve.KeyType.value
  (self : libsignal_core.curve.KeyType) : Result Std.U8 := do
  ok 5#u8

/-- [libsignal_core::curve::{libsignal_core::curve::PublicKey}::key_type]:
    Source: 'rust/core/src/curve.rs', lines 159:4-159:37
    Name pattern: [libsignal_core::curve::{libsignal_core::curve::PublicKey}::key_type]
    Visibility: public -/
@[rust_fun
  "libsignal_core::curve::{libsignal_core::curve::PublicKey}::key_type"]
def libsignal_core.curve.PublicKey.key_type
  (self : libsignal_core.curve.PublicKey) :
  Result libsignal_core.curve.KeyType
  := do
  ok libsignal_core.curve.KeyType.Djb

/-- [libsignal_core::curve::{libsignal_core::curve::PublicKey}::scalar_is_in_range]:
    Source: 'rust/core/src/curve.rs', lines 176:4-176:40
    Name pattern: [libsignal_core::curve::{libsignal_core::curve::PublicKey}::scalar_is_in_range] -/
@[rust_fun
  "libsignal_core::curve::{libsignal_core::curve::PublicKey}::scalar_is_in_range"]
def libsignal_core.curve.PublicKey.scalar_is_in_range
  (self : libsignal_core.curve.PublicKey) : Result Bool := do
  let ⟨ k ⟩ := self.key
  let i ← Array.index_usize k 31#usize
  let i1 ← lift (i &&& 128#u8)
  let b ←
    if i1 != 0#u8
    then ok true
    else
      let i2 ← Array.index_usize k 0#usize
      let i3 ← lift (core.num.U8.wrapping_sub 0#u8 19#u8)
      if i2 >= i3
      then
        let s ←
          core.array.Array.index (core.ops.index.IndexSlice
            (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) k
            { start := 1#usize, «end» := 31#usize }
        let a := Array.repeat 30#usize 255#u8
        let b1 ←
          Slice.Insts.CoreCmpPartialEqArray.eq core.cmp.PartialEqU8 s a
        if b1
        then ok (i == 127#u8)
        else ok false
      else ok false
  ok (¬ b)

/-- [libsignal_core::e164::{libsignal_core::e164::E164}::from_be_bytes::{core::ops::function::FnOnce<(core::num::nonzero::NonZero<u64, core::num::niche_types::NonZeroU64Inner>[core::num::nonzero::{core::num::nonzero::ZeroablePrimitive<core::num::niche_types::NonZeroU64Inner> for u64}]), libsignal_core::e164::E164> for libsignal_core::e164::{libsignal_core::e164::E164}::from_be_bytes::closure}::call_once]:
    Source: 'rust/core/src/e164.rs', lines 25:55-25:62
    Name pattern: [libsignal_core::e164::{libsignal_core::e164::E164}::from_be_bytes::{core::ops::function::FnOnce<libsignal_core::e164::{libsignal_core::e164::E164}::from_be_bytes::closure, (core::num::nonzero::NonZero<u64, core::num::niche_types::NonZeroU64Inner>), libsignal_core::e164::E164>}::call_once] -/
@[rust_fun
  "libsignal_core::e164::{libsignal_core::e164::E164}::from_be_bytes::{core::ops::function::FnOnce<libsignal_core::e164::{libsignal_core::e164::E164}::from_be_bytes::closure, (core::num::nonzero::NonZero<u64, core::num::niche_types::NonZeroU64Inner>), libsignal_core::e164::E164>}::call_once"]
def
  libsignal_core.e164.E164.from_be_bytes.closure.Insts.CoreOpsFunctionFnOnceTupleNonZeroU64NonZeroU64InnerE164.call_once
  (c : libsignal_core.e164.E164.from_be_bytes.closure)
  (tupled_args : core.num.nonzero.NonZero
  U64.Insts.CoreNumNonzeroZeroablePrimitiveNonZeroU64Inner) :
  Result libsignal_core.e164.E164
  := do
  ok { inner := tupled_args }

/-- Trait implementation: [libsignal_core::e164::{libsignal_core::e164::E164}::from_be_bytes::{core::ops::function::FnOnce<(core::num::nonzero::NonZero<u64, core::num::niche_types::NonZeroU64Inner>[core::num::nonzero::{core::num::nonzero::ZeroablePrimitive<core::num::niche_types::NonZeroU64Inner> for u64}]), libsignal_core::e164::E164> for libsignal_core::e164::{libsignal_core::e164::E164}::from_be_bytes::closure}]
    Source: 'rust/core/src/e164.rs', lines 25:55-25:62
    Name pattern: [core::ops::function::FnOnce<libsignal_core::e164::{libsignal_core::e164::E164}::from_be_bytes::closure, (core::num::nonzero::NonZero<u64, core::num::niche_types::NonZeroU64Inner>), libsignal_core::e164::E164>] -/
@[reducible, rust_trait_impl
  "core::ops::function::FnOnce<libsignal_core::e164::{libsignal_core::e164::E164}::from_be_bytes::closure, (core::num::nonzero::NonZero<u64, core::num::niche_types::NonZeroU64Inner>), libsignal_core::e164::E164>"]
def
  libsignal_core.e164.E164.from_be_bytes.closure.Insts.CoreOpsFunctionFnOnceTupleNonZeroU64NonZeroU64InnerE164
  : core.ops.function.FnOnce libsignal_core.e164.E164.from_be_bytes.closure
  (core.num.nonzero.NonZero
  U64.Insts.CoreNumNonzeroZeroablePrimitiveNonZeroU64Inner)
  libsignal_core.e164.E164 := {
  call_once :=
    libsignal_core.e164.E164.from_be_bytes.closure.Insts.CoreOpsFunctionFnOnceTupleNonZeroU64NonZeroU64InnerE164.call_once
}

/-- [libsignal_core::version::VERSION]
    Source: 'rust/core/src/version.rs', lines 8:0-8:23
    Name pattern: [libsignal_core::version::VERSION]
    Visibility: public -/
@[global_simps, irreducible, rust_const "libsignal_core::version::VERSION"]
def libsignal_core.version.VERSION : Str := toStr "0.90.0"

/-- Trait implementation: [subtle::{subtle::ConstantTimeEq for u8}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/subtle-2.6.1/src/lib.rs', lines 346:8-346:36
    Name pattern: [subtle::ConstantTimeEq<u8>] -/
@[reducible, rust_trait_impl "subtle::ConstantTimeEq<u8>"]
def U8.Insts.SubtleConstantTimeEq : subtle.ConstantTimeEq Std.U8 := {
  ct_eq := U8.Insts.SubtleConstantTimeEq.ct_eq
}

/-- Trait implementation: [typenum::bit::{core::clone::Clone for typenum::bit::B0}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/bit.rs', lines 18:41-18:46
    Name pattern: [core::clone::Clone<typenum::bit::B0>] -/
@[reducible, rust_trait_impl "core::clone::Clone<typenum::bit::B0>"]
def typenum.bit.B0.Insts.CoreCloneClone : core.clone.Clone typenum.bit.B0 := {
  clone := typenum.bit.B0.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [typenum::bit::{core::marker::Copy for typenum::bit::B0}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/bit.rs', lines 18:48-18:52
    Name pattern: [core::marker::Copy<typenum::bit::B0>] -/
@[reducible, rust_trait_impl "core::marker::Copy<typenum::bit::B0>"]
def typenum.bit.B0.Insts.CoreMarkerCopy : core.marker.Copy typenum.bit.B0 := {
  cloneInst := typenum.bit.B0.Insts.CoreCloneClone
}

/-- Trait implementation: [typenum::bit::{core::default::Default for typenum::bit::B0}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/bit.rs', lines 18:67-18:74
    Name pattern: [core::default::Default<typenum::bit::B0>] -/
@[reducible, rust_trait_impl "core::default::Default<typenum::bit::B0>"]
def typenum.bit.B0.Insts.CoreDefaultDefault : core.default.Default
  typenum.bit.B0 := {
  default := typenum.bit.B0.Insts.CoreDefaultDefault.default
}

/-- Trait implementation: [typenum::bit::{core::clone::Clone for typenum::bit::B1}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/bit.rs', lines 31:41-31:46
    Name pattern: [core::clone::Clone<typenum::bit::B1>] -/
@[reducible, rust_trait_impl "core::clone::Clone<typenum::bit::B1>"]
def typenum.bit.B1.Insts.CoreCloneClone : core.clone.Clone typenum.bit.B1 := {
  clone := typenum.bit.B1.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [typenum::bit::{core::marker::Copy for typenum::bit::B1}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/bit.rs', lines 31:48-31:52
    Name pattern: [core::marker::Copy<typenum::bit::B1>] -/
@[reducible, rust_trait_impl "core::marker::Copy<typenum::bit::B1>"]
def typenum.bit.B1.Insts.CoreMarkerCopy : core.marker.Copy typenum.bit.B1 := {
  cloneInst := typenum.bit.B1.Insts.CoreCloneClone
}

/-- Trait implementation: [typenum::bit::{core::default::Default for typenum::bit::B1}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/bit.rs', lines 31:67-31:74
    Name pattern: [core::default::Default<typenum::bit::B1>] -/
@[reducible, rust_trait_impl "core::default::Default<typenum::bit::B1>"]
def typenum.bit.B1.Insts.CoreDefaultDefault : core.default.Default
  typenum.bit.B1 := {
  default := typenum.bit.B1.Insts.CoreDefaultDefault.default
}

/-- Trait implementation: [typenum::sealed::{typenum::sealed::Sealed for typenum::bit::B0}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/lib.rs', lines 156:4-156:22
    Name pattern: [typenum::sealed::Sealed<typenum::bit::B0>] -/
@[reducible, rust_trait_impl "typenum::sealed::Sealed<typenum::bit::B0>"]
def typenum.bit.B0.Insts.TypenumSealedSealed : typenum.sealed.Sealed
  typenum.bit.B0 := {
}

/-- Trait implementation: [typenum::bit::{typenum::marker_traits::Bit for typenum::bit::B0}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/bit.rs', lines 43:0-43:15
    Name pattern: [typenum::marker_traits::Bit<typenum::bit::B0>] -/
@[reducible, rust_trait_impl "typenum::marker_traits::Bit<typenum::bit::B0>"]
def typenum.bit.B0.Insts.TypenumMarker_traitsBit : typenum.marker_traits.Bit
  typenum.bit.B0 := {
  U8 := typenum.bit.B0.Insts.TypenumMarker_traitsBit.U8
  BOOL := typenum.bit.B0.Insts.TypenumMarker_traitsBit.BOOL
  sealedSealedInst := typenum.bit.B0.Insts.TypenumSealedSealed
  coremarkerCopyInst := typenum.bit.B0.Insts.CoreMarkerCopy
  coredefaultDefaultInst := typenum.bit.B0.Insts.CoreDefaultDefault
  new := typenum.bit.B0.Insts.TypenumMarker_traitsBit.new
  to_u8 := typenum.bit.B0.Insts.TypenumMarker_traitsBit.to_u8
  to_bool := typenum.bit.B0.Insts.TypenumMarker_traitsBit.to_bool
}

/-- Trait implementation: [typenum::sealed::{typenum::sealed::Sealed for typenum::bit::B1}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/lib.rs', lines 157:4-157:22
    Name pattern: [typenum::sealed::Sealed<typenum::bit::B1>] -/
@[reducible, rust_trait_impl "typenum::sealed::Sealed<typenum::bit::B1>"]
def typenum.bit.B1.Insts.TypenumSealedSealed : typenum.sealed.Sealed
  typenum.bit.B1 := {
}

/-- Trait implementation: [typenum::bit::{typenum::marker_traits::Bit for typenum::bit::B1}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/bit.rs', lines 61:0-61:15
    Name pattern: [typenum::marker_traits::Bit<typenum::bit::B1>] -/
@[reducible, rust_trait_impl "typenum::marker_traits::Bit<typenum::bit::B1>"]
def typenum.bit.B1.Insts.TypenumMarker_traitsBit : typenum.marker_traits.Bit
  typenum.bit.B1 := {
  U8 := typenum.bit.B1.Insts.TypenumMarker_traitsBit.U8
  BOOL := typenum.bit.B1.Insts.TypenumMarker_traitsBit.BOOL
  sealedSealedInst := typenum.bit.B1.Insts.TypenumSealedSealed
  coremarkerCopyInst := typenum.bit.B1.Insts.CoreMarkerCopy
  coredefaultDefaultInst := typenum.bit.B1.Insts.CoreDefaultDefault
  new := typenum.bit.B1.Insts.TypenumMarker_traitsBit.new
  to_u8 := typenum.bit.B1.Insts.TypenumMarker_traitsBit.to_u8
  to_bool := typenum.bit.B1.Insts.TypenumMarker_traitsBit.to_bool
}

/-- Trait implementation: [typenum::sealed::{typenum::sealed::Sealed for typenum::uint::UTerm}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/lib.rs', lines 159:4-159:25
    Name pattern: [typenum::sealed::Sealed<typenum::uint::UTerm>] -/
@[reducible, rust_trait_impl "typenum::sealed::Sealed<typenum::uint::UTerm>"]
def typenum.uint.UTerm.Insts.TypenumSealedSealed : typenum.sealed.Sealed
  typenum.uint.UTerm := {
}

/-- Trait implementation: [typenum::sealed::{typenum::sealed::Sealed for typenum::uint::UInt<U, B>}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/lib.rs', lines 160:4-160:51
    Name pattern: [typenum::sealed::Sealed<typenum::uint::UInt<@U, @B>>] -/
@[reducible, rust_trait_impl
  "typenum::sealed::Sealed<typenum::uint::UInt<@U, @B>>"]
def typenum.uint.UInt.Insts.TypenumSealedSealed {U : Type} {B : Type}
  (marker_traitsUnsignedInst : typenum.marker_traits.Unsigned U)
  (marker_traitsBitInst : typenum.marker_traits.Bit B) : typenum.sealed.Sealed
  (typenum.uint.UInt U B) := {
}

/-- Trait implementation: [typenum::uint::{core::clone::Clone for typenum::uint::UTerm}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/uint.rs', lines 48:41-48:46
    Name pattern: [core::clone::Clone<typenum::uint::UTerm>] -/
@[reducible, rust_trait_impl "core::clone::Clone<typenum::uint::UTerm>"]
def typenum.uint.UTerm.Insts.CoreCloneClone : core.clone.Clone
  typenum.uint.UTerm := {
  clone := typenum.uint.UTerm.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [typenum::uint::{core::marker::Copy for typenum::uint::UTerm}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/uint.rs', lines 48:48-48:52
    Name pattern: [core::marker::Copy<typenum::uint::UTerm>] -/
@[reducible, rust_trait_impl "core::marker::Copy<typenum::uint::UTerm>"]
def typenum.uint.UTerm.Insts.CoreMarkerCopy : core.marker.Copy
  typenum.uint.UTerm := {
  cloneInst := typenum.uint.UTerm.Insts.CoreCloneClone
}

/-- Trait implementation: [typenum::uint::{core::default::Default for typenum::uint::UTerm}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/uint.rs', lines 48:67-48:74
    Name pattern: [core::default::Default<typenum::uint::UTerm>] -/
@[reducible, rust_trait_impl "core::default::Default<typenum::uint::UTerm>"]
def typenum.uint.UTerm.Insts.CoreDefaultDefault : core.default.Default
  typenum.uint.UTerm := {
  default := typenum.uint.UTerm.Insts.CoreDefaultDefault.default
}

/-- Trait implementation: [typenum::uint::{typenum::marker_traits::Unsigned for typenum::uint::UTerm}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/uint.rs', lines 60:0-60:23
    Name pattern: [typenum::marker_traits::Unsigned<typenum::uint::UTerm>] -/
@[reducible, rust_trait_impl
  "typenum::marker_traits::Unsigned<typenum::uint::UTerm>"]
def typenum.uint.UTerm.Insts.TypenumMarker_traitsUnsigned :
  typenum.marker_traits.Unsigned typenum.uint.UTerm := {
  U8 := typenum.uint.UTerm.Insts.TypenumMarker_traitsUnsigned.U8
  U16 := typenum.uint.UTerm.Insts.TypenumMarker_traitsUnsigned.U16
  U32 := typenum.uint.UTerm.Insts.TypenumMarker_traitsUnsigned.U32
  U64 := typenum.uint.UTerm.Insts.TypenumMarker_traitsUnsigned.U64
  USIZE := typenum.uint.UTerm.Insts.TypenumMarker_traitsUnsigned.USIZE
  I8 := typenum.uint.UTerm.Insts.TypenumMarker_traitsUnsigned.I8
  I16 := typenum.uint.UTerm.Insts.TypenumMarker_traitsUnsigned.I16
  I32 := typenum.uint.UTerm.Insts.TypenumMarker_traitsUnsigned.I32
  I64 := typenum.uint.UTerm.Insts.TypenumMarker_traitsUnsigned.I64
  ISIZE := typenum.uint.UTerm.Insts.TypenumMarker_traitsUnsigned.ISIZE
  sealedSealedInst := typenum.uint.UTerm.Insts.TypenumSealedSealed
  coremarkerCopyInst := typenum.uint.UTerm.Insts.CoreMarkerCopy
  coredefaultDefaultInst := typenum.uint.UTerm.Insts.CoreDefaultDefault
  to_u8 := typenum.uint.UTerm.Insts.TypenumMarker_traitsUnsigned.to_u8
  to_u16 := typenum.uint.UTerm.Insts.TypenumMarker_traitsUnsigned.to_u16
  to_u32 := typenum.uint.UTerm.Insts.TypenumMarker_traitsUnsigned.to_u32
  to_u64 := typenum.uint.UTerm.Insts.TypenumMarker_traitsUnsigned.to_u64
  to_usize := typenum.uint.UTerm.Insts.TypenumMarker_traitsUnsigned.to_usize
  to_i8 := typenum.uint.UTerm.Insts.TypenumMarker_traitsUnsigned.to_i8
  to_i16 := typenum.uint.UTerm.Insts.TypenumMarker_traitsUnsigned.to_i16
  to_i32 := typenum.uint.UTerm.Insts.TypenumMarker_traitsUnsigned.to_i32
  to_i64 := typenum.uint.UTerm.Insts.TypenumMarker_traitsUnsigned.to_i64
  to_isize := typenum.uint.UTerm.Insts.TypenumMarker_traitsUnsigned.to_isize
}

/-- Trait implementation: [typenum::uint::{core::clone::Clone for typenum::uint::UInt<U, B>}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/uint.rs', lines 146:41-146:46
    Name pattern: [core::clone::Clone<typenum::uint::UInt<@U, @B>>] -/
@[reducible, rust_trait_impl "core::clone::Clone<typenum::uint::UInt<@U, @B>>"]
def typenum.uint.UInt.Insts.CoreCloneClone {U : Type} {B : Type}
  (corecloneCloneInst : core.clone.Clone U) (corecloneCloneInst1 :
  core.clone.Clone B) : core.clone.Clone (typenum.uint.UInt U B) := {
  clone := typenum.uint.UInt.Insts.CoreCloneClone.clone corecloneCloneInst
    corecloneCloneInst1
}

/-- Trait implementation: [typenum::uint::{core::marker::Copy for typenum::uint::UInt<U, B>}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/uint.rs', lines 146:48-146:52
    Name pattern: [core::marker::Copy<typenum::uint::UInt<@U, @B>>] -/
@[reducible, rust_trait_impl "core::marker::Copy<typenum::uint::UInt<@U, @B>>"]
def typenum.uint.UInt.Insts.CoreMarkerCopy {U : Type} {B : Type}
  (coremarkerCopyInst : core.marker.Copy U) (coremarkerCopyInst1 :
  core.marker.Copy B) : core.marker.Copy (typenum.uint.UInt U B) := {
  cloneInst := typenum.uint.UInt.Insts.CoreCloneClone
    coremarkerCopyInst.cloneInst coremarkerCopyInst1.cloneInst
}

/-- Trait implementation: [typenum::uint::{core::default::Default for typenum::uint::UInt<U, B>}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/uint.rs', lines 146:67-146:74
    Name pattern: [core::default::Default<typenum::uint::UInt<@U, @B>>] -/
@[reducible, rust_trait_impl
  "core::default::Default<typenum::uint::UInt<@U, @B>>"]
def typenum.uint.UInt.Insts.CoreDefaultDefault {U : Type} {B : Type}
  (coredefaultDefaultInst : core.default.Default U) (coredefaultDefaultInst1 :
  core.default.Default B) : core.default.Default (typenum.uint.UInt U B) := {
  default := typenum.uint.UInt.Insts.CoreDefaultDefault.default
    coredefaultDefaultInst coredefaultDefaultInst1
}

/-- Trait implementation: [typenum::uint::{typenum::marker_traits::Unsigned for typenum::uint::UInt<U, B>}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/uint.rs', lines 163:0-163:49
    Name pattern: [typenum::marker_traits::Unsigned<typenum::uint::UInt<@U, @B>>] -/
@[reducible, rust_trait_impl
  "typenum::marker_traits::Unsigned<typenum::uint::UInt<@U, @B>>"]
def typenum.uint.UInt.Insts.TypenumMarker_traitsUnsigned {U : Type} {B : Type}
  (marker_traitsUnsignedInst : typenum.marker_traits.Unsigned U)
  (marker_traitsBitInst : typenum.marker_traits.Bit B) :
  typenum.marker_traits.Unsigned (typenum.uint.UInt U B) := {
  U8 := typenum.uint.UInt.Insts.TypenumMarker_traitsUnsigned.U8
    marker_traitsUnsignedInst marker_traitsBitInst
  U16 := typenum.uint.UInt.Insts.TypenumMarker_traitsUnsigned.U16
    marker_traitsUnsignedInst marker_traitsBitInst
  U32 := typenum.uint.UInt.Insts.TypenumMarker_traitsUnsigned.U32
    marker_traitsUnsignedInst marker_traitsBitInst
  U64 := typenum.uint.UInt.Insts.TypenumMarker_traitsUnsigned.U64
    marker_traitsUnsignedInst marker_traitsBitInst
  USIZE := typenum.uint.UInt.Insts.TypenumMarker_traitsUnsigned.USIZE
    marker_traitsUnsignedInst marker_traitsBitInst
  I8 := typenum.uint.UInt.Insts.TypenumMarker_traitsUnsigned.I8
    marker_traitsUnsignedInst marker_traitsBitInst
  I16 := typenum.uint.UInt.Insts.TypenumMarker_traitsUnsigned.I16
    marker_traitsUnsignedInst marker_traitsBitInst
  I32 := typenum.uint.UInt.Insts.TypenumMarker_traitsUnsigned.I32
    marker_traitsUnsignedInst marker_traitsBitInst
  I64 := typenum.uint.UInt.Insts.TypenumMarker_traitsUnsigned.I64
    marker_traitsUnsignedInst marker_traitsBitInst
  ISIZE := typenum.uint.UInt.Insts.TypenumMarker_traitsUnsigned.ISIZE
    marker_traitsUnsignedInst marker_traitsBitInst
  sealedSealedInst := typenum.uint.UInt.Insts.TypenumSealedSealed
    marker_traitsUnsignedInst marker_traitsBitInst
  coremarkerCopyInst := typenum.uint.UInt.Insts.CoreMarkerCopy
    marker_traitsUnsignedInst.coremarkerCopyInst
    marker_traitsBitInst.coremarkerCopyInst
  coredefaultDefaultInst := typenum.uint.UInt.Insts.CoreDefaultDefault
    marker_traitsUnsignedInst.coredefaultDefaultInst
    marker_traitsBitInst.coredefaultDefaultInst
  to_u8 := typenum.uint.UInt.Insts.TypenumMarker_traitsUnsigned.to_u8
    marker_traitsUnsignedInst marker_traitsBitInst
  to_u16 := typenum.uint.UInt.Insts.TypenumMarker_traitsUnsigned.to_u16
    marker_traitsUnsignedInst marker_traitsBitInst
  to_u32 := typenum.uint.UInt.Insts.TypenumMarker_traitsUnsigned.to_u32
    marker_traitsUnsignedInst marker_traitsBitInst
  to_u64 := typenum.uint.UInt.Insts.TypenumMarker_traitsUnsigned.to_u64
    marker_traitsUnsignedInst marker_traitsBitInst
  to_usize := typenum.uint.UInt.Insts.TypenumMarker_traitsUnsigned.to_usize
    marker_traitsUnsignedInst marker_traitsBitInst
  to_i8 := typenum.uint.UInt.Insts.TypenumMarker_traitsUnsigned.to_i8
    marker_traitsUnsignedInst marker_traitsBitInst
  to_i16 := typenum.uint.UInt.Insts.TypenumMarker_traitsUnsigned.to_i16
    marker_traitsUnsignedInst marker_traitsBitInst
  to_i32 := typenum.uint.UInt.Insts.TypenumMarker_traitsUnsigned.to_i32
    marker_traitsUnsignedInst marker_traitsBitInst
  to_i64 := typenum.uint.UInt.Insts.TypenumMarker_traitsUnsigned.to_i64
    marker_traitsUnsignedInst marker_traitsBitInst
  to_isize := typenum.uint.UInt.Insts.TypenumMarker_traitsUnsigned.to_isize
    marker_traitsUnsignedInst marker_traitsBitInst
}

/-- [signal_crypto::aes_ctr::{signal_crypto::aes_ctr::Aes256Ctr32}::NONCE_SIZE]
    Source: 'rust/crypto/src/aes_ctr.rs', lines 19:4-19:95
    Visibility: public -/
@[global_simps, irreducible]
def aes_ctr.Aes256Ctr32.NONCE_SIZE : Result Std.Usize := do
  let i ←
    typenum.uint.UInt.Insts.TypenumMarker_traitsUnsigned.USIZE
      (typenum.uint.UInt.Insts.TypenumMarker_traitsUnsigned
      (typenum.uint.UInt.Insts.TypenumMarker_traitsUnsigned
      (typenum.uint.UInt.Insts.TypenumMarker_traitsUnsigned
      (typenum.uint.UInt.Insts.TypenumMarker_traitsUnsigned
      typenum.uint.UTerm.Insts.TypenumMarker_traitsUnsigned
      typenum.bit.B1.Insts.TypenumMarker_traitsBit)
      typenum.bit.B0.Insts.TypenumMarker_traitsBit)
      typenum.bit.B0.Insts.TypenumMarker_traitsBit)
      typenum.bit.B0.Insts.TypenumMarker_traitsBit)
      typenum.bit.B0.Insts.TypenumMarker_traitsBit
  i - 4#usize

/-- [signal_crypto::aes_gcm::TAG_SIZE]
    Source: 'rust/crypto/src/aes_gcm.rs', lines 15:0-15:31
    Visibility: public -/
@[global_simps, irreducible] def aes_gcm.TAG_SIZE : Std.Usize := 16#usize

/-- [signal_crypto::aes_gcm::NONCE_SIZE]
    Source: 'rust/crypto/src/aes_gcm.rs', lines 16:0-16:33
    Visibility: public -/
@[global_simps, irreducible] def aes_gcm.NONCE_SIZE : Std.Usize := 12#usize

/-- [signal_crypto::aes_gcm::{core::clone::Clone for signal_crypto::aes_gcm::GcmGhash}::clone]:
    Source: 'rust/crypto/src/aes_gcm.rs', lines 18:9-18:14
    Visibility: public -/
def aes_gcm.GcmGhash.Insts.CoreCloneClone.clone
  (self : aes_gcm.GcmGhash) : Result aes_gcm.GcmGhash := do
  let g ← ghash.GHash.Insts.CoreCloneClone.clone self.ghash
  let a ← core.array.CloneArray.clone core.clone.CloneU8 self.ghash_pad
  let a1 ← core.array.CloneArray.clone core.clone.CloneU8 self.msg_buf
  let i ← lift (core.clone.impls.CloneUsize.clone self.msg_buf_offset)
  let i1 ← lift (core.clone.impls.CloneUsize.clone self.ad_len)
  let i2 ← lift (core.clone.impls.CloneUsize.clone self.msg_len)
  ok
    {
      ghash := g,
      ghash_pad := a,
      msg_buf := a1,
      msg_buf_offset := i,
      ad_len := i1,
      msg_len := i2
    }

/-- [signal_crypto::aes_gcm::{signal_crypto::aes_gcm::Aes256GcmEncryption}::TAG_SIZE]
    Source: 'rust/crypto/src/aes_gcm.rs', lines 139:4-139:41
    Visibility: public -/
@[global_simps, irreducible]
def aes_gcm.Aes256GcmEncryption.TAG_SIZE : Std.Usize := aes_gcm.TAG_SIZE

/-- [signal_crypto::aes_gcm::{signal_crypto::aes_gcm::Aes256GcmEncryption}::NONCE_SIZE]
    Source: 'rust/crypto/src/aes_gcm.rs', lines 140:4-140:45
    Visibility: public -/
@[global_simps, irreducible]
def aes_gcm.Aes256GcmEncryption.NONCE_SIZE : Std.Usize := aes_gcm.NONCE_SIZE

/-- [signal_crypto::aes_gcm::{signal_crypto::aes_gcm::Aes256GcmEncryption}::encrypt]:
    Source: 'rust/crypto/src/aes_gcm.rs', lines 147:4-150:5
    Visibility: public -/
def aes_gcm.Aes256GcmEncryption.encrypt
  (self : aes_gcm.Aes256GcmEncryption) (buf : Slice Std.U8) :
  Result (aes_gcm.Aes256GcmEncryption × (Slice Std.U8))
  := do
  let (ac, buf1) ← aes_ctr.Aes256Ctr32.process self.ctr buf
  let gg ← aes_gcm.GcmGhash.update self.ghash buf1
  ok ({ ctr := ac, ghash := gg }, buf1)

/-- [signal_crypto::aes_gcm::{signal_crypto::aes_gcm::Aes256GcmEncryption}::compute_tag]:
    Source: 'rust/crypto/src/aes_gcm.rs', lines 152:4-154:5
    Visibility: public -/
def aes_gcm.Aes256GcmEncryption.compute_tag
  (self : aes_gcm.Aes256GcmEncryption) : Result (Array Std.U8 16#usize) := do
  aes_gcm.GcmGhash.finalize self.ghash

/-- [signal_crypto::aes_gcm::{signal_crypto::aes_gcm::Aes256GcmDecryption}::TAG_SIZE]
    Source: 'rust/crypto/src/aes_gcm.rs', lines 163:4-163:41
    Visibility: public -/
@[global_simps, irreducible]
def aes_gcm.Aes256GcmDecryption.TAG_SIZE : Std.Usize := aes_gcm.TAG_SIZE

/-- [signal_crypto::aes_gcm::{signal_crypto::aes_gcm::Aes256GcmDecryption}::NONCE_SIZE]
    Source: 'rust/crypto/src/aes_gcm.rs', lines 164:4-164:45
    Visibility: public -/
@[global_simps, irreducible]
def aes_gcm.Aes256GcmDecryption.NONCE_SIZE : Std.Usize := aes_gcm.NONCE_SIZE

/-- [signal_crypto::aes_gcm::{signal_crypto::aes_gcm::Aes256GcmDecryption}::decrypt]:
    Source: 'rust/crypto/src/aes_gcm.rs', lines 171:4-174:5
    Visibility: public -/
def aes_gcm.Aes256GcmDecryption.decrypt
  (self : aes_gcm.Aes256GcmDecryption) (buf : Slice Std.U8) :
  Result (aes_gcm.Aes256GcmDecryption × (Slice Std.U8))
  := do
  let gg ← aes_gcm.GcmGhash.update self.ghash buf
  let (ac, buf1) ← aes_ctr.Aes256Ctr32.process self.ctr buf
  ok ({ ctr := ac, ghash := gg }, buf1)

/-- [signal_crypto::aes_gcm::{signal_crypto::aes_gcm::Aes256GcmDecryption}::verify_tag]:
    Source: 'rust/crypto/src/aes_gcm.rs', lines 176:4-190:5
    Visibility: public -/
def aes_gcm.Aes256GcmDecryption.verify_tag
  (self : aes_gcm.Aes256GcmDecryption) (tag : Slice Std.U8) :
  Result (core.result.Result Unit error.Error)
  := do
  let i := Slice.len tag
  if i != aes_gcm.TAG_SIZE
  then ok (core.result.Result.Err error.Error.InvalidTag)
  else
    let computed_tag ← aes_gcm.GcmGhash.finalize self.ghash
    let s ← lift (Array.to_slice computed_tag)
    let tag_ok ←
      Slice.Insts.SubtleConstantTimeEq.ct_eq U8.Insts.SubtleConstantTimeEq tag
        s
    let b ← Bool.Insts.CoreConvertFromChoice.from tag_ok
    if b
    then ok (core.result.Result.Ok ())
    else ok (core.result.Result.Err error.Error.InvalidTag)

/-- [signal_crypto::hash::{signal_crypto::hash::CryptographicMac}::update_and_get]:
    Source: 'rust/crypto/src/hash.rs', lines 39:4-42:5
    Visibility: public -/
def hash.CryptographicMac.update_and_get
  (self : hash.CryptographicMac) (input : Slice Std.U8) :
  Result (hash.CryptographicMac × (hash.CryptographicMac →
    hash.CryptographicMac))
  := do
  let self1 ← hash.CryptographicMac.update self input
  ok (self1, fun self2 => self2)


end signal_crypto

