-- Generated by scripts/split-types.ts from Aeneas output.
-- These definitions have been moved here from Types.lean.
-- Defs with no axiom dependencies. See types_pre_base in aeneas-config.yml.
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.longLine false
set_option linter.style.setOption false
set_option linter.style.whitespace false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

namespace signal_crypto


/-- Trait declaration: [core::num::nonzero::private::Sealed]
    Source: '/rustc/library/core/src/num/nonzero.rs', lines 46:12-46:28
    Name pattern: [core::num::nonzero::private::Sealed]
    Visibility: public -/
@[rust_trait "core::num::nonzero::private::Sealed"]
structure core.num.nonzero.private.Sealed (Self : Type) where

/-- Trait declaration: [core::num::nonzero::ZeroablePrimitive]
    Source: '/rustc/library/core/src/num/nonzero.rs', lines 33:0-33:66
    Name pattern: [core::num::nonzero::ZeroablePrimitive]
    Visibility: public -/
@[rust_trait "core::num::nonzero::ZeroablePrimitive"
  (parentClauses := ["markerCopyInst", "privateSealedInst", "markerCopyInst"])]
structure core.num.nonzero.ZeroablePrimitive (Self : Type) (Self_NonZeroInner :
  Type) where
  markerCopyInst : core.marker.Copy Self
  privateSealedInst : core.num.nonzero.private.Sealed Self
  markerCopyInst1 : core.marker.Copy Self_NonZeroInner

/-- Trait declaration: [core::ops::arith::Add]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 77:0-77:31
    Name pattern: [core::ops::arith::Add]
    Visibility: public -/
@[rust_trait "core::ops::arith::Add"]
structure core.ops.arith.Add (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  add : Self → Rhs → Result Self_Output

/-- Trait declaration: [core::ops::arith::Sub]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 190:0-190:31
    Name pattern: [core::ops::arith::Sub]
    Visibility: public -/
@[rust_trait "core::ops::arith::Sub"]
structure core.ops.arith.Sub (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  sub : Self → Rhs → Result Self_Output

/-- Trait declaration: [core::ops::arith::Div]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 462:0-462:31
    Name pattern: [core::ops::arith::Div]
    Visibility: public -/
@[rust_trait "core::ops::arith::Div"]
structure core.ops.arith.Div (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  div : Self → Rhs → Result Self_Output

/-- Trait declaration: [core::ops::arith::Rem]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 571:0-571:31
    Name pattern: [core::ops::arith::Rem]
    Visibility: public -/
@[rust_trait "core::ops::arith::Rem"]
structure core.ops.arith.Rem (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  rem : Self → Rhs → Result Self_Output

/-- Trait declaration: [core::ops::bit::Shl]
    Source: '/rustc/library/core/src/ops/bit.rs', lines 461:0-461:31
    Name pattern: [core::ops::bit::Shl]
    Visibility: public -/
@[rust_trait "core::ops::bit::Shl"]
structure core.ops.bit.Shl (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  shl : Self → Rhs → Result Self_Output

/-- [typenum::uint::UTerm]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/uint.rs', lines 50:0-50:16
    Name pattern: [typenum::uint::UTerm]
    Visibility: public -/
@[reducible, rust_type "typenum::uint::UTerm"]
def typenum.uint.UTerm := Unit

/-- [typenum::bit::B1]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/bit.rs', lines 33:0-33:13
    Name pattern: [typenum::bit::B1]
    Visibility: public -/
@[reducible, rust_type "typenum::bit::B1"]
def typenum.bit.B1 := Unit

/-- [typenum::bit::B0]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/bit.rs', lines 20:0-20:13
    Name pattern: [typenum::bit::B0]
    Visibility: public -/
@[reducible, rust_type "typenum::bit::B0"]
def typenum.bit.B0 := Unit

/-- Trait declaration: [typenum::sealed::Sealed]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/lib.rs', lines 154:4-154:20
    Name pattern: [typenum::sealed::Sealed]
    Visibility: public -/
@[rust_trait "typenum::sealed::Sealed"]
structure typenum.sealed.Sealed (Self : Type) where

/-- Trait declaration: [typenum::marker_traits::Unsigned]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/marker_traits.rs', lines 59:0-59:53
    Name pattern: [typenum::marker_traits::Unsigned]
    Visibility: public -/
@[rust_trait "typenum::marker_traits::Unsigned"
  (parentClauses := ["sealedSealedInst", "coremarkerCopyInst", "coredefaultDefaultInst"])
  (consts := ["U8", "U16", "U32", "U64", "USIZE", "I8", "I16", "I32", "I64", "ISIZE"])]
structure typenum.marker_traits.Unsigned (Self : Type) where
  U8 : Result Std.U8
  U16 : Result Std.U16
  U32 : Result Std.U32
  U64 : Result Std.U64
  USIZE : Result Std.Usize
  I8 : Result Std.I8
  I16 : Result Std.I16
  I32 : Result Std.I32
  I64 : Result Std.I64
  ISIZE : Result Std.Isize
  sealedSealedInst : typenum.sealed.Sealed Self
  coremarkerCopyInst : core.marker.Copy Self
  coredefaultDefaultInst : core.default.Default Self
  to_u8 : Result Std.U8
  to_u16 : Result Std.U16
  to_u32 : Result Std.U32
  to_u64 : Result Std.U64
  to_usize : Result Std.Usize
  to_i8 : Result Std.I8
  to_i16 : Result Std.I16
  to_i32 : Result Std.I32
  to_i64 : Result Std.I64
  to_isize : Result Std.Isize

/-- Trait declaration: [typenum::marker_traits::Bit]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/marker_traits.rs', lines 35:0-35:48
    Name pattern: [typenum::marker_traits::Bit]
    Visibility: public -/
@[rust_trait "typenum::marker_traits::Bit"
  (parentClauses := ["sealedSealedInst", "coremarkerCopyInst", "coredefaultDefaultInst"])
  (consts := ["U8", "BOOL"])]
structure typenum.marker_traits.Bit (Self : Type) where
  U8 : Result Std.U8
  BOOL : Result Bool
  sealedSealedInst : typenum.sealed.Sealed Self
  coremarkerCopyInst : core.marker.Copy Self
  coredefaultDefaultInst : core.default.Default Self
  new : Result Self
  to_u8 : Result Std.U8
  to_bool : Result Bool

/-- Trait declaration: [typenum::type_operators::IsLess]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/type_operators.rs', lines 374:0-374:28
    Name pattern: [typenum::type_operators::IsLess]
    Visibility: public -/
@[rust_trait "typenum::type_operators::IsLess"
  (parentClauses := ["marker_traitsBitInst"])]
structure typenum.type_operators.IsLess (Self : Type) (Rhs : Type) (Self_Output
  : Type) where
  marker_traitsBitInst : typenum.marker_traits.Bit Self_Output
  is_less : Self → Rhs → Result Self_Output

/-- Trait declaration: [typenum::marker_traits::NonZero]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/marker_traits.rs', lines 22:0-22:25
    Name pattern: [typenum::marker_traits::NonZero]
    Visibility: public -/
@[rust_trait "typenum::marker_traits::NonZero"
  (parentClauses := ["sealedSealedInst"])]
structure typenum.marker_traits.NonZero (Self : Type) where
  sealedSealedInst : typenum.sealed.Sealed Self

/-- Trait declaration: [typenum::type_operators::PartialDiv]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/type_operators.rs', lines 348:0-348:32
    Name pattern: [typenum::type_operators::PartialDiv]
    Visibility: public -/
@[rust_trait "typenum::type_operators::PartialDiv"]
structure typenum.type_operators.PartialDiv (Self : Type) (Rhs : Type)
  (Self_Output : Type) where
  partial_div : Self → Rhs → Result Self_Output

/-- Trait declaration: [typenum::marker_traits::Ord]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/marker_traits.rs', lines 29:0-29:21
    Name pattern: [typenum::marker_traits::Ord]
    Visibility: public -/
@[rust_trait "typenum::marker_traits::Ord"
  (parentClauses := ["sealedSealedInst"])]
structure typenum.marker_traits.Ord (Self : Type) where
  sealedSealedInst : typenum.sealed.Sealed Self
  to_ordering : Result Ordering

/-- [typenum::Less]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/lib.rs', lines 98:0-98:15
    Name pattern: [typenum::Less]
    Visibility: public -/
@[reducible, rust_type "typenum::Less"]
def typenum.Less := Unit

/-- [typenum::Greater]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/lib.rs', lines 92:0-92:18
    Name pattern: [typenum::Greater]
    Visibility: public -/
@[reducible, rust_type "typenum::Greater"]
def typenum.Greater := Unit

/-- [typenum::Equal]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/lib.rs', lines 104:0-104:16
    Name pattern: [typenum::Equal]
    Visibility: public -/
@[reducible, rust_type "typenum::Equal"]
def typenum.Equal := Unit

/-- Trait declaration: [typenum::private::PrivateCmp]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/private.rs', lines 320:0-320:32
    Name pattern: [typenum::private::PrivateCmp]
    Visibility: public -/
@[rust_trait "typenum::private::PrivateCmp"]
structure typenum.private.PrivateCmp (Self : Type) (Rhs : Type) (SoFar : Type)
  (Self_Output : Type) where
  private_cmp : Self → Rhs → SoFar → Result Self_Output

/-- Trait declaration: [typenum::private::InternalMarker]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/private.rs', lines 31:0-31:24
    Name pattern: [typenum::private::InternalMarker]
    Visibility: public -/
@[rust_trait "typenum::private::InternalMarker"]
structure typenum.private.InternalMarker (Self : Type) where

/-- Trait declaration: [typenum::type_operators::Cmp]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/type_operators.rs', lines 310:0-310:25
    Name pattern: [typenum::type_operators::Cmp]
    Visibility: public -/
@[rust_trait "typenum::type_operators::Cmp"]
structure typenum.type_operators.Cmp (Self : Type) (Rhs : Type) (Self_Output :
  Type) where
  compare : forall {IM : Type} (privateInternalMarkerInst :
    typenum.private.InternalMarker IM), Self → Rhs → Result Self_Output

/-- Trait declaration: [typenum::private::IsLessPrivate]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/private.rs', lines 394:0-394:33
    Name pattern: [typenum::private::IsLessPrivate]
    Visibility: public -/
@[rust_trait "typenum::private::IsLessPrivate"
  (parentClauses := ["marker_traitsBitInst"])]
structure typenum.private.IsLessPrivate (Self : Type) (Rhs : Type) (Cmp : Type)
  (Self_Output : Type) where
  marker_traitsBitInst : typenum.marker_traits.Bit Self_Output
  is_less_private : Self → Rhs → Cmp → Result Self_Output

/-- Trait declaration: [typenum::private::Trim]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/private.rs', lines 36:0-36:14
    Name pattern: [typenum::private::Trim]
    Visibility: public -/
@[rust_trait "typenum::private::Trim"]
structure typenum.private.Trim (Self : Type) (Self_Output : Type) where
  trim : Self → Result Self_Output

/-- Trait declaration: [typenum::private::TrimTrailingZeros]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/private.rs', lines 45:0-45:27
    Name pattern: [typenum::private::TrimTrailingZeros]
    Visibility: public -/
@[rust_trait "typenum::private::TrimTrailingZeros"]
structure typenum.private.TrimTrailingZeros (Self : Type) (Self_Output : Type)
  where
  trim_trailing_zeros : Self → Result Self_Output

/-- Trait declaration: [typenum::private::Invert]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/private.rs', lines 54:0-54:16
    Name pattern: [typenum::private::Invert]
    Visibility: public -/
@[rust_trait "typenum::private::Invert"]
structure typenum.private.Invert (Self : Type) (Self_Output : Type) where
  invert : Self → Result Self_Output

/-- Trait declaration: [typenum::private::PrivateInvert]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/private.rs', lines 63:0-63:28
    Name pattern: [typenum::private::PrivateInvert]
    Visibility: public -/
@[rust_trait "typenum::private::PrivateInvert"]
structure typenum.private.PrivateInvert (Self : Type) (Rhs : Type) (Self_Output
  : Type) where
  private_invert : Self → Rhs → Result Self_Output

/-- [typenum::private::InvertedUTerm]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/private.rs', lines 71:0-71:24
    Name pattern: [typenum::private::InvertedUTerm]
    Visibility: public -/
@[reducible, rust_type "typenum::private::InvertedUTerm"]
def typenum.private.InvertedUTerm := Unit

/-- Trait declaration: [typenum::private::InvertedUnsigned]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/private.rs', lines 134:0-134:26
    Name pattern: [typenum::private::InvertedUnsigned]
    Visibility: public -/
@[rust_trait "typenum::private::InvertedUnsigned"]
structure typenum.private.InvertedUnsigned (Self : Type) where
  to_u64 : Result Std.U64

/-- Trait declaration: [typenum::private::PrivateSetBit]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/private.rs', lines 328:0-328:29
    Name pattern: [typenum::private::PrivateSetBit]
    Visibility: public -/
@[rust_trait "typenum::private::PrivateSetBit"]
structure typenum.private.PrivateSetBit (Self : Type) (I : Type) (B : Type)
  (Self_Output : Type) where
  private_set_bit : Self → I → B → Result Self_Output

/-- Trait declaration: [typenum::private::PrivateDiv]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/private.rs', lines 336:0-336:35
    Name pattern: [typenum::private::PrivateDiv]
    Visibility: public -/
@[rust_trait "typenum::private::PrivateDiv"]
structure typenum.private.PrivateDiv (Self : Type) (N : Type) (D : Type) (Q :
  Type) (R : Type) (I : Type) (Self_Quotient : Type) (Self_Remainder : Type)
  where
  private_div_quotient : Self → N → D → Q → R → I → Result
    Self_Quotient
  private_div_remainder : Self → N → D → Q → R → I → Result
    Self_Remainder

/-- Trait declaration: [typenum::private::PrivateDivIf]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/private.rs', lines 348:0-348:44
    Name pattern: [typenum::private::PrivateDivIf]
    Visibility: public -/
@[rust_trait "typenum::private::PrivateDivIf"]
structure typenum.private.PrivateDivIf (Self : Type) (N : Type) (D : Type) (Q :
  Type) (R : Type) (I : Type) (RcmpD : Type) (Self_Quotient : Type)
  (Self_Remainder : Type) where
  private_div_if_quotient : Self → N → D → Q → R → I → RcmpD →
    Result Self_Quotient
  private_div_if_remainder : Self → N → D → Q → R → I → RcmpD →
    Result Self_Remainder

/-- Trait declaration: [typenum::type_operators::Len]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/type_operators.rs', lines 320:0-320:13
    Name pattern: [typenum::type_operators::Len]
    Visibility: public -/
@[rust_trait "typenum::type_operators::Len"
  (parentClauses := ["marker_traitsUnsignedInst"])]
structure typenum.type_operators.Len (Self : Type) (Self_Output : Type) where
  marker_traitsUnsignedInst : typenum.marker_traits.Unsigned Self_Output
  len : Self → Result Self_Output

/-- Trait declaration: [typenum::uint::GetBit]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/uint.rs', lines 1564:0-1564:19
    Name pattern: [typenum::uint::GetBit]
    Visibility: public -/
@[rust_trait "typenum::uint::GetBit"]
structure typenum.uint.GetBit (Self : Type) (I : Type) (Self_Output : Type)
  where
  get_bit : forall {IM : Type} (privateInternalMarkerInst :
    typenum.private.InternalMarker IM), Self → I → Result Self_Output

/-- Trait declaration: [typenum::uint::SetBit]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/uint.rs', lines 1630:0-1630:22
    Name pattern: [typenum::uint::SetBit]
    Visibility: public -/
@[rust_trait "typenum::uint::SetBit"]
structure typenum.uint.SetBit (Self : Type) (I : Type) (B : Type) (Self_Output
  : Type) where
  set_bit : forall {IM : Type} (privateInternalMarkerInst :
    typenum.private.InternalMarker IM), Self → I → B → Result Self_Output

/-- Trait declaration: [generic_array::ArrayLength]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/generic-array-0.14.7/src/lib.rs', lines 112:0-112:41
    Name pattern: [generic_array::ArrayLength]
    Visibility: public -/
@[rust_trait "generic_array::ArrayLength"
  (parentClauses := ["typenummarker_traitsUnsignedInst"])]
structure generic_array.ArrayLength (Self : Type) (T : Type) (Self_ArrayType :
  Type) where
  typenummarker_traitsUnsignedInst : typenum.marker_traits.Unsigned Self

/-- Trait declaration: [crypto_common::BlockSizeUser]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/crypto-common-0.1.7/src/lib.rs', lines 42:0-42:23
    Name pattern: [crypto_common::BlockSizeUser]
    Visibility: public -/
@[rust_trait "crypto_common::BlockSizeUser"
  (parentClauses := ["generic_arrayArrayLengthSelf_BlockSizeU8Self_Clause0_ArrayTypeInst"])]
structure crypto_common.BlockSizeUser (Self : Type) (Self_BlockSize : Type)
  (Self_Clause0_ArrayType : Type) where
  generic_arrayArrayLengthSelf_BlockSizeU8Self_Clause0_ArrayTypeInst :
    generic_array.ArrayLength Self_BlockSize Std.U8 Self_Clause0_ArrayType

/-- [block_padding::PadType]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/block-padding-0.3.3/src/lib.rs', lines 23:0-23:16
    Name pattern: [block_padding::PadType]
    Visibility: public -/
@[discriminant isize, rust_type "block_padding::PadType"]
inductive block_padding.PadType where
| Reversible : block_padding.PadType
| Ambiguous : block_padding.PadType
| NoPadding : block_padding.PadType

/-- [block_padding::UnpadError]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/block-padding-0.3.3/src/lib.rs', lines 401:0-401:21
    Name pattern: [block_padding::UnpadError]
    Visibility: public -/
@[reducible, rust_type "block_padding::UnpadError"]
def block_padding.UnpadError := Unit

/-- Trait declaration: [cipher::block::BlockCipher]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/cipher-0.4.4/src/block.rs', lines 26:0-26:36
    Name pattern: [cipher::block::BlockCipher]
    Visibility: public -/
@[rust_trait "cipher::block::BlockCipher"
  (parentClauses := ["crypto_commonBlockSizeUserInst"])]
structure cipher.block.BlockCipher (Self : Type) (Self_Clause0_BlockSize :
  Type) (Self_Clause0_Clause0_ArrayType : Type) where
  crypto_commonBlockSizeUserInst : crypto_common.BlockSizeUser Self
    Self_Clause0_BlockSize Self_Clause0_Clause0_ArrayType

/-- Trait declaration: [cipher::stream_core::Counter]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/cipher-0.4.4/src/stream_core.rs', lines 159:0-169:20
    Name pattern: [cipher::stream_core::Counter]
    Visibility: public -/
@[rust_trait "cipher::stream_core::Counter"
  (parentClauses := ["coreconvertTryFromSelfI32Self_Clause0_ErrorInst", "coreconvertTryFromSelfU32Self_Clause1_ErrorInst", "coreconvertTryFromSelfU64Self_Clause2_ErrorInst", "coreconvertTryFromSelfU128Self_Clause3_ErrorInst", "coreconvertTryFromSelfUsizeSelf_Clause4_ErrorInst", "coreconvertTryIntoSelfI32Self_Clause5_ErrorInst", "coreconvertTryIntoSelfU32Self_Clause6_ErrorInst", "coreconvertTryIntoSelfU64Self_Clause7_ErrorInst", "coreconvertTryIntoSelfU128Self_Clause8_ErrorInst", "coreconvertTryIntoSelfUsizeSelf_Clause9_ErrorInst"])]
structure cipher.stream_core.Counter (Self : Type) (Self_Clause0_Error : Type)
  (Self_Clause1_Error : Type) (Self_Clause2_Error : Type) (Self_Clause3_Error :
  Type) (Self_Clause4_Error : Type) (Self_Clause5_Error : Type)
  (Self_Clause6_Error : Type) (Self_Clause7_Error : Type) (Self_Clause8_Error :
  Type) (Self_Clause9_Error : Type) where
  coreconvertTryFromSelfI32Self_Clause0_ErrorInst : core.convert.TryFrom Self
    Std.I32 Self_Clause0_Error
  coreconvertTryFromSelfU32Self_Clause1_ErrorInst : core.convert.TryFrom Self
    Std.U32 Self_Clause1_Error
  coreconvertTryFromSelfU64Self_Clause2_ErrorInst : core.convert.TryFrom Self
    Std.U64 Self_Clause2_Error
  coreconvertTryFromSelfU128Self_Clause3_ErrorInst : core.convert.TryFrom Self
    Std.U128 Self_Clause3_Error
  coreconvertTryFromSelfUsizeSelf_Clause4_ErrorInst : core.convert.TryFrom Self
    Std.Usize Self_Clause4_Error
  coreconvertTryIntoSelfI32Self_Clause5_ErrorInst : core.convert.TryInto Self
    Std.I32 Self_Clause5_Error
  coreconvertTryIntoSelfU32Self_Clause6_ErrorInst : core.convert.TryInto Self
    Std.U32 Self_Clause6_Error
  coreconvertTryIntoSelfU64Self_Clause7_ErrorInst : core.convert.TryInto Self
    Std.U64 Self_Clause7_Error
  coreconvertTryIntoSelfU128Self_Clause8_ErrorInst : core.convert.TryInto Self
    Std.U128 Self_Clause8_Error
  coreconvertTryIntoSelfUsizeSelf_Clause9_ErrorInst : core.convert.TryInto Self
    Std.Usize Self_Clause9_Error

/-- Trait declaration: [rand_core::RngCore]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rand_core-0.9.3/src/lib.rs', lines 130:0-130:17
    Name pattern: [rand_core::RngCore]
    Visibility: public -/
@[rust_trait "rand_core::RngCore"]
structure rand_core.RngCore (Self : Type) where
  next_u32 : Self → Result (Std.U32 × Self)
  next_u64 : Self → Result (Std.U64 × Self)
  fill_bytes : Self → Slice Std.U8 → Result (Self × (Slice Std.U8))

/-- Trait declaration: [rand_core::CryptoRng]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rand_core-0.9.3/src/lib.rs', lines 204:0-204:28
    Name pattern: [rand_core::CryptoRng]
    Visibility: public -/
@[rust_trait "rand_core::CryptoRng" (parentClauses := ["RngCoreInst"])]
structure rand_core.CryptoRng (Self : Type) where
  RngCoreInst : rand_core.RngCore Self

/-- Trait declaration: [rand::rng::Rng]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rand-0.9.2/src/rng.rs', lines 58:0-58:22
    Name pattern: [rand::rng::Rng]
    Visibility: public -/
@[rust_trait "rand::rng::Rng" (parentClauses := ["rand_coreRngCoreInst"])]
structure rand.rng.Rng (Self : Type) where
  rand_coreRngCoreInst : rand_core.RngCore Self

/-- Trait declaration: [rand::distr::distribution::Distribution]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rand-0.9.2/src/distr/distribution.rs', lines 35:0-35:25
    Name pattern: [rand::distr::distribution::Distribution]
    Visibility: public -/
@[rust_trait "rand::distr::distribution::Distribution"]
structure rand.distr.distribution.Distribution (Self : Type) (T : Type) where
  sample : forall {R : Type} (rngRngInst : rand.rng.Rng R), Self → R →
    Result (T × R)

/-- [rand::distr::StandardUniform]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rand-0.9.2/src/distr/mod.rs', lines 214:0-214:26
    Name pattern: [rand::distr::StandardUniform]
    Visibility: public -/
@[reducible, rust_type "rand::distr::StandardUniform"]
def rand.distr.StandardUniform := Unit

/-- Trait declaration: [rand::rng::Fill]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rand-0.9.2/src/rng.rs', lines 366:0-366:14
    Name pattern: [rand::rng::Fill]
    Visibility: public -/
@[rust_trait "rand::rng::Fill"]
structure rand.rng.Fill (Self : Type) where
  fill : forall {R : Type} (RngInst : rand.rng.Rng R), Self → R → Result
    (Self × R)

/-- [derive_more::convert::try_from::TryFromReprError]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/derive_more-2.1.1/src/convert.rs', lines 17:4-17:34
    Name pattern: [derive_more::convert::try_from::TryFromReprError]
    Visibility: public -/
@[rust_type "derive_more::convert::try_from::TryFromReprError"]
structure derive_more.convert.try_from.TryFromReprError (T : Type) where
  input : T

/-- [signal_crypto::aes_cbc::EncryptionError]
    Source: 'rust/crypto/src/aes_cbc.rs', lines 13:0-16:1
    Visibility: public -/
@[discriminant isize]
inductive aes_cbc.EncryptionError where
| BadKeyOrIv : aes_cbc.EncryptionError

/-- [signal_crypto::aes_cbc::DecryptionError]
    Source: 'rust/crypto/src/aes_cbc.rs', lines 19:0-24:1
    Visibility: public -/
@[discriminant isize]
inductive aes_cbc.DecryptionError where
| BadKeyOrIv : aes_cbc.DecryptionError
| BadCiphertext : Str → aes_cbc.DecryptionError

/-- [signal_crypto::error::Error]
    Source: 'rust/crypto/src/error.rs', lines 7:0-18:1
    Visibility: public -/
@[discriminant isize]
inductive error.Error where
| UnknownAlgorithm : Str → String → error.Error
| InvalidKeySize : error.Error
| InvalidNonceSize : error.Error
| InvalidInputSize : error.Error
| InvalidTag : error.Error

/-- [libsignal_core::address::InvalidDeviceId]
    Source: 'rust/core/src/address.rs', lines 687:0-687:26
    Name pattern: [libsignal_core::address::InvalidDeviceId]
    Visibility: public -/
@[reducible, rust_type "libsignal_core::address::InvalidDeviceId"]
def libsignal_core.address.InvalidDeviceId := Unit

/-- [libsignal_core::curve::KeyType]
    Source: 'rust/core/src/curve.rs', lines 15:0-15:16
    Name pattern: [libsignal_core::curve::KeyType]
    Visibility: public -/
@[discriminant isize, rust_type "libsignal_core::curve::KeyType"]
inductive libsignal_core.curve.KeyType where
| Djb : libsignal_core.curve.KeyType

/-- [libsignal_core::curve::CurveError]
    Source: 'rust/core/src/curve.rs', lines 34:0-34:19
    Name pattern: [libsignal_core::curve::CurveError]
    Visibility: public -/
@[discriminant isize, rust_type "libsignal_core::curve::CurveError"]
inductive libsignal_core.curve.CurveError where
| NoKeyTypeIdentifier : libsignal_core.curve.CurveError
| BadKeyType : Std.U8 → libsignal_core.curve.CurveError
| BadKeyLength :
  libsignal_core.curve.KeyType →
  Std.Usize →
  libsignal_core.curve.CurveError
| InvalidKeyAgreement : libsignal_core.curve.CurveError

/-- [libsignal_core::curve::PublicKeyData]
    Source: 'rust/core/src/curve.rs', lines 59:0-59:18
    Name pattern: [libsignal_core::curve::PublicKeyData] -/
@[discriminant isize, rust_type "libsignal_core::curve::PublicKeyData"]
inductive libsignal_core.curve.PublicKeyData where
| DjbPublicKey : Array Std.U8 32#usize → libsignal_core.curve.PublicKeyData

/-- [libsignal_core::curve::PublicKey]
    Source: 'rust/core/src/curve.rs', lines 64:0-64:20
    Name pattern: [libsignal_core::curve::PublicKey]
    Visibility: public -/
@[rust_type "libsignal_core::curve::PublicKey"]
structure libsignal_core.curve.PublicKey where
  key : libsignal_core.curve.PublicKeyData

/-- [libsignal_core::curve::PrivateKeyData]
    Source: 'rust/core/src/curve.rs', lines 232:0-232:19
    Name pattern: [libsignal_core::curve::PrivateKeyData] -/
@[discriminant isize, rust_type "libsignal_core::curve::PrivateKeyData"]
inductive libsignal_core.curve.PrivateKeyData where
| DjbPrivateKey : Array Std.U8 32#usize → libsignal_core.curve.PrivateKeyData

/-- [libsignal_core::curve::PrivateKey]
    Source: 'rust/core/src/curve.rs', lines 237:0-237:21
    Name pattern: [libsignal_core::curve::PrivateKey]
    Visibility: public -/
@[rust_type "libsignal_core::curve::PrivateKey"]
structure libsignal_core.curve.PrivateKey where
  key : libsignal_core.curve.PrivateKeyData

/-- [libsignal_core::curve::KeyPair]
    Source: 'rust/core/src/curve.rs', lines 321:0-321:18
    Name pattern: [libsignal_core::curve::KeyPair]
    Visibility: public -/
@[rust_type "libsignal_core::curve::KeyPair"]
structure libsignal_core.curve.KeyPair where
  public_key : libsignal_core.curve.PublicKey
  private_key : libsignal_core.curve.PrivateKey


end signal_crypto

