//
// Copyright (C) 2020 Signal Messenger, LLC.
// All rights reserved.
//
// SPDX-License-Identifier: GPL-3.0-only
//

// Generated by zkgroup/codegen/codegen.py - do not edit

package org.signal.zkgroup.auth;

import org.signal.zkgroup.InvalidInputException;
import org.signal.zkgroup.internal.ByteArray;
import org.signal.client.internal.Native;

public final class AuthCredential extends ByteArray {

  public static final int SIZE = 181;

  public AuthCredential(byte[] contents) throws InvalidInputException {
    super(contents, SIZE);
    Native.AuthCredential_CheckValidContents(contents);
  }

  public byte[] serialize() {
    return contents.clone();
  }

}
