//
// Copyright 2026 Signal Messenger, LLC.
// SPDX-License-Identifier: AGPL-3.0-only
//

import { RequestOptions, UnauthenticatedChatConnection } from '../Chat.js';
import * as NativeNice from '../../NativeNice.js';
import type { StandardNetworkError } from '../../Errors.js';

declare module '../Chat' {
  // eslint-disable-next-line @typescript-eslint/no-empty-object-type
  interface UnauthenticatedChatConnection extends UnauthCredentialsService {}
}

export type AuthCheckResult =
  /**
   * The credentials could be used to make a call to SVR service by the user
   * associated with the `CheckSvrCredentialsRequest.number` phone number.
   */
  | 'match'
  /**
   * The credentials were generated by a different user.
   */
  | 'noMatch'
  /*
   * This status indicates that the corresponding credentials token should no longer be used.
   * This may be because it has expired or invalid, but it can also mean that there is a more
   * recent token in the request which should be used instead.
   */
  | 'invalid';

export interface UnauthCredentialsService {
  /**
   * Given a list of secure value recovery (SVR) service credentials and a phone
   * number, checks and returns which of the provided credentials were generated
   * by the user with the given phone number and have not yet expired.
   * @param number A phone number in the E164 format to check the passwords against. Only
   * passwords generated for the user associated with the given number will be marked as
   * `Match`.
   * @param credentials A list of credentials (`username:password`) from previously made calls to
   * `ExternalServiceCredentials.GetExternalServiceCredentials()` for
   * `EXTERNAL_SERVICE_TYPE_SVR`. This list may contain credentials generated by different
   * users. Up to 10 credentials can be checked.
   * @returns A map from the inputted credential to its corresponding result
   * @throws {StandardNetworkError}
   */
  checkSvrCredentials: (
    request: { number: string; credentials: string[] },
    options?: RequestOptions
  ) => Promise<Map<string, AuthCheckResult>>;
}
UnauthenticatedChatConnection.prototype.checkSvrCredentials = async function (
  {
    number,
    credentials,
  }: {
    number: string;
    credentials: Array<string>;
  },
  options?: RequestOptions
): Promise<Map<string, AuthCheckResult>> {
  return new Map(
    await NativeNice.UnauthenticatedChatConnection_check_svr_credentials({
      asyncContext: this._asyncContext,
      abortSignal: options?.abortSignal,
      chat: this._chatService,
      number,
      credentials,
    })
  );
};
