/**
 * Split Aeneas output files to break circular dependencies.
 *
 * Aeneas generates Types.lean (defs) and TypesExternal_Template.lean (axioms),
 * where Types imports TypesExternal. Some axioms reference defs and vice versa,
 * creating cycles. This script splits them into layers:
 *
 *   TypesPreBase ← TypesExternalPre_Template ← TypesPre ← TypesExternal_Template
 *     ← FunsPre ← Types ← FunsExternal_Template ← Funs
 *
 * Configuration lists in aeneas-config.yml control which declarations move where.
 */

import fs from "node:fs";
import path from "node:path";
import chalk from "chalk";
import { loadConfig } from "./lib/config.js";

/** Split content into declaration blocks (each starting with /-- ) */
function splitIntoBlocks(content: string): { header: string; blocks: string[]; footer: string } {
  const firstDecl = content.indexOf("\n/-- ");
  if (firstDecl === -1) {
    return { header: content, blocks: [], footer: "" };
  }
  const header = content.slice(0, firstDecl + 1);
  const endMatch = content.match(/\nend \S+\s*$/);
  const footer = endMatch ? endMatch[0] : "";
  const body = endMatch
    ? content.slice(firstDecl + 1, content.length - footer.length)
    : content.slice(firstDecl + 1);
  const blocks = body.split(/(?=\/-- )/).map((b) => b.trim()).filter(Boolean);
  return { header, blocks, footer };
}

/** Get the declared name from a block */
function getDeclName(block: string): string | null {
  const m = block.match(/(?:^|\n)(?:axiom|structure|def|inductive)\s+(\S+)/);
  return m ? m[1] : null;
}

/** Extract blocks matching a name list, returning extracted and remaining */
function extractBlocks(
  blocks: string[],
  names: Set<string>,
  orderMap: Map<string, number>,
  label: string,
): { extracted: string[]; remaining: string[] } {
  const extracted: string[] = [];
  const remaining: string[] = [];
  const found = new Set<string>();

  for (const block of blocks) {
    const name = getDeclName(block);
    if (name && names.has(name)) {
      extracted.push(block);
      found.add(name);
    } else {
      remaining.push(block);
    }
  }

  const missing = [...names].filter((n) => !found.has(n));
  if (missing.length > 0) {
    console.log(chalk.yellow(`  Warning: not found in ${label}: ${missing.join(", ")}`));
  }

  // Sort extracted by config order
  extracted.sort((a, b) => {
    const nameA = getDeclName(a);
    const nameB = getDeclName(b);
    return (orderMap.get(nameA ?? "") ?? 9999) - (orderMap.get(nameB ?? "") ?? 9999);
  });

  return { extracted, remaining };
}

/** Fix known Aeneas bug: ZeroablePrimitive has duplicate field name */
function fixDuplicateFields(content: string): string {
  return content.replace(
    /^(structure core\.num\.nonzero\.ZeroablePrimitive[\s\S]*?markerCopyInst : core\.marker\.Copy Self\n  privateSealedInst : core\.num\.nonzero\.private\.Sealed Self\n)  markerCopyInst/m,
    "$1  markerCopyInst1"
  );
}

/** Fix duplicate field in ZeroablePrimitive trait instances */
function fixDuplicateFieldsInFuns(content: string): string {
  let result = content;
  result = result.replace(
    /^(def U8\.Insts\.CoreNumNonzeroZeroablePrimitiveNonZeroU8Inner[\s\S]*?markerCopyInst := core\.marker\.CopyU8\n  privateSealedInst := U8\.Insts\.CoreNumNonzeroPrivateSealed\n)  markerCopyInst/m,
    "$1  markerCopyInst1"
  );
  result = result.replace(
    /^(def U64\.Insts\.CoreNumNonzeroZeroablePrimitiveNonZeroU64Inner[\s\S]*?markerCopyInst := core\.marker\.CopyU64\n  privateSealedInst := U64\.Insts\.CoreNumNonzeroPrivateSealed\n)  markerCopyInst/m,
    "$1  markerCopyInst1"
  );
  return result;
}

function makeHeader(original: string, comment: string, movedFrom: string, imports: string[]): string {
  let h = original
    .replace("-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS",
      `-- Generated by scripts/split-types.ts from Aeneas output.\n-- These definitions have been moved here from ${movedFrom}.`)
    .replace(/-- \[.*?\]: (?:type|function) definitions/,
      `-- ${comment}`);
  // Remove existing imports to Types/TypesExternal/FunsExternal (we'll set our own)
  h = h.replace(/import \S+\.Types\n/, "");
  h = h.replace(/import \S+\.TypesExternal\n/, "");
  h = h.replace(/import \S+\.FunsExternal\n/, "");
  // Add our imports after "import Aeneas"
  if (imports.length > 0) {
    h = h.replace("import Aeneas", "import Aeneas\n" + imports.map((i) => `import ${i}`).join("\n"));
  }
  return h;
}

function main(): void {
  const { config, root } = loadConfig();
  const cfg = config as any;
  const outputDir = config.aeneas_args.subdir
    ? path.join(root, config.aeneas_args.dest, config.aeneas_args.subdir)
    : path.join(root, config.aeneas_args.dest);
  const subdir = config.aeneas_args.subdir ?? "";
  const mod = subdir.replace(/\//g, ".");

  const typesPath = path.join(outputDir, "Types.lean");
  const typesExtTemplatePath = path.join(outputDir, "TypesExternal_Template.lean");
  const funsPath = path.join(outputDir, "Funs.lean");
  const funsExtTemplatePath = path.join(outputDir, "FunsExternal_Template.lean");

  if (!fs.existsSync(typesPath) || !fs.existsSync(typesExtTemplatePath)) {
    console.log(chalk.yellow("  Types.lean or TypesExternal_Template.lean not found, skipping"));
    return;
  }

  // Read source files
  const types = splitIntoBlocks(fs.readFileSync(typesPath, "utf-8"));
  const typesExt = splitIntoBlocks(fs.readFileSync(typesExtTemplatePath, "utf-8"));

  // Find namespace
  const nsMatch = types.header.match(/namespace\s+(\S+)/);
  const ns = nsMatch ? nsMatch[1] : null;

  // ── Layer 1: TypesPreBase (defs with no axiom deps) ─────────────────
  const preBaseList: string[] = cfg.types_pre_base ?? [];
  if (preBaseList.length > 0) {
    console.log(chalk.bold("Splitting Types.lean (layer 1: TypesPreBase)..."));
    const preBaseSet = new Set(preBaseList);
    const preBaseOrder = new Map(preBaseList.map((n: string, i: number) => [n, i]));
    const { extracted: preBaseBlocks, remaining: afterBase } = extractBlocks(
      types.blocks, preBaseSet, preBaseOrder, "Types.lean"
    );
    types.blocks = afterBase;

    let body = fixDuplicateFields(preBaseBlocks.join("\n\n"));
    const header = makeHeader(types.header,
      "Defs with no axiom dependencies. See types_pre_base in aeneas-config.yml.",
      "Types.lean", []);
    fs.writeFileSync(path.join(outputDir, "TypesPreBase.lean"),
      header + "\n" + body + "\n\n" + types.footer + "\n");
    console.log(`  ${preBaseBlocks.length} declarations → TypesPreBase.lean`);
  }

  // ── Layer 2: TypesExternalPre (axioms needed by TypesPre) ───────────
  const extPreList: string[] = cfg.types_external_pre ?? [];
  if (extPreList.length > 0) {
    console.log(chalk.bold("Splitting TypesExternal_Template.lean (layer 2: TypesExternalPre)..."));
    const extPreSet = new Set(extPreList);
    const extPreOrder = new Map(extPreList.map((n: string, i: number) => [n, i]));
    const { extracted: extPreBlocks, remaining: afterExtPre } = extractBlocks(
      typesExt.blocks, extPreSet, extPreOrder, "TypesExternal_Template.lean"
    );
    typesExt.blocks = afterExtPre;

    const header = makeHeader(typesExt.header,
      "Axioms needed by TypesPre. See types_external_pre in aeneas-config.yml.",
      "TypesExternal_Template.lean", [`${mod}.TypesPreBase`]);
    // Add open namespace so unqualified names from TypesPreBase are in scope
    let headerWithOpen = header;
    if (ns) {
      headerWithOpen = header.replace("open Aeneas", `open ${ns}\nopen Aeneas`);
    }
    fs.writeFileSync(path.join(outputDir, "TypesExternalPre_Template.lean"),
      headerWithOpen + "\n" + extPreBlocks.join("\n\n") + "\n");
    console.log(`  ${extPreBlocks.length} axioms → TypesExternalPre_Template.lean`);
  }

  // ── Layer 3: TypesPre (defs that need axioms) ──────────────────────
  const preList: string[] = cfg.types_pre ?? [];
  if (preList.length > 0) {
    console.log(chalk.bold("Splitting Types.lean (layer 3: TypesPre)..."));
    const preSet = new Set(preList);
    const preOrder = new Map(preList.map((n: string, i: number) => [n, i]));
    const { extracted: preBlocks, remaining: afterPre } = extractBlocks(
      types.blocks, preSet, preOrder, "Types.lean"
    );
    types.blocks = afterPre;

    const header = makeHeader(types.header,
      "Defs that need axioms from TypesExternalPre. See types_pre in aeneas-config.yml.",
      "Types.lean", [`${mod}.TypesExternalPre`]);
    fs.writeFileSync(path.join(outputDir, "TypesPre.lean"),
      header + "\n" + preBlocks.join("\n\n") + "\n\n" + types.footer + "\n");
    console.log(`  ${preBlocks.length} declarations → TypesPre.lean`);
  }

  // ── Layer 4: Rewrite TypesExternal_Template.lean ────────────────────
  {
    let header = typesExt.header;
    const imports = [`${mod}.TypesPre`];
    if (extPreList.length > 0) {
      imports.push(`${mod}.TypesExternalPre`);
    }
    header = header.replace("import Aeneas",
      "import Aeneas\n" + imports.map((i) => `import ${i}`).join("\n"));
    if (ns) {
      header = header.replace("open Aeneas", `open ${ns}\nopen Aeneas`);
    }
    fs.writeFileSync(typesExtTemplatePath,
      header + "\n" + typesExt.blocks.join("\n\n") + "\n");
    console.log(`  ${typesExt.blocks.length} axioms remain in TypesExternal_Template.lean`);
  }

  // ── Layer 5+6: Rewrite Types.lean ──────────────────────────────────
  {
    const imports = [];
    if (preBaseList.length > 0) imports.push(`${mod}.TypesPreBase`);
    if (extPreList.length > 0) imports.push(`${mod}.TypesExternalPre`);
    if (preList.length > 0) imports.push(`${mod}.TypesPre`);
    imports.push(`${mod}.TypesExternal`);
    const funsPreCfg: string[] = cfg.funs_pre ?? [];
    if (funsPreCfg.length > 0) imports.push(`${mod}.FunsPre`);

    let header = types.header;
    header = header.replace(/import \S+\.TypesExternal/, imports.map((i) => `import ${i}`).join("\n"));
    fs.writeFileSync(typesPath,
      header + "\n" + types.blocks.join("\n\n") + "\n\n" + types.footer + "\n");
    console.log(`  ${types.blocks.length} declarations remain in Types.lean`);
  }

  // ── Funs split ─────────────────────────────────────────────────────
  const funsPreList2: string[] = cfg.funs_pre ?? [];
  if (funsPreList2.length > 0 && fs.existsSync(funsPath)) {
    console.log(chalk.bold("Splitting Funs.lean..."));

    const funs = splitIntoBlocks(fs.readFileSync(funsPath, "utf-8"));
    const funsExt = fs.existsSync(funsExtTemplatePath)
      ? splitIntoBlocks(fs.readFileSync(funsExtTemplatePath, "utf-8"))
      : null;

    const funsPreSet = new Set(funsPreList2);
    const funsPreOrder = new Map(funsPreList2.map((n: string, i: number) => [n, i]));

    // Extract from both Funs and FunsExternal_Template
    const { extracted: funsPreBlocks, remaining: remainFuns } = extractBlocks(
      funs.blocks, funsPreSet, funsPreOrder, "Funs.lean"
    );
    funs.blocks = remainFuns;

    let remainFunsExt = funsExt?.blocks ?? [];
    if (funsExt) {
      const { extracted: funsExtPreBlocks, remaining: afterFunsExt } = extractBlocks(
        funsExt.blocks, funsPreSet, funsPreOrder, "FunsExternal_Template.lean"
      );
      funsPreBlocks.push(...funsExtPreBlocks);
      remainFunsExt = afterFunsExt;

      // Re-sort after merging
      funsPreBlocks.sort((a, b) => {
        const nameA = getDeclName(a);
        const nameB = getDeclName(b);
        return (funsPreOrder.get(nameA ?? "") ?? 9999) - (funsPreOrder.get(nameB ?? "") ?? 9999);
      });
    }

    let body = fixDuplicateFieldsInFuns(funsPreBlocks.join("\n\n"));

    // FunsPre imports TypesExternal (not Types, to avoid cycle)
    const funsPreHeader = makeHeader(funs.header,
      "Trait instances moved here so Types.lean can reference them. See funs_pre in aeneas-config.yml.",
      "Funs.lean", [`${mod}.TypesExternal`]);
    fs.writeFileSync(path.join(outputDir, "FunsPre.lean"),
      funsPreHeader + "\n" + body + "\n\n" + funs.footer + "\n");
    console.log(`  ${funsPreBlocks.length} declarations → FunsPre.lean`);

    // Rewrite Funs.lean
    let funsHeader = funs.header;
    funsHeader = funsHeader.replace(
      /import \S+\.Types\b/,
      `import ${mod}.Types\nimport ${mod}.FunsPre`
    );
    fs.writeFileSync(funsPath,
      funsHeader + "\n" + funs.blocks.join("\n\n") + "\n\n" + funs.footer + "\n");
    console.log(`  ${funs.blocks.length} declarations remain in Funs.lean`);

    // Rewrite FunsExternal_Template.lean
    if (funsExt) {
      fs.writeFileSync(funsExtTemplatePath,
        funsExt.header + "\n" + remainFunsExt.join("\n\n") + "\n\n" + (funsExt.footer || "") + "\n");
    }
  }

  console.log(chalk.green("  Split complete"));
}

try {
  main();
} catch (err) {
  console.error(chalk.red(`\nError: ${(err as Error).message}`));
  process.exit(1);
}
