/**
 * Split Types.lean to break the circular dependency with TypesExternal.lean.
 *
 * Moves declarations listed in aeneas-config.yml `types_pre` from Types.lean
 * (and TypesExternal_Template.lean) into TypesPre.lean. This allows
 * TypesExternal to import TypesPre and reference those declarations.
 *
 * Import chain after split: TypesPre ← TypesExternal ← Types
 */

import fs from "node:fs";
import path from "node:path";
import chalk from "chalk";
import { loadConfig } from "./lib/config.js";

/** Split content into declaration blocks (each starting with /-- ) */
function splitIntoBlocks(content: string): { header: string; blocks: string[]; footer: string } {
  const firstDecl = content.indexOf("\n/-- ");
  if (firstDecl === -1) {
    return { header: content, blocks: [], footer: "" };
  }
  const header = content.slice(0, firstDecl + 1);
  const endMatch = content.match(/\nend \S+\s*$/);
  const footer = endMatch ? endMatch[0] : "";
  const body = endMatch
    ? content.slice(firstDecl + 1, content.length - footer.length)
    : content.slice(firstDecl + 1);
  const blocks = body.split(/(?=\/-- )/).map((b) => b.trim()).filter(Boolean);
  return { header, blocks, footer };
}

/** Get the declared name from a block */
function getDeclName(block: string): string | null {
  const m = block.match(/(?:^|\n)(?:axiom|structure|def|inductive)\s+(\S+)/);
  return m ? m[1] : null;
}

function main(): void {
  const { config, root } = loadConfig();
  const outputDir = config.aeneas_args.subdir
    ? path.join(root, config.aeneas_args.dest, config.aeneas_args.subdir)
    : path.join(root, config.aeneas_args.dest);

  const moveList: string[] = (config as any).types_pre ?? [];
  if (moveList.length === 0) {
    console.log(chalk.yellow("  No types_pre list in config, skipping split"));
    return;
  }

  const typesPath = path.join(outputDir, "Types.lean");
  const typesExtTemplatePath = path.join(outputDir, "TypesExternal_Template.lean");
  const typesExtPath = path.join(outputDir, "TypesExternal.lean");
  const typesPrePath = path.join(outputDir, "TypesPre.lean");
  const subdir = config.aeneas_args.subdir ?? "";
  const modulePath = subdir.replace(/\//g, ".");

  if (!fs.existsSync(typesPath) || !fs.existsSync(typesExtTemplatePath)) {
    console.log(chalk.yellow("  Types.lean or TypesExternal_Template.lean not found, skipping"));
    return;
  }

  console.log(chalk.bold("Splitting Types.lean..."));

  const moveSet = new Set(moveList);

  // Collect blocks from both Types.lean and TypesExternal_Template.lean
  const typesContent = fs.readFileSync(typesPath, "utf-8");
  const typesExtContent = fs.readFileSync(typesExtTemplatePath, "utf-8");

  const types = splitIntoBlocks(typesContent);
  const typesExt = splitIntoBlocks(typesExtContent);

  // Partition: pre vs remaining
  const preBlocks: string[] = [];
  const remainTypes: string[] = [];
  const remainExt: string[] = [];

  for (const block of types.blocks) {
    const name = getDeclName(block);
    if (name && moveSet.has(name)) {
      preBlocks.push(block);
      moveSet.delete(name);
    } else {
      remainTypes.push(block);
    }
  }

  for (const block of typesExt.blocks) {
    const name = getDeclName(block);
    if (name && moveSet.has(name)) {
      preBlocks.push(block);
      moveSet.delete(name);
    } else {
      remainExt.push(block);
    }
  }

  if (moveSet.size > 0) {
    console.log(chalk.yellow(`  Warning: ${moveSet.size} declarations not found: ${[...moveSet].join(", ")}`));
  }

  // Sort preBlocks by the order in the config list
  const orderMap = new Map(moveList.map((name, i) => [name, i]));
  preBlocks.sort((a, b) => {
    const nameA = getDeclName(a);
    const nameB = getDeclName(b);
    const orderA = nameA ? (orderMap.get(nameA) ?? 9999) : 9999;
    const orderB = nameB ? (orderMap.get(nameB) ?? 9999) : 9999;
    return orderA - orderB;
  });

  console.log(`  ${preBlocks.length} declarations → TypesPre.lean`);
  console.log(`  ${remainTypes.length} declarations → Types.lean`);
  console.log(`  ${remainExt.length} declarations → TypesExternal.lean`);

  // Find namespace
  const nsMatch = types.header.match(/namespace\s+(\S+)/);
  const ns = nsMatch ? nsMatch[1] : null;

  // Fix known Aeneas bug: ZeroablePrimitive has duplicate field name "markerCopyInst"
  let preBody = preBlocks.join("\n\n");
  preBody = preBody.replace(
    /^(structure core\.num\.nonzero\.ZeroablePrimitive[\s\S]*?markerCopyInst : core\.marker\.Copy Self\n  privateSealedInst : core\.num\.nonzero\.private\.Sealed Self\n)  markerCopyInst/m,
    "$1  markerCopyInst1"
  );

  // Build TypesPre.lean
  const preHeader = types.header
    .replace("-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS", "-- Generated by scripts/split-types.ts from Aeneas output.")
    .replace(/-- \[.*?\]: type definitions/, "-- Type declarations moved here to break circular dependency with TypesExternal.\n-- See the types_pre list in aeneas-config.yml.")
    .replace(/import \S+\.TypesExternal\n/, "");
  fs.writeFileSync(typesPrePath, preHeader + "\n" + preBody + "\n\n" + types.footer + "\n");

  // Build new Types.lean (import both TypesPre and TypesExternal)
  const newTypesHeader = types.header.replace(
    /import \S+\.TypesExternal/,
    `import ${modulePath}.TypesPre\nimport ${modulePath}.TypesExternal`
  );
  fs.writeFileSync(typesPath, newTypesHeader + "\n" + remainTypes.join("\n\n") + "\n\n" + types.footer + "\n");

  // Build TypesExternal.lean (import TypesPre, open namespace)
  let extHeader = typesExtContent.slice(0, typesExtContent.indexOf("\n/-- ") + 1);
  extHeader = extHeader.replace("import Aeneas", `import Aeneas\nimport ${modulePath}.TypesPre`);
  if (ns) {
    extHeader = extHeader.replace("open Aeneas", `open ${ns}\nopen Aeneas`);
  }
  fs.writeFileSync(typesExtPath, extHeader + "\n" + remainExt.join("\n\n") + "\n");

  // ── Split Funs.lean → FunsPre.lean ──────────────────────────────────
  const funsMoveList: string[] = (config as any).funs_pre ?? [];
  if (funsMoveList.length > 0) {
    const funsPath = path.join(outputDir, "Funs.lean");
    const funsPrePath = path.join(outputDir, "FunsPre.lean");

    const funsExtTemplatePath = path.join(outputDir, "FunsExternal_Template.lean");
    const funsExtPath = path.join(outputDir, "FunsExternal.lean");

    if (fs.existsSync(funsPath)) {
      console.log(chalk.bold("Splitting Funs.lean..."));

      const funsContent = fs.readFileSync(funsPath, "utf-8");
      const funsExtContent = fs.existsSync(funsExtTemplatePath)
        ? fs.readFileSync(funsExtTemplatePath, "utf-8") : "";
      const funs = splitIntoBlocks(funsContent);
      const funsExt = funsExtContent ? splitIntoBlocks(funsExtContent) : { header: "", blocks: [], footer: "" };
      const funsMoveSet = new Set(funsMoveList);

      const funsPreBlocks: string[] = [];
      const remainFuns: string[] = [];
      const remainFunsExt: string[] = [];

      for (const block of funs.blocks) {
        const name = getDeclName(block);
        if (name && funsMoveSet.has(name)) {
          funsPreBlocks.push(block);
          funsMoveSet.delete(name);
        } else {
          remainFuns.push(block);
        }
      }

      // Also pull from FunsExternal_Template
      for (const block of funsExt.blocks) {
        const name = getDeclName(block);
        if (name && funsMoveSet.has(name)) {
          funsPreBlocks.push(block);
          funsMoveSet.delete(name);
        } else {
          remainFunsExt.push(block);
        }
      }

      if (funsMoveSet.size > 0) {
        console.log(chalk.yellow(`  Warning: not found in Funs.lean: ${[...funsMoveSet].join(", ")}`));
      }

      // Sort by config order
      const funsOrderMap = new Map(funsMoveList.map((name, i) => [name, i]));
      funsPreBlocks.sort((a, b) => {
        const nameA = getDeclName(a);
        const nameB = getDeclName(b);
        return (funsOrderMap.get(nameA ?? "") ?? 9999) - (funsOrderMap.get(nameB ?? "") ?? 9999);
      });

      // Fix duplicate field name in ZeroablePrimitive instances
      let funsPreBody = funsPreBlocks.join("\n\n");
      funsPreBody = funsPreBody.replace(
        /^(def U8\.Insts\.CoreNumNonzeroZeroablePrimitiveNonZeroU8Inner[\s\S]*?markerCopyInst := core\.marker\.CopyU8\n  privateSealedInst := U8\.Insts\.CoreNumNonzeroPrivateSealed\n)  markerCopyInst/m,
        "$1  markerCopyInst1"
      );
      funsPreBody = funsPreBody.replace(
        /^(def U64\.Insts\.CoreNumNonzeroZeroablePrimitiveNonZeroU64Inner[\s\S]*?markerCopyInst := core\.marker\.CopyU64\n  privateSealedInst := U64\.Insts\.CoreNumNonzeroPrivateSealed\n)  markerCopyInst/m,
        "$1  markerCopyInst1"
      );

      console.log(`  ${funsPreBlocks.length} declarations → FunsPre.lean`);
      console.log(`  ${remainFuns.length} declarations → Funs.lean`);

      // Build FunsPre.lean
      // Import TypesExternal (not Types) to avoid circular dependency
      const funsPreHeader = funs.header
        .replace("-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS", "-- Generated by scripts/split-types.ts from Aeneas output.")
        .replace(/-- \[.*?\]: function definitions/, "-- Trait instances moved here so Types.lean can reference them.\n-- See the funs_pre list in aeneas-config.yml.")
        .replace(/import \S+\.Types\b/, `import ${modulePath}.TypesExternal`)
        .replace(/import \S+\.FunsExternal\n/, "");
      fs.writeFileSync(funsPrePath, funsPreHeader + "\n" + funsPreBody + "\n\n" + funs.footer + "\n");

      // Rewrite Funs.lean with import of FunsPre
      const newFunsHeader = funs.header.replace(
        /import \S+\.Types\b/,
        `import ${modulePath}.Types\nimport ${modulePath}.FunsPre`
      );
      fs.writeFileSync(funsPath, newFunsHeader + "\n" + remainFuns.join("\n\n") + "\n\n" + funs.footer + "\n");

      // Write FunsExternal.lean (remaining axioms after moving some to FunsPre)
      if (funsExtContent && remainFunsExt.length > 0) {
        let feHeader = funsExt.header;
        fs.writeFileSync(funsExtPath, feHeader + "\n" + remainFunsExt.join("\n\n") + "\n\n" + funsExt.footer + "\n");
      } else if (funsExtContent) {
        // Copy template as-is if nothing was removed
        fs.copyFileSync(funsExtTemplatePath, funsExtPath);
      }

      // Add import of FunsPre to Types.lean (Types needs the trait instances)
      let typesWithFunsPre = fs.readFileSync(typesPath, "utf-8");
      if (!typesWithFunsPre.includes("FunsPre")) {
        typesWithFunsPre = typesWithFunsPre.replace(
          `import ${modulePath}.TypesExternal`,
          `import ${modulePath}.TypesExternal\nimport ${modulePath}.FunsPre`
        );
        fs.writeFileSync(typesPath, typesWithFunsPre);
      }

      console.log(chalk.green("  Funs split complete"));
    }
  }

  console.log(chalk.green("  Split complete"));
}

try {
  main();
} catch (err) {
  console.error(chalk.red(`\nError: ${(err as Error).message}`));
  process.exit(1);
}
