//
// Copyright 2026 Signal Messenger, LLC.
// SPDX-License-Identifier: AGPL-3.0-only
//

use std::collections::HashMap;
use std::convert::Infallible;
use std::str::FromStr;

use libsignal_core::E164;
use libsignal_net_grpc::proto::chat::credentials::credentials_anonymous_client::CredentialsAnonymousClient;
use libsignal_net_grpc::proto::chat::credentials::{
    AuthCheckResult as ProtoAuthCheckResult, CheckSvrCredentialsRequest,
    CheckSvrCredentialsResponse,
};

use crate::api::{RequestError, Unauth};
use crate::grpc::{GrpcServiceProvider, log_and_send};
use crate::logging::Redact;

impl std::fmt::Display for Redact<CheckSvrCredentialsRequest> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let Self(CheckSvrCredentialsRequest { number, passwords }) = self;
        let mut ds = f.debug_struct("CheckSvrCredentialsRequest");
        ds.field("passwords.len()", &passwords.len());
        if let Ok(number) = E164::from_str(number) {
            ds.field("number", &Redact(number));
            ds.finish()
        } else {
            ds.finish_non_exhaustive()
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AuthCheckResult {
    /// The credentials could be used to make a call to SVR service by the user
    /// associated with the `CheckSvrCredentialsRequest.number` phone number.
    Match,
    /// The credentials were generated by a different user.
    NoMatch,
    /// This status indicates that the corresponding credentials token should no longer be used.
    /// This may be because it has expired or invalid, but it can also mean that there is a more
    /// recent token in the request which should be used instead.
    Invalid,
}

impl<T: GrpcServiceProvider> Unauth<T> {
    /// Given a list of secure value recovery (SVR) service credentials and a phone
    /// number, checks and returns which of the provided credentials were generated
    /// by the user with the given phone number and have not yet expired.
    ///
    /// # Parameters
    /// * `number`: A phone number in the E164 format to check the passwords against. Only
    ///   passwords generated for the user associated with the given number will be marked as
    ///   [`AuthCheckResult::Match`].
    /// * `credentials`:  A list of credentials (`username:password`) from previously made calls to
    ///   `ExternalServiceCredentials.GetExternalServiceCredentials()` for
    ///   `EXTERNAL_SERVICE_TYPE_SVR`. This list may contain credentials generated by different
    ///   users. Up to 10 credentials can be checked.
    pub async fn check_svr_credentials(
        &self,
        number: String,
        credentials: Vec<String>,
    ) -> Result<HashMap<String, AuthCheckResult>, RequestError<Infallible>> {
        let mut client = CredentialsAnonymousClient::new(self.0.service());
        let request = CheckSvrCredentialsRequest {
            number,
            passwords: credentials,
        };
        let desc = Redact(&request).to_string();
        let CheckSvrCredentialsResponse { matches } =
            log_and_send("unauth", &desc, || client.check_svr_credentials(request))
                .await?
                .into_inner();
        let mut out = HashMap::with_capacity(matches.len());
        for (k, v) in matches.into_iter() {
            out.insert(
                k,
                match ProtoAuthCheckResult::try_from(v).map_err(|_e| RequestError::Unexpected {
                    log_safe: "Unknown enum value for AuthCheckResult".into(),
                })? {
                    ProtoAuthCheckResult::Unspecified => {
                        return Err(RequestError::Unexpected {
                            log_safe: "Got unspecified AuthCheckResult".into(),
                        });
                    }
                    ProtoAuthCheckResult::Match => AuthCheckResult::Match,
                    ProtoAuthCheckResult::NoMatch => AuthCheckResult::NoMatch,
                    ProtoAuthCheckResult::Invalid => AuthCheckResult::Invalid,
                },
            );
        }
        Ok(out)
    }
}

// Not cfg(test) so it can be accessed via bridging tests.
// These tests will get pruned via LTO tree shaking.
pub mod test_cases {
    use super::*;
    use crate::grpc::GrpcTestCase;
    pub type CheckSvrCredentialsArgs = CheckSvrCredentialsRequest;
    pub type CheckSvrCredentialsOut = HashMap<String, AuthCheckResult>;
    pub fn check_svr_credentials_test_cases() -> Vec<
        GrpcTestCase<
            CheckSvrCredentialsArgs,
            CheckSvrCredentialsRequest,
            CheckSvrCredentialsResponse,
            CheckSvrCredentialsOut,
        >,
    > {
        let method = "/org.signal.chat.credentials.CredentialsAnonymous/CheckSvrCredentials";
        let request = CheckSvrCredentialsRequest {
            number: "+15555551234".to_string(),
            passwords: vec!["a:b".into(), "c:d".into(), "e:f".into(), "g:h".into()],
        };
        vec![GrpcTestCase {
            name: "success".to_string(),
            method: method.to_string(),
            request: request.clone(),
            request_grpc: request.clone(),
            response_grpc: CheckSvrCredentialsResponse {
                matches: HashMap::from_iter([
                    ("match".into(), ProtoAuthCheckResult::Match as i32),
                    ("no_match".into(), ProtoAuthCheckResult::NoMatch as i32),
                    ("invalid".into(), ProtoAuthCheckResult::Invalid as i32),
                ]),
            },
            response: HashMap::from_iter([
                ("match".into(), AuthCheckResult::Match),
                ("no_match".into(), AuthCheckResult::NoMatch),
                ("invalid".into(), AuthCheckResult::Invalid),
            ]),
        }]
    }
}

#[cfg(test)]
mod test {
    use test_cases::*;

    use super::*;
    use crate::grpc::testutil::run_tests;

    #[test]
    fn test_check_svr_credentials() {
        run_tests(
            check_svr_credentials_test_cases(),
            |chat: Unauth<_>, CheckSvrCredentialsArgs { number, passwords }| async move {
                chat.check_svr_credentials(number, passwords).await
            },
            |expected, result| assert_eq!(result.expect("success"), expected),
        );
    }
}
