name: "Release - iOS"

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Just build, don't publish"
        default: false
        required: false
        type: boolean

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build

    permissions:
      # Needed for ncipollo/release-action.
      contents: 'write'
      # Needed for google-github-actions/auth.
      id-token: 'write'

    runs-on: macos-15-xlarge

    timeout-minutes: 45

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        submodules: recursive

    - name: Checking run eligibility
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      with:
        script: |
          const dryRun = ${{ inputs.dry_run }};
          const refType = '${{ github.ref_type }}';
          const refName = '${{ github.ref_name }}';
          console.log(dryRun
            ? `Running in 'dry run' mode on '${refName}' ${refType}`
            : `Running on '${refName}' ${refType}`);
          if (refType !== 'tag' && !dryRun) {
            core.setFailed("the action should either be launched on a tag or with a 'dry run' switch");
          }

    - id: archive-name
      run: echo "name=libsignal-client-ios-build-v$(sed -En "s/${VERSION_REGEX}/\1/p" LibSignalClient.podspec).tar.gz" >> "$GITHUB_OUTPUT"
      env:
        VERSION_REGEX: "^.*[.]version += '(.+)'$"

    - run: rustup toolchain install "$(cat rust-toolchain)" --profile minimal --target x86_64-apple-ios,aarch64-apple-ios,aarch64-apple-ios-sim --component rust-src

    - run: brew install protobuf

    - name: Build for x86_64-apple-ios
      run: swift/build_ffi.sh --release
      env:
        CARGO_BUILD_TARGET: x86_64-apple-ios

    - name: Build for aarch64-apple-ios
      run: swift/build_ffi.sh --release
      env:
        CARGO_BUILD_TARGET: aarch64-apple-ios

    - name: Build for aarch64-apple-ios-sim
      run: swift/build_ffi.sh --release
      env:
        CARGO_BUILD_TARGET: aarch64-apple-ios-sim

    - run: tar -c --auto-compress --no-mac-metadata -f '${{ steps.archive-name.outputs.name }}' target/*/release/libsignal_ffi.a

    - run: shasum -a 256 '${{ steps.archive-name.outputs.name }}' | tee -a "$GITHUB_STEP_SUMMARY" '${{ steps.archive-name.outputs.name }}.sha256'
      shell: bash # Explicitly setting the shell turns on pipefail in GitHub Actions

    - name: Attach artifact to the run
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
      with:
        path: ${{ steps.archive-name.outputs.name }}
        name: libsignal-client-ios

    - uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
      if: ${{ !inputs.dry_run }}
      with:
        workload_identity_provider: 'projects/741367068918/locations/global/workloadIdentityPools/github/providers/github-actions'
        service_account: 'github-actions@signal-build-artifacts.iam.gserviceaccount.com'

    - uses: google-github-actions/upload-cloud-storage@6397bd7208e18d13ba2619ee21b9873edc94427a # v3.0.0
      if: ${{ !inputs.dry_run }}
      with:
        path: ${{ steps.archive-name.outputs.name }}
        destination: build-artifacts.signal.org/libraries

    # This step is expected to fail if not run on a tag.
    - name: Upload checksum to release
      uses: ncipollo/release-action@b7eabc95ff50cbeeedec83973935c8f306dfcd0b # v1.20
      if: ${{ !inputs.dry_run }}
      with:
        allowUpdates: true
        artifactErrorsFailBuild: true
        artifacts: ${{ steps.archive-name.outputs.name }}.sha256
